In [1]:
from Dataload import dataload
import torch.nn.functional as F

import torch
import torch.nn as nn
from torchsummary import summary
from sklearn.metrics import confusion_matrix
from torch.utils.data import Dataset, DataLoader
import matplotlib.pylab as plt
from torchvision import  utils

from src import detect_faces, show_bboxes
from PIL import Image
import numpy as np
from module import video_model
from constant import EMOTIPATH,EMOTIFACEPATH,EMOTIAUDIOPATH
import os
import pandas as pd
import time
from tqdm.notebook import tqdm
import cv2

from torchvision import transforms


In [2]:
Train_label=os.path.join(EMOTIPATH,"Train_labels.txt")
Val_labels=os.path.join(EMOTIPATH,"Val_labels.txt")
Audio_Train=os.path.join(EMOTIAUDIOPATH,"Train_audio.csv")
Audio_Valid=os.path.join(EMOTIAUDIOPATH,"Val_audio.csv")



In [3]:
def num_correct(prediction,labels):
    correct=0
    for i,(pred_label,label) in enumerate(zip(prediction,labels)):
        if (pred_label.item()==label.item()):
            correct +=1
    return correct

class Audio_Data(Dataset):
    def __init__(self,csv_file,audio_path=None):
        self._table = pd.read_csv(csv_file,delimiter=' ')
        self._audio_table=pd.read_csv(audio_path)
    def __len__(self):
        return len(self._table)
    def __getitem__(self, idx):
        audio_feature=self._audio_table.loc[self._audio_table.file_name ==self._table.Vid_name[idx]+'.arff']
        audio_feature=pd.to_numeric(audio_feature.values[0][2:])
        labels = torch.from_numpy(np.array(self._table.Label[idx]))-1
        return (audio_feature,labels)
        



In [4]:
def train(num_epochs,name,model,train_dataloader,valid_dataloader,optimizer,criterion):
    f = open(name+".txt",'a')
    start = time.time()
    #Triaining
    train_loss=[]
    valid_accuracy=[]
    model.train()
    for epochs in range(0,num_epochs):
        first=True
        model.train()
        correct=0
        total_samples=0
        avg_tloss=0
        print("Training Epoch: ", epochs+1,"\n")
        for i_batch, (audio_file,label) in tqdm(enumerate(train_dataloader)):
         
            batch_size=audio_file.size(0)
            optimizer.zero_grad()
            audio_file=audio_file.float().to(device)
            output=model(audio_file)
            loss=criterion(output,label.to(device))
            loss.backward()
            predicted = torch.max(output, 1)
            prediction=predicted.indices.detach().cpu()
            correct +=num_correct(prediction,label)
            total_samples+=batch_size
            accuracy=correct/(total_samples)
            optimizer.step()
            true_label=label.detach().cpu()
            avg_tloss+=loss.item()
            if first:
                first=False
                conf_mat=confusion_matrix( true_label,prediction,labels=[0,1,2])
            else:
                conf_mat+=confusion_matrix(true_label,prediction,labels=[0,1,2])
            if (i_batch+1)%84==0:
               # print(label)
                print("Batch: ",i_batch+1,"/",len(train_dataloader))
                print("Batch Recognition loss: ", loss.item())

        print(conf_mat)
        avg_tloss=avg_tloss/len(train_dataloader)
        avg_taccuracy=correct/total_samples
        print("Average_Loss: ",avg_tloss)
        print("Average_Accuracy: ",avg_taccuracy)

        torch.save(model.state_dict(),name+".pth")
        print("Validation\n")
        model.eval()   
        correct=0
        total_samples=0
        avg_vloss=0
        first=True

        for i_batch, (audio_file,label) in (enumerate(valid_dataloader)):
         
            batch_size=audio_file.size(0)
            optimizer.zero_grad()
            audio_file=audio_file.float().to(device)
            
            output=model(audio_file)
            loss=criterion(output,label.to(device))
            avg_vloss+=loss.item()
            predicted = torch.max(output, 1)
            prediction=predicted.indices.detach().cpu()
            correct +=num_correct(prediction,label)
            total_samples+=batch_size

            true_label=label.detach().cpu()
            if first:
                first=False
                conf_mat=confusion_matrix( true_label,prediction,labels=[0,1,2])
            else:
                conf_mat+=confusion_matrix(true_label,prediction,labels=[0,1,2])
        print(conf_mat)
        avg_vloss=avg_vloss/len(valid_dataloader)
        print(avg_vloss)
        avg_vaccuracy=correct/(total_samples)
        print("Accuracy: ", avg_vaccuracy)

        data = " %f,%f,%f,%f \n" % (avg_tloss,avg_taccuracy,avg_vloss,avg_vaccuracy)
        f.write(data)



    f.close()

In [5]:
model=video_model.AudioRecognition()

device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
torch.set_default_tensor_type(torch.
                              cuda.FloatTensor)
model.to(device)

AudioRecognition(
  (fc1): Linear(in_features=988, out_features=512, bias=True)
  (fc2): Linear(in_features=512, out_features=128, bias=True)
  (fc3): Linear(in_features=128, out_features=3, bias=True)
  (bn1): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (bn2): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU()
)

In [6]:
model(torch.rand(3,988))

tensor([[0.2450, 0.4796, 0.2753],
        [0.4802, 0.2599, 0.2599],
        [0.3152, 0.2651, 0.4197]], grad_fn=<SoftmaxBackward>)

In [7]:
train_set=Audio_Data(Train_label,Audio_Train)
valid_set=Audio_Data(Val_labels,Audio_Valid)


In [8]:
train_dataloader = DataLoader(train_set, batch_size=32
                       , num_workers=0,shuffle=True)

valid_dataloader = DataLoader(valid_set, batch_size=32
                       , num_workers=0,shuffle=False)

In [9]:
optimizer = torch.optim.Adam(filter(lambda p: p.requires_grad, model.parameters()), lr=0.005, betas=(0.5, 0.999))
num_epochs=50
criterion = nn.CrossEntropyLoss()  

model_name="pre_embedded_audio"

In [10]:
train(num_epochs,model_name,model,train_dataloader,valid_dataloader,optimizer,criterion)

Training Epoch:  1 



Batch:  84 / 84
Batch Recognition loss:  0.981432318687439

[[327 271 208]
 [238 511 174]
 [358 283 291]]
Average_Loss:  1.0768274828082038
Average_Accuracy:  0.42427658774896654
Validation

[[ 38 119 142]
 [ 11 177  93]
 [ 18  90  78]]
1.116650549074014
Accuracy:  0.3825065274151436
Training Epoch:  2 



Batch:  84 / 84
Batch Recognition loss:  1.1166741847991943

[[198 304 304]
 [106 613 204]
 [159 280 493]]
Average_Loss:  1.0389756915115176
Average_Accuracy:  0.4900413378429162
Validation

[[ 96 176  27]
 [ 73 198  10]
 [ 81  78  27]]
1.0904515733321507
Accuracy:  0.41906005221932113
Training Epoch:  3 



Batch:  84 / 84
Batch Recognition loss:  1.1042845249176025

[[284 266 256]
 [166 579 178]
 [205 242 485]]
Average_Loss:  1.0168754302320027
Average_Accuracy:  0.506576475009395
Validation

[[ 46 141 112]
 [ 24 165  92]
 [ 21  48 117]]
1.0869081318378448
Accuracy:  0.4281984334203655
Training Epoch:  4 



Batch:  84 / 84
Batch Recognition loss:  1.1947815418243408

[[312 228 266]
 [152 544 227]
 [212 192 528]]
Average_Loss:  1.0126755656231017
Average_Accuracy:  0.5201052236001503
Validation

[[ 90  26 183]
 [ 61  56 164]
 [ 32  20 134]]
1.146715223789215
Accuracy:  0.36553524804177545
Training Epoch:  5 



Batch:  84 / 84
Batch Recognition loss:  1.0180652141571045

[[328 242 236]
 [160 593 170]
 [211 203 518]]
Average_Loss:  0.9881099356072289
Average_Accuracy:  0.5407741450582488
Validation

[[ 52 168  79]
 [ 36 195  50]
 [ 24  63  99]]
1.0712328776717186
Accuracy:  0.4516971279373368
Training Epoch:  6 



Batch:  84 / 84
Batch Recognition loss:  0.872695803642273

[[355 204 247]
 [150 587 186]
 [192 195 545]]
Average_Loss:  0.9733750820159912
Average_Accuracy:  0.5588124765125893
Validation

[[ 20 208  71]
 [  5 225  51]
 [  8  95  83]]
1.1034438883264859
Accuracy:  0.4281984334203655
Training Epoch:  7 



Batch:  84 / 84
Batch Recognition loss:  0.9687120318412781

[[382 203 221]
 [190 558 175]
 [208 171 553]]
Average_Loss:  0.9728625076157706
Average_Accuracy:  0.5610672679443818
Validation

[[253  29  17]
 [208  50  23]
 [142  10  34]]
1.0821392759680748
Accuracy:  0.43994778067885115
Training Epoch:  8 



Batch:  84 / 84
Batch Recognition loss:  1.0839375257492065

[[365 219 222]
 [165 598 160]
 [202 194 536]]
Average_Loss:  0.9681469847758611
Average_Accuracy:  0.5633220593761744
Validation

[[128  76  95]
 [ 96 131  54]
 [ 57  27 102]]
1.0565344368418057
Accuracy:  0.47127937336814624
Training Epoch:  9 



Batch:  84 / 84
Batch Recognition loss:  1.2847785949707031

[[395 212 199]
 [161 613 149]
 [228 186 518]]
Average_Loss:  0.9709659247171312
Average_Accuracy:  0.5734686208192409
Validation

[[105  53 141]
 [ 83 102  96]
 [ 57  18 111]]
1.1019033913811047
Accuracy:  0.4151436031331593
Training Epoch:  10 



Batch:  84 / 84
Batch Recognition loss:  1.00698721408844

[[390 207 209]
 [152 619 152]
 [190 189 553]]
Average_Loss:  0.9542756492183322
Average_Accuracy:  0.5869973694099963
Validation

[[132  38 129]
 [ 87  89 105]
 [ 55   9 122]]
1.0792318632205327
Accuracy:  0.44778067885117495
Training Epoch:  11 



Batch:  84 / 84
Batch Recognition loss:  0.8015205264091492

[[357 235 214]
 [127 620 176]
 [172 202 558]]
Average_Loss:  0.9560149212678274
Average_Accuracy:  0.5768508079669298
Validation

[[ 44 150 105]
 [ 23 189  69]
 [ 23  74  89]]
1.103021835287412
Accuracy:  0.42036553524804177
Training Epoch:  12 



Batch:  84 / 84
Batch Recognition loss:  0.6603258848190308

[[397 193 216]
 [160 580 183]
 [182 173 577]]
Average_Loss:  0.9555518925189972
Average_Accuracy:  0.5839909808342728
Validation

[[ 42 142 115]
 [ 17 197  67]
 [ 12  57 117]]
1.071230078736941
Accuracy:  0.46475195822454307
Training Epoch:  13 



Batch:  84 / 84
Batch Recognition loss:  1.3099197149276733

[[387 219 200]
 [146 618 159]
 [185 194 553]]
Average_Loss:  0.9597665951365516
Average_Accuracy:  0.5854941751221345
Validation

[[127 107  65]
 [ 84 153  44]
 [ 52  49  85]]
1.061305803557237
Accuracy:  0.4765013054830287
Training Epoch:  14 



Batch:  84 / 84
Batch Recognition loss:  1.089935541152954

[[412 206 188]
 [174 599 150]
 [213 177 542]]
Average_Loss:  0.9569470016729265
Average_Accuracy:  0.5836151822623074
Validation

[[184  87  28]
 [138 121  22]
 [ 89  46  51]]
1.0723810096581776
Accuracy:  0.46475195822454307
Training Epoch:  15 



Batch:  84 / 84
Batch Recognition loss:  1.3957808017730713

[[397 202 207]
 [140 619 164]
 [168 190 574]]
Average_Loss:  0.9499802788098654
Average_Accuracy:  0.5975197294250282
Validation

[[ 27 255  17]
 [  9 258  14]
 [ 11 139  36]]
1.1208943923314412
Accuracy:  0.41906005221932113
Training Epoch:  16 



Batch:  84 / 84
Batch Recognition loss:  0.9625029563903809

[[431 193 182]
 [170 596 157]
 [235 162 535]]
Average_Loss:  0.9502502275364739
Average_Accuracy:  0.5869973694099963
Validation

[[129  37 133]
 [109  76  96]
 [ 41  13 132]]
1.094645989437898
Accuracy:  0.43994778067885115
Training Epoch:  17 



Batch:  84 / 84
Batch Recognition loss:  1.3230650424957275

[[413 189 204]
 [158 594 171]
 [178 173 581]]
Average_Loss:  0.9448134913330987
Average_Accuracy:  0.5967681322810974
Validation

[[102 161  36]
 [ 60 194  27]
 [ 54  72  60]]
1.0636618634064992
Accuracy:  0.46475195822454307
Training Epoch:  18 



Batch:  84 / 84
Batch Recognition loss:  0.7499945759773254

[[448 185 173]
 [173 587 163]
 [199 151 582]]
Average_Loss:  0.9337592862901234
Average_Accuracy:  0.6076662908680946
Validation

[[150  92  57]
 [120 126  35]
 [ 62  46  78]]
1.0695001805822055
Accuracy:  0.4621409921671018
Training Epoch:  19 



Batch:  84 / 84
Batch Recognition loss:  0.8948522806167603

[[414 187 205]
 [146 613 164]
 [153 172 607]]
Average_Loss:  0.9273331974233899
Average_Accuracy:  0.614054866591507
Validation

[[124 134  41]
 [ 82 169  30]
 [ 58  59  69]]
1.0613880058129628
Accuracy:  0.4725848563968668
Training Epoch:  20 



Batch:  84 / 84
Batch Recognition loss:  1.1072622537612915

[[404 200 202]
 [150 603 170]
 [142 157 633]]
Average_Loss:  0.931149328038806
Average_Accuracy:  0.6163096580232995
Validation

[[ 79  60 160]
 [ 89 102  90]
 [ 27  22 137]]
1.1162096560001373
Accuracy:  0.4151436031331593
Training Epoch:  21 



Batch:  84 / 84
Batch Recognition loss:  0.9033355712890625

[[402 179 225]
 [160 604 159]
 [162 172 598]]
Average_Loss:  0.9374025130555743
Average_Accuracy:  0.6027809094325441
Validation

[[ 25 123 151]
 [ 16 177  88]
 [  9  49 128]]
1.1058128649989765
Accuracy:  0.4308093994778068
Training Epoch:  22 



Batch:  84 / 84
Batch Recognition loss:  0.5524901151657104

[[397 192 217]
 [150 600 173]
 [175 167 590]]
Average_Loss:  0.9359280041285923
Average_Accuracy:  0.5963923337091319
Validation

[[138 102  59]
 [ 95 146  40]
 [ 59  44  83]]
1.055224244793256
Accuracy:  0.47911227154047
Training Epoch:  23 



Batch:  84 / 84
Batch Recognition loss:  0.9489097595214844

[[417 209 180]
 [145 619 159]
 [171 172 589]]
Average_Loss:  0.9270131311246327
Average_Accuracy:  0.6106726794438181
Validation

[[109  96  94]
 [ 82 140  59]
 [ 39  48  99]]
1.0754555687308311
Accuracy:  0.45430809399477806
Training Epoch:  24 



Batch:  84 / 84
Batch Recognition loss:  0.656262218952179

[[412 183 211]
 [139 629 155]
 [160 161 611]]
Average_Loss:  0.9200001713775453
Average_Accuracy:  0.6208192408868847
Validation

[[ 79 135  85]
 [ 52 178  51]
 [ 31  52 103]]
1.0601689120133717
Accuracy:  0.4699738903394256
Training Epoch:  25 



Batch:  84 / 84
Batch Recognition loss:  0.8475887179374695

[[439 169 198]
 [156 607 160]
 [165 154 613]]
Average_Loss:  0.9189734835000265
Average_Accuracy:  0.6234498308906427
Validation

[[ 49  69 181]
 [ 38 121 122]
 [ 12  23 151]]
1.1125524391730626
Accuracy:  0.41906005221932113
Training Epoch:  26 



Batch:  84 / 84
Batch Recognition loss:  0.7580892443656921

[[418 190 198]
 [141 615 167]
 [161 173 598]]
Average_Loss:  0.9266704760846638
Average_Accuracy:  0.6129274708756107
Validation

[[ 71 143  85]
 [ 51 186  44]
 [ 25  69  92]]
1.0835453247030575
Accuracy:  0.4556135770234987
Training Epoch:  27 



Batch:  84 / 84
Batch Recognition loss:  1.0325334072113037

[[426 180 200]
 [158 595 170]
 [159 156 617]]
Average_Loss:  0.9258241908890861
Average_Accuracy:  0.6155580608793687
Validation

[[109 132  58]
 [ 67 176  38]
 [ 38  57  91]]
1.046100877225399
Accuracy:  0.4908616187989556
Training Epoch:  28 



Batch:  84 / 84
Batch Recognition loss:  0.7436423897743225

[[406 185 215]
 [129 626 168]
 [142 158 632]]
Average_Loss:  0.9196997100398654
Average_Accuracy:  0.6253288237504697
Validation

[[ 83 141  75]
 [ 36 192  53]
 [ 28  54 104]]
1.0419126749038696
Accuracy:  0.49477806788511747
Training Epoch:  29 



Batch:  84 / 84
Batch Recognition loss:  1.4697967767715454

[[438 176 192]
 [155 603 165]
 [169 155 608]]
Average_Loss:  0.9291174241474697
Average_Accuracy:  0.6196918451709883
Validation

[[ 31  48 220]
 [ 30 107 144]
 [  6  20 160]]
1.1490844587484996
Accuracy:  0.38903394255874674
Training Epoch:  30 



Batch:  84 / 84
Batch Recognition loss:  0.5515448451042175

[[438 181 187]
 [156 606 161]
 [172 156 604]]
Average_Loss:  0.9180275634640739
Average_Accuracy:  0.619316046599023
Validation

[[ 73  74 152]
 [ 73 114  94]
 [ 24  31 131]]
1.1160198623935382
Accuracy:  0.4151436031331593
Training Epoch:  31 



Batch:  84 / 84
Batch Recognition loss:  0.9761459231376648

[[424 181 201]
 [152 612 159]
 [148 154 630]]
Average_Loss:  0.915322523031916
Average_Accuracy:  0.6260804208944006
Validation

[[113 111  75]
 [ 81 155  45]
 [ 41  51  94]]
1.0612604121367137
Accuracy:  0.4725848563968668
Training Epoch:  32 



Batch:  84 / 84
Batch Recognition loss:  1.1418120861053467

[[435 181 190]
 [151 618 154]
 [177 162 593]]
Average_Loss:  0.9247676212163198
Average_Accuracy:  0.618564449455092
Validation

[[128 102  69]
 [ 92 143  46]
 [ 49  49  88]]
1.0692483286062877
Accuracy:  0.46866840731070497
Training Epoch:  33 



Batch:  84 / 84
Batch Recognition loss:  0.9543994665145874

[[442 194 170]
 [168 612 143]
 [169 152 611]]
Average_Loss:  0.9111343033256984
Average_Accuracy:  0.6257046223224352
Validation

[[130 107  62]
 [100 134  47]
 [ 50  45  91]]
1.069165197511514
Accuracy:  0.46344647519582244
Training Epoch:  34 



Batch:  84 / 84
Batch Recognition loss:  0.7521608471870422

[[447 177 182]
 [176 601 146]
 [191 143 598]]
Average_Loss:  0.9170045980385372
Average_Accuracy:  0.618564449455092
Validation

[[ 78  63 158]
 [ 61 123  97]
 [ 21  21 144]]
1.0865351830919583
Accuracy:  0.45039164490861616
Training Epoch:  35 



Batch:  84 / 84
Batch Recognition loss:  0.7307841181755066

[[439 179 188]
 [152 629 142]
 [164 152 616]]
Average_Loss:  0.9090168419338408
Average_Accuracy:  0.6328447951897783
Validation

[[114  79 106]
 [ 94 126  61]
 [ 38  39 109]]
1.0806487301985424
Accuracy:  0.4556135770234987
Training Epoch:  36 



Batch:  84 / 84
Batch Recognition loss:  0.8639874458312988

[[442 178 186]
 [151 612 160]
 [180 144 608]]
Average_Loss:  0.9153238953579039
Average_Accuracy:  0.6245772266065389
Validation

[[110 117  72]
 [ 76 159  46]
 [ 41  50  95]]
1.0646743178367615
Accuracy:  0.4751958224543081
Training Epoch:  37 



Batch:  84 / 84
Batch Recognition loss:  0.9589599370956421

[[419 190 197]
 [134 618 171]
 [143 158 631]]
Average_Loss:  0.9148342233328592
Average_Accuracy:  0.6268320180383314
Validation

[[113 150  36]
 [ 72 184  25]
 [ 43  89  54]]
1.0706234474976857
Accuracy:  0.45822454308093996
Training Epoch:  38 



Batch:  84 / 84
Batch Recognition loss:  1.097383737564087

[[427 182 197]
 [149 636 138]
 [158 169 605]]
Average_Loss:  0.9144129696346465
Average_Accuracy:  0.6268320180383314
Validation

[[ 90  66 143]
 [ 83 124  74]
 [ 35  27 124]]
1.0932238822182019
Accuracy:  0.4412532637075718
Training Epoch:  39 



Batch:  84 / 84
Batch Recognition loss:  0.7934736013412476

[[432 169 205]
 [155 616 152]
 [156 150 626]]
Average_Loss:  0.9130279173453649
Average_Accuracy:  0.629086809470124
Validation

[[ 84  93 122]
 [ 54 160  67]
 [ 28  40 118]]
1.063140645623207
Accuracy:  0.4725848563968668
Training Epoch:  40 



Batch:  84 / 84
Batch Recognition loss:  1.124290943145752

[[441 183 182]
 [140 633 150]
 [187 157 588]]
Average_Loss:  0.9143206072705132
Average_Accuracy:  0.6245772266065389
Validation

[[ 97 141  61]
 [ 70 173  38]
 [ 38  66  82]]
1.0670715818802516
Accuracy:  0.4595300261096606
Training Epoch:  41 



Batch:  84 / 84
Batch Recognition loss:  0.9760416746139526

[[439 183 184]
 [146 613 164]
 [140 154 638]]
Average_Loss:  0.9094083976177942
Average_Accuracy:  0.6350995866215708
Validation

[[ 15  46 238]
 [ 19 101 161]
 [  3  17 166]]
1.1789298430085182
Accuracy:  0.3681462140992167
Training Epoch:  42 



Batch:  84 / 84
Batch Recognition loss:  0.9466579556465149

[[452 168 186]
 [166 602 155]
 [162 142 628]]
Average_Loss:  0.9084251125653585
Average_Accuracy:  0.6320931980458474
Validation

[[116 131  52]
 [ 71 173  37]
 [ 45  65  76]]
1.0536655510465305
Accuracy:  0.4765013054830287
Training Epoch:  43 



Batch:  84 / 84
Batch Recognition loss:  0.5614979863166809

[[442 165 199]
 [159 623 141]
 [159 144 629]]
Average_Loss:  0.9003271794035321
Average_Accuracy:  0.6366027809094326
Validation

[[ 54 107 138]
 [ 46 164  71]
 [ 14  65 107]]
1.1079149146874745
Accuracy:  0.42428198433420367
Training Epoch:  44 



Batch:  84 / 84
Batch Recognition loss:  1.1522204875946045

[[444 175 187]
 [142 626 155]
 [147 157 628]]
Average_Loss:  0.9073406649487359
Average_Accuracy:  0.6381059751972943
Validation

[[ 79 126  94]
 [ 63 172  46]
 [ 32  65  89]]
1.085034725566705
Accuracy:  0.44386422976501305
Training Epoch:  45 



Batch:  84 / 84
Batch Recognition loss:  1.0213801860809326

[[449 170 187]
 [151 629 143]
 [152 155 625]]
Average_Loss:  0.9034951953660875
Average_Accuracy:  0.6399849680571214
Validation

[[ 74  74 151]
 [ 62 112 107]
 [ 17  28 141]]
1.1106947486599286
Accuracy:  0.42689295039164493
Training Epoch:  46 



Batch:  84 / 84
Batch Recognition loss:  0.9859333038330078

[[468 179 159]
 [178 626 119]
 [190 182 560]]
Average_Loss:  0.9139190238146555
Average_Accuracy:  0.6215708380308155
Validation

[[ 40 115 144]
 [ 35 163  83]
 [ 12  55 119]]
1.1115562270085018
Accuracy:  0.42036553524804177
Training Epoch:  47 



Batch:  84 / 84
Batch Recognition loss:  1.2052825689315796

[[463 168 175]
 [181 605 137]
 [190 149 593]]
Average_Loss:  0.9176195703801655
Average_Accuracy:  0.6242014280345735
Validation

[[106  70 123]
 [ 88 117  76]
 [ 40  28 118]]
1.0886364777882893
Accuracy:  0.4451697127937337
Training Epoch:  48 



Batch:  84 / 84
Batch Recognition loss:  1.1668592691421509

[[441 170 195]
 [165 610 148]
 [174 137 621]]
Average_Loss:  0.9138705340169725
Average_Accuracy:  0.6283352123261932
Validation

[[145 124  30]
 [100 160  21]
 [ 64  65  57]]
1.0673949991663296
Accuracy:  0.4725848563968668
Training Epoch:  49 



Batch:  84 / 84
Batch Recognition loss:  1.2483855485916138

[[435 168 203]
 [159 615 149]
 [174 153 605]]
Average_Loss:  0.9177954324654171
Average_Accuracy:  0.6219466366027809
Validation

[[123 107  69]
 [ 88 143  50]
 [ 45  55  86]]
1.0716205537319183
Accuracy:  0.4595300261096606
Training Epoch:  50 



Batch:  84 / 84
Batch Recognition loss:  1.1458749771118164

[[461 172 173]
 [173 606 144]
 [170 152 610]]
Average_Loss:  0.9074547035353524
Average_Accuracy:  0.6302142051860203
Validation

[[123  87  89]
 [ 88 137  56]
 [ 49  46  91]]
1.0774105166395505
Accuracy:  0.45822454308093996
