In [1]:
from Dataload import dataload
import torch.nn.functional as F

import torch
import torch.nn as nn
from torchsummary import summary
from sklearn.metrics import confusion_matrix
from torch.utils.data import Dataset, DataLoader
import matplotlib.pylab as plt
from torchvision import  utils

from src import detect_faces, show_bboxes
from PIL import Image
import numpy as np
from module import video_model
from constant import EMOTIPATH,EMOTIFACEPATH,EMOTIAUDIOPATH
import os
import pandas as pd
import time
from tqdm.notebook import tqdm
import cv2
from torchvision import transforms


In [2]:
Train_label=os.path.join(EMOTIPATH,"Train_labels.txt")
Val_labels=os.path.join(EMOTIPATH,"Val_labels.txt")
Audio_Train=os.path.join(EMOTIAUDIOPATH,"Train_audio.csv")
Audio_Valid=os.path.join(EMOTIAUDIOPATH,"Val_audio.csv")



In [11]:
def num_correct(prediction,labels):
    correct=0
    for i,(pred_label,label) in enumerate(zip(prediction,labels)):
        if (pred_label.item()==label.item()):
            correct +=1
    return correct

class Audio_Data(Dataset):
    def __init__(self,csv_file,audio_path=None):
        self._table = pd.read_csv(csv_file,delimiter=' ')
        self._audio_table=pd.read_csv(audio_path)
    def __len__(self):
        return len(self._table)
    def __getitem__(self, idx):
        audio_feature=self._audio_table.loc[self._audio_table.file_name ==self._table.Vid_name[idx]+'.arff']
        audio_feature=pd.to_numeric(audio_feature.values[0][2:])
        labels = torch.from_numpy(np.array(self._table.Label[idx]))-1
        return (audio_feature,labels)
        

class AudioRecognition(nn.Module):
    
    def __init__(self,softmax=True,label=3):
        super(AudioRecognition, self).__init__()
        self.label=label
        self.fc1=nn.Linear(988,512)
        self.fc2=nn.Linear(512,128)
        self.fc3=nn.Linear(128,self.label)
        self.bn1 = nn.BatchNorm1d(num_features=512)
        self.bn2=nn.BatchNorm1d(num_features=128)
        self.relu = nn.ReLU()
        self.softmax=softmax
        
    def forward(self,x):
        x=self.relu(self.bn1(self.fc1(x)))
        x=self.relu(self.bn2((self.fc2(x))))
        x=(self.fc3(x))
        
        if self.softmax:
            return F.softmax(x,1)
        else:
            return self.relu(x)


In [12]:
def train(num_epochs,name,model,train_dataloader,valid_dataloader,optimizer,criterion):
    f = open(name+".txt",'a')
    start = time.time()
    #Triaining
    train_loss=[]
    valid_accuracy=[]
    model.train()
    for epochs in range(0,num_epochs):
        first=True
        model.train()
        correct=0
        total_samples=0
        avg_tloss=0
        print("Training Epoch: ", epochs+1,"\n")
        for i_batch, (audio_file,label) in tqdm(enumerate(train_dataloader)):
         
            batch_size=audio_file.size(0)
            optimizer.zero_grad()
            audio_file=audio_file.float().to(device)
            output=model(audio_file)
            loss=criterion(output,label.to(device))
            loss.backward()
            predicted = torch.max(output, 1)
            prediction=predicted.indices.detach().cpu()
            correct +=num_correct(prediction,label)
            total_samples+=batch_size
            accuracy=correct/(total_samples)
            optimizer.step()
            true_label=label.detach().cpu()
            avg_tloss+=loss.item()
            if first:
                first=False
                conf_mat=confusion_matrix( true_label,prediction,labels=[0,1,2])
            else:
                conf_mat+=confusion_matrix(true_label,prediction,labels=[0,1,2])
            if (i_batch+1)%84==0:
               # print(label)
                print("Batch: ",i_batch+1,"/",len(train_dataloader))
                print("Batch Recognition loss: ", loss.item())

        print(conf_mat)
        avg_tloss=avg_tloss/len(train_dataloader)
        avg_taccuracy=correct/total_samples
        print("Average_Loss: ",avg_tloss)
        print("Average_Accuracy: ",avg_taccuracy)

        torch.save(model.state_dict(),name+".pth")
        print("Validation\n")
        model.eval()   
        correct=0
        total_samples=0
        avg_vloss=0
        first=True

        for i_batch, (audio_file,label) in (enumerate(valid_dataloader)):
         
            batch_size=audio_file.size(0)
            optimizer.zero_grad()
            audio_file=audio_file.float().to(device)
            
            output=model(audio_file)
            loss=criterion(output,label.to(device))
            avg_vloss+=loss.item()
            predicted = torch.max(output, 1)
            prediction=predicted.indices.detach().cpu()
            correct +=num_correct(prediction,label)
            total_samples+=batch_size

            true_label=label.detach().cpu()
            if first:
                first=False
                conf_mat=confusion_matrix( true_label,prediction,labels=[0,1,2])
            else:
                conf_mat+=confusion_matrix(true_label,prediction,labels=[0,1,2])
        print(conf_mat)
        avg_vloss=avg_vloss/len(valid_dataloader)
        print(avg_vloss)
        avg_vaccuracy=correct/(total_samples)
        print("Accuracy: ", avg_vaccuracy)

        data = " %f,%f,%f,%f \n" % (avg_tloss,avg_taccuracy,avg_vloss,avg_vaccuracy)
        f.write(data)



    f.close()

In [13]:
model=AudioRecognition()

device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
torch.set_default_tensor_type(torch.cuda.FloatTensor)
model.to(device)

AudioRecognition(
  (fc1): Linear(in_features=988, out_features=512, bias=True)
  (fc2): Linear(in_features=512, out_features=128, bias=True)
  (fc3): Linear(in_features=128, out_features=3, bias=True)
  (bn1): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (bn2): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU()
)

In [14]:
model(torch.rand(3,988))

tensor([[0.4899, 0.1863, 0.3238],
        [0.3550, 0.2067, 0.4383],
        [0.2335, 0.3245, 0.4420]], grad_fn=<SoftmaxBackward>)

In [15]:
train_set=Audio_Data(Train_label,Audio_Train)
valid_set=Audio_Data(Val_labels,Audio_Valid)


In [16]:
train_dataloader = DataLoader(train_set, batch_size=32
                       , num_workers=0,shuffle=True)

valid_dataloader = DataLoader(valid_set, batch_size=32
                       , num_workers=0,shuffle=False)

In [19]:
optimizer = torch.optim.Adam(filter(lambda p: p.requires_grad, model.parameters()), lr=0.0005, betas=(0.5, 0.999))
num_epochs=50
criterion = nn.CrossEntropyLoss()  

model_name="pre_embedded_audio"

In [20]:
train(num_epochs,model_name,model,train_dataloader,valid_dataloader,optimizer,criterion)

Training Epoch:  1 



Batch:  84 / 84
Batch Recognition loss:  1.1238806247711182

[[643  94  69]
 [ 46 807  70]
 [ 51  88 793]]
Average_Loss:  0.7128347931873231
Average_Accuracy:  0.8429161969184517
Validation

[[ 92 123  84]
 [ 66 155  60]
 [ 34  63  89]]
1.1055021459857624
Accuracy:  0.4386422976501306
Training Epoch:  2 



Batch:  84 / 84
Batch Recognition loss:  0.5625830888748169

[[647  84  75]
 [ 52 817  54]
 [ 40  74 818]]
Average_Loss:  0.6934683521588644
Average_Accuracy:  0.8575723412251034
Validation

[[ 94 125  80]
 [ 78 150  53]
 [ 38  62  86]]
1.1054153442382812
Accuracy:  0.4308093994778068
Training Epoch:  3 



Batch:  84 / 84
Batch Recognition loss:  0.5566364526748657

[[651  82  73]
 [ 56 797  70]
 [ 39  76 817]]
Average_Loss:  0.6956836637996492
Average_Accuracy:  0.8511837655016911
Validation

[[ 99 106  94]
 [ 88 132  61]
 [ 37  51  98]]
1.1041720484693844
Accuracy:  0.42950391644908614
Training Epoch:  4 



Batch:  84 / 84
Batch Recognition loss:  1.134116530418396

[[652  84  70]
 [ 41 825  57]
 [ 36  66 830]]
Average_Loss:  0.6885307232538859
Average_Accuracy:  0.8669673055242391
Validation

[[ 95 111  93]
 [ 72 149  60]
 [ 35  54  97]]
1.0970219522714615
Accuracy:  0.4451697127937337
Training Epoch:  5 



Batch:  84 / 84
Batch Recognition loss:  0.7455648183822632

[[668  75  63]
 [ 45 812  66]
 [ 31  65 836]]
Average_Loss:  0.6815271760736193
Average_Accuracy:  0.8703494926719278
Validation

[[104 104  91]
 [ 91 133  57]
 [ 38  50  98]]
1.1003450552622478
Accuracy:  0.43733681462140994
Training Epoch:  6 



Batch:  84 / 84
Batch Recognition loss:  1.1348888874053955

[[672  68  66]
 [ 45 817  61]
 [ 23  57 852]]
Average_Loss:  0.6764037147873924
Average_Accuracy:  0.8797444569710635
Validation

[[ 92 105 102]
 [ 75 136  70]
 [ 32  49 105]]
1.100900727013747
Accuracy:  0.4347258485639687
Training Epoch:  7 



Batch:  84 / 84
Batch Recognition loss:  0.5514690279960632

[[667  72  67]
 [ 48 827  48]
 [ 26  67 839]]
Average_Loss:  0.6729070671967098
Average_Accuracy:  0.8767380683953401
Validation

[[106 105  88]
 [ 82 140  59]
 [ 43  50  93]]
1.0953230286637943
Accuracy:  0.4425587467362924
Training Epoch:  8 



Batch:  84 / 84
Batch Recognition loss:  0.8877596855163574

[[668  74  64]
 [ 41 829  53]
 [ 23  66 843]]
Average_Loss:  0.672974638286091
Average_Accuracy:  0.8793686583990981
Validation

[[110 101  88]
 [ 87 135  59]
 [ 37  52  97]]
1.0928774053851764
Accuracy:  0.4464751958224543
Training Epoch:  9 



Batch:  84 / 84
Batch Recognition loss:  0.9474565386772156

[[670  74  62]
 [ 46 833  44]
 [ 28  56 848]]
Average_Loss:  0.6705474221990222
Average_Accuracy:  0.8835024426907178
Validation

[[101 113  85]
 [ 79 148  54]
 [ 36  55  95]]
1.0914180527130763
Accuracy:  0.4490861618798956
Training Epoch:  10 



Batch:  84 / 84
Batch Recognition loss:  0.9493656158447266

[[666  78  62]
 [ 48 828  47]
 [ 27  66 839]]
Average_Loss:  0.6766406283492133
Average_Accuracy:  0.8767380683953401
Validation

[[ 82 124  93]
 [ 68 151  62]
 [ 30  58  98]]
1.1011107042431831
Accuracy:  0.4321148825065274
Training Epoch:  11 



Batch:  84 / 84
Batch Recognition loss:  0.7891084551811218

[[673  72  61]
 [ 42 832  49]
 [ 26  59 847]]
Average_Loss:  0.6684051681132543
Average_Accuracy:  0.8838782412626832
Validation

[[ 89  98 112]
 [ 68 144  69]
 [ 33  50 103]]
1.0956494212150574
Accuracy:  0.4386422976501306
Training Epoch:  12 



Batch:  84 / 84
Batch Recognition loss:  0.5549255609512329

[[676  71  59]
 [ 41 836  46]
 [ 22  60 850]]
Average_Loss:  0.6627018607798076
Average_Accuracy:  0.8876362269823375
Validation

[[ 99 118  82]
 [ 72 158  51]
 [ 36  59  91]]
1.089629848798116
Accuracy:  0.45430809399477806
Training Epoch:  13 



Batch:  84 / 84
Batch Recognition loss:  0.5898122787475586

[[680  70  56]
 [ 44 837  42]
 [ 28  60 844]]
Average_Loss:  0.6621244280111223
Average_Accuracy:  0.887260428410372
Validation

[[ 91 134  74]
 [ 65 171  45]
 [ 33  69  84]]
1.0856571247180302
Accuracy:  0.4516971279373368
Training Epoch:  14 



Batch:  84 / 84
Batch Recognition loss:  1.1409661769866943

[[686  70  50]
 [ 46 834  43]
 [ 22  58 852]]
Average_Loss:  0.6651817361513773
Average_Accuracy:  0.8913942127019917
Validation

[[102 113  84]
 [ 74 156  51]
 [ 39  59  88]]
1.0838041255871456
Accuracy:  0.4516971279373368
Training Epoch:  15 



Batch:  84 / 84
Batch Recognition loss:  0.7115412354469299

[[684  65  57]
 [ 40 843  40]
 [ 27  58 847]]
Average_Loss:  0.6599428802728653
Average_Accuracy:  0.8921458098459226
Validation

[[ 94 110  95]
 [ 67 153  61]
 [ 33  57  96]]
1.08980576445659
Accuracy:  0.44778067885117495
Training Epoch:  16 



Batch:  84 / 84
Batch Recognition loss:  1.2483878135681152

[[681  70  55]
 [ 43 839  41]
 [ 22  56 854]]
Average_Loss:  0.6642555076451528
Average_Accuracy:  0.8921458098459226
Validation

[[ 94 115  90]
 [ 73 156  52]
 [ 35  60  91]]
1.0944855486353238
Accuracy:  0.4451697127937337
Training Epoch:  17 



Batch:  84 / 84
Batch Recognition loss:  0.7517698407173157

[[685  69  52]
 [ 36 847  40]
 [ 22  55 855]]
Average_Loss:  0.6573313680433092
Average_Accuracy:  0.8970311912814731
Validation

[[ 94 119  86]
 [ 71 158  52]
 [ 36  62  88]]
1.0912190948923428
Accuracy:  0.44386422976501305
Training Epoch:  18 



Batch:  84 / 84
Batch Recognition loss:  0.7275443077087402

[[685  69  52]
 [ 39 842  42]
 [ 20  55 857]]
Average_Loss:  0.6561502686568669
Average_Accuracy:  0.8959037955655769
Validation

[[109 109  81]
 [ 80 152  49]
 [ 39  56  91]]
1.084112862745921
Accuracy:  0.4595300261096606
Training Epoch:  19 



Batch:  84 / 84
Batch Recognition loss:  0.7536333203315735

[[685  66  55]
 [ 42 839  42]
 [ 21  52 859]]
Average_Loss:  0.6570201842557817
Average_Accuracy:  0.8955279969936114
Validation

[[108 114  77]
 [ 82 151  48]
 [ 44  56  86]]
1.0818242952227592
Accuracy:  0.45039164490861616
Training Epoch:  20 



Batch:  84 / 84
Batch Recognition loss:  0.5514816045761108

[[688  71  47]
 [ 33 846  44]
 [ 26  52 854]]
Average_Loss:  0.6522525761808667
Average_Accuracy:  0.8974069898534386
Validation

[[ 92 117  90]
 [ 69 156  56]
 [ 34  56  96]]
1.0900884096821148
Accuracy:  0.4490861618798956
Training Epoch:  21 



Batch:  84 / 84
Batch Recognition loss:  1.1427202224731445

[[690  65  51]
 [ 40 847  36]
 [ 21  55 856]]
Average_Loss:  0.6578244914611181
Average_Accuracy:  0.8992859827132657
Validation

[[102 106  91]
 [ 77 148  56]
 [ 32  53 101]]
1.0858579998215039
Accuracy:  0.45822454308093996
Training Epoch:  22 



Batch:  84 / 84
Batch Recognition loss:  1.1130073070526123

[[693  69  44]
 [ 40 841  42]
 [ 23  52 857]]
Average_Loss:  0.6579862102156594
Average_Accuracy:  0.8985343855693348
Validation

[[ 85 119  95]
 [ 64 161  56]
 [ 31  54 101]]
1.085332341492176
Accuracy:  0.45300261096605743
Training Epoch:  23 



Batch:  84 / 84
Batch Recognition loss:  0.9503990411758423

[[691  67  48]
 [ 32 853  38]
 [ 21  56 855]]
Average_Loss:  0.6531304348082769
Average_Accuracy:  0.9015407741450583
Validation

[[ 91 126  82]
 [ 65 165  51]
 [ 36  61  89]]
1.0876308555404346
Accuracy:  0.45039164490861616
Training Epoch:  24 



Batch:  84 / 84
Batch Recognition loss:  0.7618972659111023

[[690  66  50]
 [ 36 847  40]
 [ 23  48 861]]
Average_Loss:  0.6506433799153283
Average_Accuracy:  0.9011649755730928
Validation

[[ 97 112  90]
 [ 73 148  60]
 [ 35  52  99]]
1.0860060825943947
Accuracy:  0.4490861618798956
Training Epoch:  25 



Batch:  84 / 84
Batch Recognition loss:  1.349638819694519

[[695  64  47]
 [ 34 852  37]
 [ 25  48 859]]
Average_Loss:  0.6559319794178009
Average_Accuracy:  0.9041713641488163
Validation

[[ 86 119  94]
 [ 55 163  63]
 [ 29  56 101]]
1.0842033649484317
Accuracy:  0.45691906005221933
Training Epoch:  26 



Batch:  84 / 84
Batch Recognition loss:  1.1980102062225342

[[697  60  49]
 [ 31 852  40]
 [ 21  47 864]]
Average_Loss:  0.6510539821216038
Average_Accuracy:  0.9068019541525743
Validation

[[112 101  86]
 [ 83 142  56]
 [ 42  51  93]]
1.0857562348246574
Accuracy:  0.45300261096605743
Training Epoch:  27 



Batch:  84 / 84
Batch Recognition loss:  0.8355226516723633

[[691  66  49]
 [ 34 848  41]
 [ 14  51 867]]
Average_Loss:  0.6486576149861017
Average_Accuracy:  0.9041713641488163
Validation

[[ 91 133  75]
 [ 58 169  54]
 [ 35  64  87]]
1.0841910714904468
Accuracy:  0.45300261096605743
Training Epoch:  28 



Batch:  84 / 84
Batch Recognition loss:  0.6928857564926147

[[698  60  48]
 [ 33 852  38]
 [ 22  47 863]]
Average_Loss:  0.6459374981267112
Average_Accuracy:  0.9068019541525743
Validation

[[ 94  99 106]
 [ 66 145  70]
 [ 29  45 112]]
1.0826053495208423
Accuracy:  0.45822454308093996
Training Epoch:  29 



Batch:  84 / 84
Batch Recognition loss:  0.9517587423324585

[[696  68  42]
 [ 35 853  35]
 [ 20  55 857]]
Average_Loss:  0.6512588454144341
Average_Accuracy:  0.9041713641488163
Validation

[[ 90 117  92]
 [ 60 164  57]
 [ 33  58  95]]
1.0841849620143573
Accuracy:  0.4556135770234987
Training Epoch:  30 



Batch:  84 / 84
Batch Recognition loss:  0.7544621229171753

[[697  60  49]
 [ 31 851  41]
 [ 15  52 865]]
Average_Loss:  0.6459449848958424
Average_Accuracy:  0.9068019541525743
Validation

[[103 115  81]
 [ 67 162  52]
 [ 37  61  88]]
1.0839128742615383
Accuracy:  0.4608355091383812
Training Epoch:  31 



Batch:  84 / 84
Batch Recognition loss:  0.6289607882499695

[[697  69  40]
 [ 35 856  32]
 [ 13  50 869]]
Average_Loss:  0.6424506249881926
Average_Accuracy:  0.910184141300263
Validation

[[113 100  86]
 [ 91 136  54]
 [ 43  49  94]]
1.0873697027564049
Accuracy:  0.44778067885117495
Training Epoch:  32 



Batch:  84 / 84
Batch Recognition loss:  0.7547442317008972

[[700  63  43]
 [ 42 842  39]
 [ 17  49 866]]
Average_Loss:  0.6469498773415884
Average_Accuracy:  0.9049229612927471
Validation

[[ 81 115 103]
 [ 57 157  67]
 [ 26  57 103]]
1.0910065670808156
Accuracy:  0.4451697127937337
Training Epoch:  33 



Batch:  84 / 84
Batch Recognition loss:  0.7985727190971375

[[695  68  43]
 [ 30 856  37]
 [ 18  50 864]]
Average_Loss:  0.6454310878401711
Average_Accuracy:  0.9075535512965051
Validation

[[ 87 110 102]
 [ 55 159  67]
 [ 24  61 101]]
1.0954814131061237
Accuracy:  0.45300261096605743
Training Epoch:  34 



Batch:  84 / 84
Batch Recognition loss:  1.0562629699707031

[[700  66  40]
 [ 35 850  38]
 [ 18  45 869]]
Average_Loss:  0.6463387182780674
Average_Accuracy:  0.9090567455843668
Validation

[[ 99  98 102]
 [ 77 140  64]
 [ 31  49 106]]
1.0905448098977406
Accuracy:  0.45039164490861616
Training Epoch:  35 



Batch:  84 / 84
Batch Recognition loss:  1.136529564857483

[[697  72  37]
 [ 37 852  34]
 [ 18  45 869]]
Average_Loss:  0.6474345667021615
Average_Accuracy:  0.9086809470124013
Validation

[[ 84 113 102]
 [ 61 155  65]
 [ 25  57 104]]
1.0916463434696198
Accuracy:  0.44778067885117495
Training Epoch:  36 



Batch:  84 / 84
Batch Recognition loss:  0.5514488220214844

[[700  66  40]
 [ 38 857  28]
 [ 14  46 872]]
Average_Loss:  0.6386719026735851
Average_Accuracy:  0.912814731304021
Validation

[[115 101  83]
 [ 79 146  56]
 [ 39  52  95]]
1.079857014119625
Accuracy:  0.46475195822454307
Training Epoch:  37 



Batch:  84 / 84
Batch Recognition loss:  0.8181740641593933

[[708  58  40]
 [ 34 851  38]
 [ 17  51 864]]
Average_Loss:  0.6426132151058742
Average_Accuracy:  0.9105599398722285
Validation

[[111 119  69]
 [ 79 156  46]
 [ 41  63  82]]
1.086092360317707
Accuracy:  0.4556135770234987
Training Epoch:  38 



Batch:  84 / 84
Batch Recognition loss:  0.7008112668991089

[[703  63  40]
 [ 26 856  41]
 [ 17  42 873]]
Average_Loss:  0.6383902338289079
Average_Accuracy:  0.9139421270199173
Validation

[[ 93 127  79]
 [ 63 172  46]
 [ 32  64  90]]
1.0858153079946835
Accuracy:  0.46344647519582244
Training Epoch:  39 



Batch:  84 / 84
Batch Recognition loss:  0.7478008270263672

[[699  59  48]
 [ 30 857  36]
 [ 15  45 872]]
Average_Loss:  0.6402747765893028
Average_Accuracy:  0.9124389327320556
Validation

[[ 76 124  99]
 [ 54 161  66]
 [ 24  58 104]]
1.0932973846793175
Accuracy:  0.4451697127937337
Training Epoch:  40 



Batch:  84 / 84
Batch Recognition loss:  0.7539480328559875

[[699  66  41]
 [ 37 848  38]
 [ 13  47 872]]
Average_Loss:  0.6438483326208024
Average_Accuracy:  0.9090567455843668
Validation

[[ 95 118  86]
 [ 68 164  49]
 [ 34  63  89]]
1.0857866058746974
Accuracy:  0.45430809399477806
Training Epoch:  41 



Batch:  84 / 84
Batch Recognition loss:  0.8727031946182251

[[706  59  41]
 [ 31 860  32]
 [ 16  45 871]]
Average_Loss:  0.6388452493009114
Average_Accuracy:  0.9158211198797445
Validation

[[102 116  81]
 [ 81 147  53]
 [ 38  59  89]]
1.0902423411607742
Accuracy:  0.4412532637075718
Training Epoch:  42 



Batch:  84 / 84
Batch Recognition loss:  0.7514444589614868

[[705  59  42]
 [ 28 852  43]
 [ 12  48 872]]
Average_Loss:  0.6406829137177694
Average_Accuracy:  0.912814731304021
Validation

[[105 100  94]
 [ 79 140  62]
 [ 38  49  99]]
1.0842025975386302
Accuracy:  0.4490861618798956
Training Epoch:  43 



Batch:  84 / 84
Batch Recognition loss:  0.9531394839286804

[[698  61  47]
 [ 25 857  41]
 [ 19  46 867]]
Average_Loss:  0.6426020214955012
Average_Accuracy:  0.910184141300263
Validation

[[110 118  71]
 [ 80 155  46]
 [ 40  60  86]]
1.0772419596711795
Accuracy:  0.45822454308093996
Training Epoch:  44 



Batch:  84 / 84
Batch Recognition loss:  1.1496820449829102

[[706  62  38]
 [ 28 860  35]
 [ 13  42 877]]
Average_Loss:  0.6389732375031426
Average_Accuracy:  0.918075911311537
Validation

[[109  90 100]
 [ 85 135  61]
 [ 35  48 103]]
1.08848524838686
Accuracy:  0.45300261096605743
Training Epoch:  45 



Batch:  84 / 84
Batch Recognition loss:  0.9513075947761536

[[703  59  44]
 [ 35 862  26]
 [ 16  42 874]]
Average_Loss:  0.6391655958834148
Average_Accuracy:  0.9165727170236753
Validation

[[105 112  82]
 [ 78 148  55]
 [ 39  53  94]]
1.0843202223380406
Accuracy:  0.45300261096605743
Training Epoch:  46 



Batch:  84 / 84
Batch Recognition loss:  0.9139281511306763

[[706  61  39]
 [ 30 858  35]
 [ 14  44 874]]
Average_Loss:  0.6390823381287711
Average_Accuracy:  0.9161969184517099
Validation

[[ 95 126  78]
 [ 65 167  49]
 [ 34  64  88]]
1.084600495795409
Accuracy:  0.45691906005221933
Training Epoch:  47 



Batch:  84 / 84
Batch Recognition loss:  0.687264621257782

[[699  62  45]
 [ 33 854  36]
 [ 15  43 874]]
Average_Loss:  0.6385915847051711
Average_Accuracy:  0.9120631341600902
Validation

[[112 106  81]
 [ 84 151  46]
 [ 42  56  88]]
1.0792651325464249
Accuracy:  0.45822454308093996
Training Epoch:  48 



Batch:  84 / 84
Batch Recognition loss:  0.7931199073791504

[[706  64  36]
 [ 31 866  26]
 [ 17  42 873]]
Average_Loss:  0.6349866709538868
Average_Accuracy:  0.9188275084554679
Validation

[[103 128  68]
 [ 74 161  46]
 [ 38  66  82]]
1.0848595102628071
Accuracy:  0.4516971279373368
Training Epoch:  49 



Batch:  84 / 84
Batch Recognition loss:  0.9103434681892395

[[707  57  42]
 [ 35 858  30]
 [ 16  38 878]]
Average_Loss:  0.6367891182502111
Average_Accuracy:  0.918075911311537
Validation

[[ 93 118  88]
 [ 63 158  60]
 [ 34  56  96]]
1.08849951873223
Accuracy:  0.45300261096605743
Training Epoch:  50 



Batch:  84 / 84
Batch Recognition loss:  1.2133604288101196

[[700  64  42]
 [ 34 852  37]
 [ 12  46 874]]
Average_Loss:  0.6449994288739704
Average_Accuracy:  0.9116873355881248
Validation

[[ 80 142  77]
 [ 50 184  47]
 [ 28  75  83]]
1.0875975464781125
Accuracy:  0.45300261096605743
