In [1]:
from Dataload import dataload

from module import transformer,video_model,invres

import torch
import torch.nn as nn
from torchsummary import summary
from sklearn.metrics import confusion_matrix
from torch.utils.data import Dataset, DataLoader
import matplotlib.pylab as plt
from torchvision import  utils
import os
from constant import EMOTIPATH
import time
from tqdm.notebook import tqdm


In [2]:
Train_label=os.path.join(EMOTIPATH,"Train_labels.txt")
Train_video=os.path.join(EMOTIPATH,"Train")
Val_labels=os.path.join(EMOTIPATH,"Val_labels.txt")
Val_video=os.path.join(EMOTIPATH,"Val")

frame_num=1
train_data=dataload.Video_Frame_Data(Train_label,"train_new.csv",base_path_v=Train_video,frame_num=frame_num)



In [5]:
train_data[0][0].shape

torch.Size([1, 1000])

In [6]:
#Batchfy
#Counts number of correct label
def num_correct(prediction,labels):
    correct=0
    for i,(pred_label,label) in enumerate(zip(prediction,labels)):
        if (pred_label.item()==label.item()):
            correct +=1
    return correct


valid_data=dataload.Video_Frame_Data(Val_labels,"train_new.csv",base_path_v=Val_video,frame_num=frame_num)

#train_data1=dataload.Video_Embedding_Data("train.csv",Train_label)
#valid_data=dataload.Video_Embedding_Data("valid.csv",Val_labels)
            
train_dataloader = DataLoader(train_data, batch_size=32
                       , num_workers=0,shuffle=True)
#valid_data=dataload.Video_Frame_Data(Val_labels,base_path_v=Val_video,strict_num=26)

valid_dataloader = DataLoader(valid_data, batch_size=32
                       , num_workers=0)

device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
torch.set_default_tensor_type(torch.cuda.FloatTensor)
model=video_model.Encoder(num_frame=frame_num,isframe=1)
for name, child in model.named_children():
   if not name in ['densenet']:
       print(name + ' is unfrozen')
       for param in child.parameters():
           param.requires_grad = True
   else:
       print(name + ' is frozen')
       for param in child.parameters():
           param.requires_grad = False
#model=model.to(device)  
model=model.double().to(device)
#model=model.float()
criterion = nn.CrossEntropyLoss()  
loss_func = torch.nn.MSELoss()

optimizer = torch.optim.Adam(filter(lambda p: p.requires_grad, model.parameters()), lr=0.0002, betas=(0.5, 0.999))

len(train_data)

embedder is unfrozen
fc1 is unfrozen
fc2 is unfrozen
posencoding is unfrozen
transformer is unfrozen


2661

In [7]:
def train(num_epochs,name,model):
    f = open(name+".txt",'a')
    start = time.time()
    #Triaining
    train_loss=[]
    valid_accuracy=[]
    model.train()
    for epochs in range(0,num_epochs):
        first=True
        model.train()
        correct=0
        total_samples=0
        avg_tloss=0
        print("Training Epoch: ", epochs+1,"\n")
        for i_batch, (sample_batched,_,label) in tqdm(enumerate(train_dataloader)):
           # sample_batched=sample_batched.frames
            batch_size=sample_batched.size(0)
            optimizer.zero_grad()
            sample_batched=sample_batched.to(device)
            output=model(sample_batched)
            loss=criterion(output,label.to(device))
            loss.backward()
            predicted = torch.max(output, 1)
            prediction=predicted.indices.detach().cpu()
            correct +=num_correct(prediction,label)
            total_samples+=batch_size
            accuracy=correct/(total_samples)
            optimizer.step()
            true_label=label.detach().cpu()
            avg_tloss+=loss.item()
            if first:
                first=False
                conf_mat=confusion_matrix( true_label,prediction,labels=[0,1,2])
            else:
                conf_mat+=confusion_matrix(true_label,prediction,labels=[0,1,2])
            if i_batch%20==0:
               # print(label)
                print("Batch: ",i_batch+1,"/",len(train_dataloader))
                print("Batch Recognition loss: ", loss.item())

        print(conf_mat)
        avg_tloss=avg_tloss/len(train_dataloader)
        avg_taccuracy=correct/total_samples
        print("Average_Loss: ",avg_tloss)
        print("Average_Accuracy: ",avg_taccuracy)

        torch.save(model.state_dict(),name+".pth")
        print("Validation\n")
        model.eval()   
        correct=0
        total_samples=0
        avg_vloss=0
        first=True

        for i_batch, (sample_batched,_,label) in enumerate(valid_dataloader):
            batch_size=sample_batched.size(0)
            sample_batched=sample_batched.to(device)
            output=model(sample_batched)
            loss=criterion(output,label.to(device))
            avg_vloss+=loss.item()
            predicted = torch.max(output, 1)
            prediction=predicted.indices.detach().cpu()
            correct +=num_correct(prediction,label)
            total_samples+=batch_size

            true_label=label.detach().cpu()
            if first:
                first=False
                conf_mat=confusion_matrix( true_label,prediction,labels=[0,1,2])
            else:
                conf_mat+=confusion_matrix(true_label,prediction,labels=[0,1,2])
        print(conf_mat)
        avg_vloss=avg_vloss/len(valid_dataloader)
        print(avg_vloss)
        avg_vaccuracy=correct/(total_samples)
        print("Accuracy: ", avg_vaccuracy)

        data = " %f,%f,%f,%f \n" % (avg_tloss,avg_taccuracy,avg_vloss,avg_vaccuracy)
        f.write(data)



    f.close()


In [8]:
model_name="pre_embedded_1_frames"
train(20,model_name,model)

Training Epoch:  1 



Batch:  1 / 84
Batch Recognition loss:  1.102019359660783
Batch:  21 / 84
Batch Recognition loss:  1.0067424240337943
Batch:  41 / 84
Batch Recognition loss:  0.8891175967320328
Batch:  61 / 84
Batch Recognition loss:  1.084498578127521
Batch:  81 / 84
Batch Recognition loss:  1.0271528711184057

[[255 278 273]
 [174 476 273]
 [115 189 628]]
Average_Loss:  1.010583182093453
Average_Accuracy:  0.5107102593010147
Validation

[[158  68  73]
 [188  64  29]
 [154  17  15]]
1.1787222578954624
Accuracy:  0.3093994778067885
Training Epoch:  2 



Batch:  1 / 84
Batch Recognition loss:  0.9630548682869428
Batch:  21 / 84
Batch Recognition loss:  0.9699716250431251
Batch:  41 / 84
Batch Recognition loss:  0.943315333444924
Batch:  61 / 84
Batch Recognition loss:  0.9354708185384353
Batch:  81 / 84
Batch Recognition loss:  0.9208720461929907

[[390 223 193]
 [229 481 213]
 [113 132 687]]
Average_Loss:  0.9489865723194912
Average_Accuracy:  0.5854941751221345
Validation

[[ 74 218   7]
 [ 75 201   5]
 [ 58 123   5]]
1.1353248146008197
Accuracy:  0.36553524804177545
Training Epoch:  3 



Batch:  1 / 84
Batch Recognition loss:  0.9580147096886342
Batch:  21 / 84
Batch Recognition loss:  0.8499259133099203
Batch:  41 / 84
Batch Recognition loss:  0.9296086452449996
Batch:  61 / 84
Batch Recognition loss:  0.9235689916120381
Batch:  81 / 84
Batch Recognition loss:  0.8529874102105642

[[441 205 160]
 [191 543 189]
 [106 143 683]]
Average_Loss:  0.9170601550995069
Average_Accuracy:  0.626456219466366
Validation

[[108 144  47]
 [109 160  12]
 [ 83  95   8]]
1.153292243618014
Accuracy:  0.360313315926893
Training Epoch:  4 



Batch:  1 / 84
Batch Recognition loss:  0.8307077192832759
Batch:  21 / 84
Batch Recognition loss:  0.884094779300902
Batch:  41 / 84
Batch Recognition loss:  0.9959029580354364
Batch:  61 / 84
Batch Recognition loss:  0.9027526457112484
Batch:  81 / 84
Batch Recognition loss:  0.8338239693460834

[[468 188 150]
 [195 534 194]
 [ 97 133 702]]
Average_Loss:  0.8985577687981801
Average_Accuracy:  0.6403607666290868
Validation

[[123 131  45]
 [126 137  18]
 [ 92  87   7]]
1.153132828978449
Accuracy:  0.34856396866840733
Training Epoch:  5 



Batch:  1 / 84
Batch Recognition loss:  0.8698647687310017
Batch:  21 / 84
Batch Recognition loss:  0.9155906438554537
Batch:  41 / 84
Batch Recognition loss:  0.982152722619686
Batch:  61 / 84
Batch Recognition loss:  0.8416379705252567
Batch:  81 / 84
Batch Recognition loss:  1.1844478178147584

[[485 172 149]
 [198 540 185]
 [ 85 125 722]]
Average_Loss:  0.8882932645583701
Average_Accuracy:  0.6565201052236002
Validation

[[110 150  39]
 [108 162  11]
 [ 63 116   7]]
1.1465836000002396
Accuracy:  0.3642297650130548
Training Epoch:  6 



Batch:  1 / 84
Batch Recognition loss:  0.9022249372463831
Batch:  21 / 84
Batch Recognition loss:  0.8875897792697705
Batch:  41 / 84
Batch Recognition loss:  0.8193115741832251
Batch:  61 / 84
Batch Recognition loss:  0.8011401852420278
Batch:  81 / 84
Batch Recognition loss:  0.8314394821079641

[[485 177 144]
 [172 577 174]
 [ 73 120 739]]
Average_Loss:  0.8754389493192113
Average_Accuracy:  0.6768132281097332
Validation

[[130  86  83]
 [151  92  38]
 [118  48  20]]
1.1992653081403086
Accuracy:  0.31592689295039167
Training Epoch:  7 



Batch:  1 / 84
Batch Recognition loss:  0.9479680832243395
Batch:  21 / 84
Batch Recognition loss:  0.9083805052273999
Batch:  41 / 84
Batch Recognition loss:  0.8469902453686623
Batch:  61 / 84
Batch Recognition loss:  0.8799813333802347
Batch:  81 / 84
Batch Recognition loss:  1.0115277800928248

[[509 162 135]
 [176 574 173]
 [ 80 113 739]]
Average_Loss:  0.8691945976684585
Average_Accuracy:  0.6847049981210072
Validation

[[118 141  40]
 [123 148  10]
 [ 92  88   6]]
1.157589450183556
Accuracy:  0.35509138381201044
Training Epoch:  8 



Batch:  1 / 84
Batch Recognition loss:  0.7696234399493519
Batch:  21 / 84
Batch Recognition loss:  0.8597094637272826
Batch:  41 / 84
Batch Recognition loss:  0.872724740249655
Batch:  61 / 84
Batch Recognition loss:  0.8392528733939828
Batch:  81 / 84
Batch Recognition loss:  0.8359438345949027

[[524 160 122]
 [171 587 165]
 [ 80 110 742]]
Average_Loss:  0.8509450007675203
Average_Accuracy:  0.6963547538519353
Validation

[[125 135  39]
 [117 154  10]
 [ 91  91   4]]
1.1581343293798434
Accuracy:  0.36945169712793735
Training Epoch:  9 



Batch:  1 / 84
Batch Recognition loss:  0.7860588609355991
Batch:  21 / 84
Batch Recognition loss:  0.728346938919969
Batch:  41 / 84
Batch Recognition loss:  0.7623434362274669
Batch:  61 / 84
Batch Recognition loss:  0.8290374450825305
Batch:  81 / 84
Batch Recognition loss:  0.8167161104240429

[[529 165 112]
 [169 599 155]
 [ 80 105 747]]
Average_Loss:  0.8453204507997223
Average_Accuracy:  0.7046223224351748
Validation

[[159  98  42]
 [161 109  11]
 [124  58   4]]
1.1635335622808596
Accuracy:  0.35509138381201044
Training Epoch:  10 



Batch:  1 / 84
Batch Recognition loss:  0.9629850934776212
Batch:  21 / 84
Batch Recognition loss:  0.7785448758787524
Batch:  41 / 84
Batch Recognition loss:  0.9011026926553913
Batch:  61 / 84
Batch Recognition loss:  0.8686745544632568
Batch:  81 / 84
Batch Recognition loss:  0.8586864164085429

[[537 162 107]
 [168 601 154]
 [ 61 116 755]]
Average_Loss:  0.8398076066422069
Average_Accuracy:  0.7113866967305524
Validation

[[ 81 180  38]
 [ 52 219  10]
 [ 31 149   6]]
1.1362539149153692
Accuracy:  0.39947780678851175
Training Epoch:  11 



Batch:  1 / 84
Batch Recognition loss:  0.884381735834413
Batch:  21 / 84
Batch Recognition loss:  0.9050165750655834
Batch:  41 / 84
Batch Recognition loss:  0.9087417368336574
Batch:  61 / 84
Batch Recognition loss:  0.7726574548452557
Batch:  81 / 84
Batch Recognition loss:  0.696515245953739

[[539 148 119]
 [152 631 140]
 [ 63 111 758]]
Average_Loss:  0.8265490315632038
Average_Accuracy:  0.7245396467493423
Validation

[[129 133  37]
 [123 148  10]
 [ 88  93   5]]
1.152943249097227
Accuracy:  0.3681462140992167
Training Epoch:  12 



Batch:  1 / 84
Batch Recognition loss:  0.8468395280915741
Batch:  21 / 84
Batch Recognition loss:  0.8481870520063087
Batch:  41 / 84
Batch Recognition loss:  0.9232785612315514
Batch:  61 / 84
Batch Recognition loss:  0.7828435490772243
Batch:  81 / 84
Batch Recognition loss:  0.851039387024745

[[547 151 108]
 [163 619 141]
 [ 60 106 766]]
Average_Loss:  0.8225919486053411
Average_Accuracy:  0.7260428410372041
Validation

[[123 138  38]
 [105 165  11]
 [ 91  89   6]]
1.1522255356156041
Accuracy:  0.3838120104438642
Training Epoch:  13 



Batch:  1 / 84
Batch Recognition loss:  0.8036756453990918
Batch:  21 / 84
Batch Recognition loss:  0.7784854853814853
Batch:  41 / 84
Batch Recognition loss:  0.9264868305773087
Batch:  61 / 84
Batch Recognition loss:  0.6694955472300685
Batch:  81 / 84
Batch Recognition loss:  0.7400235346196886

[[574 133  99]
 [154 636 133]
 [ 57 106 769]]
Average_Loss:  0.8078725614904007
Average_Accuracy:  0.7437053739195791
Validation

[[119 139  41]
 [110 160  11]
 [ 86  94   6]]
1.1544192607000128
Accuracy:  0.3720626631853786
Training Epoch:  14 



Batch:  1 / 84
Batch Recognition loss:  0.8537587298027365
Batch:  21 / 84
Batch Recognition loss:  0.8154127964651077
Batch:  41 / 84
Batch Recognition loss:  0.8135075704903808
Batch:  61 / 84
Batch Recognition loss:  0.8600400189550857
Batch:  81 / 84
Batch Recognition loss:  0.7910470393932014

[[581 131  94]
 [156 643 124]
 [ 46 106 780]]
Average_Loss:  0.8044316204789997
Average_Accuracy:  0.7531003382187148
Validation

[[128 129  42]
 [113 155  13]
 [ 80 101   5]]
1.151878387148192
Accuracy:  0.37597911227154046
Training Epoch:  15 



Batch:  1 / 84
Batch Recognition loss:  0.8511985914080176
Batch:  21 / 84
Batch Recognition loss:  0.8258279198913775
Batch:  41 / 84
Batch Recognition loss:  0.844342303905578
Batch:  61 / 84
Batch Recognition loss:  0.8060759298418986
Batch:  81 / 84
Batch Recognition loss:  0.7624425456787224

[[589 120  97]
 [139 651 133]
 [ 54 101 777]]
Average_Loss:  0.7984783419720162
Average_Accuracy:  0.7579857196542653
Validation

[[129 133  37]
 [127 145   9]
 [ 96  85   5]]
1.1683039074469226
Accuracy:  0.3642297650130548
Training Epoch:  16 



Batch:  1 / 84
Batch Recognition loss:  0.7112684880786044
Batch:  21 / 84
Batch Recognition loss:  0.8350842836684247
Batch:  41 / 84
Batch Recognition loss:  0.8232997270800467
Batch:  61 / 84
Batch Recognition loss:  0.8136152017928022
Batch:  81 / 84
Batch Recognition loss:  0.859063415796094

[[579 131  96]
 [150 656 117]
 [ 49 100 783]]
Average_Loss:  0.7973656691213006
Average_Accuracy:  0.7583615182262308
Validation

[[108 127  64]
 [ 98 156  27]
 [ 79  93  14]]
1.1693151059427194
Accuracy:  0.3629242819843342
Training Epoch:  17 



Batch:  1 / 84
Batch Recognition loss:  0.8373484170337316
Batch:  21 / 84
Batch Recognition loss:  0.7774899667292885
Batch:  41 / 84
Batch Recognition loss:  0.8716312595260252
Batch:  61 / 84
Batch Recognition loss:  0.7367976135068652
Batch:  81 / 84
Batch Recognition loss:  0.8547476956633675

[[579 132  95]
 [125 671 127]
 [ 48 102 782]]
Average_Loss:  0.7897025164129834
Average_Accuracy:  0.7636226982337467
Validation

[[138 117  44]
 [136 133  12]
 [109  70   7]]
1.1672317785061777
Accuracy:  0.3629242819843342
Training Epoch:  18 



Batch:  1 / 84
Batch Recognition loss:  0.6984263319886894
Batch:  21 / 84
Batch Recognition loss:  0.8186335166896438
Batch:  41 / 84
Batch Recognition loss:  0.8490359118710014
Batch:  61 / 84
Batch Recognition loss:  0.7996109364446272
Batch:  81 / 84
Batch Recognition loss:  0.7963192593666464

[[597 121  88]
 [134 667 122]
 [ 52  95 785]]
Average_Loss:  0.7838567907075222
Average_Accuracy:  0.770011273957159
Validation

[[136  97  66]
 [127 123  31]
 [101  71  14]]
1.1705148228326572
Accuracy:  0.3563968668407311
Training Epoch:  19 



Batch:  1 / 84
Batch Recognition loss:  0.7796689905538109
Batch:  21 / 84
Batch Recognition loss:  0.7220358807107771
Batch:  41 / 84
Batch Recognition loss:  0.777804916979323
Batch:  61 / 84
Batch Recognition loss:  0.7931002050852936
Batch:  81 / 84
Batch Recognition loss:  0.8157377013315962

[[600 117  89]
 [133 661 129]
 [ 50  97 785]]
Average_Loss:  0.7873943366567879
Average_Accuracy:  0.7688838782412627
Validation

[[144 120  35]
 [129 145   7]
 [103  79   4]]
1.147574156259897
Accuracy:  0.3825065274151436
Training Epoch:  20 



Batch:  1 / 84
Batch Recognition loss:  0.7885921683776084
Batch:  21 / 84
Batch Recognition loss:  0.812432181204799
Batch:  41 / 84
Batch Recognition loss:  0.7980728745366531
Batch:  61 / 84
Batch Recognition loss:  0.8278675745058263
Batch:  81 / 84
Batch Recognition loss:  0.7536954537934001

[[607 117  82]
 [114 694 115]
 [ 41  94 797]]
Average_Loss:  0.7733446067830165
Average_Accuracy:  0.7884254039834648
Validation

[[155 110  34]
 [141 133   7]
 [103  77   6]]
1.1471737572203533
Accuracy:  0.3838120104438642


In [ ]:
print("finished")

In [ ]:
valid_data1=dataload.Video_Frame_Data(Val_labels,base_path_v=Val_video,strict_num=26)

valid_dataloader1 = DataLoader(valid_data1, batch_size=32
                       , num_workers=0)

In [ ]:
debug

In [ ]:
train(1)