In [1]:
from Dataload import dataload

from module import transformer,video_model,invres

import torch
import torch.nn as nn
from torchsummary import summary
from sklearn.metrics import confusion_matrix
from torch.utils.data import Dataset, DataLoader
import matplotlib.pylab as plt
from torchvision import  utils
import os
from constant import EMOTIPATH
import time
from tqdm.notebook import tqdm


In [2]:
#Batchfy
#Counts number of correct label
def num_correct(prediction,labels):
    correct=0
    for i,(pred_label,label) in enumerate(zip(prediction,labels)):
        if (pred_label.item()==label.item()):
            correct +=1
    return correct

Train_label=os.path.join(EMOTIPATH,"Train_labels.txt")
Train_video=os.path.join(EMOTIPATH,"Train")
Val_labels=os.path.join(EMOTIPATH,"Val_labels.txt")
Val_video=os.path.join(EMOTIPATH,"Val")

frame_num=5
train_data=dataload.Video_Frame_Data(Train_label,"train.csv",base_path_v=Train_video,frame_num=frame_num)
valid_data=dataload.Video_Frame_Data(Val_labels,"valid.csv",base_path_v=Val_video,frame_num=frame_num)

#train_data1=dataload.Video_Embedding_Data("train.csv",Train_label)
#valid_data=dataload.Video_Embedding_Data("valid.csv",Val_labels)
            
train_dataloader = DataLoader(train_data, batch_size=32
                       , num_workers=0,shuffle=True)
#valid_data=dataload.Video_Frame_Data(Val_labels,base_path_v=Val_video,strict_num=26)

valid_dataloader = DataLoader(valid_data, batch_size=32
                       , num_workers=0)



len(train_data)

2661

In [3]:
valid_data[60][0].dtype

torch.float64

In [4]:
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
torch.set_default_tensor_type(torch.cuda.FloatTensor)
model=video_model.Video_Feature(joint=False,grayscale=False,classfication=True,frame=frame_num)
for name, child in model.named_children():
   if not name in ['densenet']:
       print(name + ' is unfrozen')
       for param in child.parameters():
           param.requires_grad = True
   else:
       print(name + ' is frozen')
       for param in child.parameters():
           param.requires_grad = False
#model=model.to(device)  
model=model.double().to(device)
#model=model.float()
criterion = nn.CrossEntropyLoss()  
loss_func = torch.nn.MSELoss()

optimizer = torch.optim.Adam(filter(lambda p: p.requires_grad, model.parameters()), lr=0.0002, betas=(0.5, 0.999))


densenet is frozen
fc2 is unfrozen
fc3 is unfrozen
posencoding is unfrozen
transformer is unfrozen


In [6]:
def train(num_epochs,name,model):
    f = open(name+".txt",'a')
    start = time.time()
    #Triaining
    train_loss=[]
    valid_accuracy=[]
    model.train()
    for epochs in range(0,num_epochs):
        first=True
        model.train()
        correct=0
        total_samples=0
        avg_tloss=0
        print("Training Epoch: ", epochs+1,"\n")
        for i_batch, (sample_batched,_,label) in tqdm(enumerate(train_dataloader)):
           # sample_batched=sample_batched.frames
            batch_size=sample_batched.size(0)
            optimizer.zero_grad()
            sample_batched=sample_batched.to(device)
            output=model(sample_batched)
            loss=criterion(output,label.to(device))
            loss.backward()
            predicted = torch.max(output, 1)
            prediction=predicted.indices.detach().cpu()
            correct +=num_correct(prediction,label)
            total_samples+=batch_size
            accuracy=correct/(total_samples)
            optimizer.step()
            true_label=label.detach().cpu()
            avg_tloss+=loss.item()
            if first:
                first=False
                conf_mat=confusion_matrix( true_label,prediction,labels=[0,1,2])
            else:
                conf_mat+=confusion_matrix(true_label,prediction,labels=[0,1,2])
            if i_batch%20==0:
               # print(label)
                print("Batch: ",i_batch+1,"/",len(train_dataloader))
                print("Batch Recognition loss: ", loss.item())

        print(conf_mat)
        avg_tloss=avg_tloss/len(train_dataloader)
        avg_taccuracy=correct/total_samples
        print("Average_Loss: ",avg_tloss)
        print("Average_Accuracy: ",avg_taccuracy)

        torch.save(model.state_dict(),name)
        print("Validation\n")
        model.eval()   
        correct=0
        total_samples=0
        avg_vloss=0
        first=True

        for i_batch, (sample_batched,_,label) in enumerate(valid_dataloader):
            batch_size=sample_batched.size(0)
            sample_batched=sample_batched.to(device)
            output=model(sample_batched)
            loss=criterion(output,label.to(device))
            avg_vloss+=loss.item()
            predicted = torch.max(output, 1)
            prediction=predicted.indices.detach().cpu()
            correct +=num_correct(prediction,label)
            total_samples+=batch_size

            true_label=label.detach().cpu()
            if first:
                first=False
                conf_mat=confusion_matrix( true_label,prediction,labels=[0,1,2])
            else:
                conf_mat+=confusion_matrix(true_label,prediction,labels=[0,1,2])
        print(conf_mat)
        avg_vloss=avg_vloss/len(valid_dataloader)
        print(avg_vloss)
        avg_vaccuracy=correct/(total_samples)
        print("Accuracy: ", avg_vaccuracy)

       # data = " %d,%d,%d,%d \n" % (avg_tloss,avg_taccuracy,avg_vloss,avg_vaccuracy)



    f.close()


In [7]:
model_name="pre_embedded_5_frames"
train(20,model_name,model)

Training Epoch:  1 



Batch:  1 / 84
Batch Recognition loss:  1.09314688594941
Batch:  21 / 84
Batch Recognition loss:  1.0191039765275929
Batch:  41 / 84
Batch Recognition loss:  1.0166374573876193
Batch:  61 / 84
Batch Recognition loss:  1.0508648426365186
Batch:  81 / 84
Batch Recognition loss:  1.0672927621313324

[[522   0 284]
 [604   0 319]
 [285   0 647]]
Average_Loss:  1.048527383433934
Average_Accuracy:  0.4393085306275836
Validation

[[189   0 110]
 [214   0  67]
 [ 38   0 148]]
1.0846347214347585
Accuracy:  0.43994778067885115
Training Epoch:  2 



Batch:  1 / 84
Batch Recognition loss:  1.0000864147496322
Batch:  21 / 84
Batch Recognition loss:  1.0209347529964132
Batch:  41 / 84
Batch Recognition loss:  0.9015418986115982
Batch:  61 / 84
Batch Recognition loss:  1.0098727011112965
Batch:  81 / 84
Batch Recognition loss:  0.9832591385183491

[[589   1 216]
 [675   0 248]
 [238   0 694]]
Average_Loss:  1.008436632755505
Average_Accuracy:  0.48214956783164226
Validation

[[245   0  54]
 [234   0  47]
 [ 61   0 125]]
1.018902190132702
Accuracy:  0.4830287206266319
Training Epoch:  3 



Batch:  1 / 84
Batch Recognition loss:  1.047266420082255
Batch:  21 / 84
Batch Recognition loss:  0.9388785280071814
Batch:  41 / 84
Batch Recognition loss:  0.9548855153158153
Batch:  61 / 84
Batch Recognition loss:  0.9996705107195986
Batch:  81 / 84
Batch Recognition loss:  0.9285935915907997

[[652   0 154]
 [692   0 231]
 [223   0 709]]
Average_Loss:  0.9746558872055214
Average_Accuracy:  0.5114618564449455
Validation

[[247   0  52]
 [237   0  44]
 [101   0  85]]
1.058910591147364
Accuracy:  0.43342036553524804
Training Epoch:  4 



Batch:  1 / 84
Batch Recognition loss:  1.026489743145249
Batch:  21 / 84
Batch Recognition loss:  0.8469583821396199
Batch:  41 / 84
Batch Recognition loss:  1.0274250328917895
Batch:  61 / 84
Batch Recognition loss:  1.0595961593510763
Batch:  81 / 84
Batch Recognition loss:  0.9140614708289088

[[660   0 146]
 [693   0 230]
 [215   0 717]]
Average_Loss:  0.9639896135000893
Average_Accuracy:  0.5174746335963923
Validation

[[207   0  92]
 [208   0  73]
 [ 45   0 141]]
1.0474229801325727
Accuracy:  0.45430809399477806
Training Epoch:  5 



Batch:  1 / 84
Batch Recognition loss:  0.9256727977331123
Batch:  21 / 84
Batch Recognition loss:  0.9116917800852125
Batch:  41 / 84
Batch Recognition loss:  1.0269162998919275
Batch:  61 / 84
Batch Recognition loss:  0.9611550192717886
Batch:  81 / 84
Batch Recognition loss:  1.1320435198231245

[[671   0 135]
 [720   0 203]
 [203   0 729]]
Average_Loss:  0.9495208474130589
Average_Accuracy:  0.5261180007515971
Validation

[[181   0 118]
 [174   0 107]
 [ 27   0 159]]
1.049334444962392
Accuracy:  0.44386422976501305
Training Epoch:  6 



Batch:  1 / 84
Batch Recognition loss:  0.9003138203052481
Batch:  21 / 84
Batch Recognition loss:  1.0409565943724168
Batch:  41 / 84
Batch Recognition loss:  0.911407110747953
Batch:  61 / 84
Batch Recognition loss:  0.9309459925864598
Batch:  81 / 84
Batch Recognition loss:  0.8879755704332736

[[673   0 133]
 [733   0 190]
 [189   0 743]]
Average_Loss:  0.9369179982984716
Average_Accuracy:  0.532130777903044
Validation

[[198   0 101]
 [204   0  77]
 [ 51   0 135]]
1.0765651171054504
Accuracy:  0.4347258485639687
Training Epoch:  7 



Batch:  1 / 84
Batch Recognition loss:  1.0597134654881661
Batch:  21 / 84
Batch Recognition loss:  0.8945761120807364
Batch:  41 / 84
Batch Recognition loss:  0.9761726898333064
Batch:  61 / 84
Batch Recognition loss:  0.9318221127965529
Batch:  81 / 84
Batch Recognition loss:  1.0098172445147895

[[669   0 137]
 [718   0 205]
 [192   0 740]]
Average_Loss:  0.9455757527316757
Average_Accuracy:  0.529500187899286
Validation

[[213   0  86]
 [219   0  62]
 [ 38   0 148]]
1.042550999948711
Accuracy:  0.47127937336814624
Training Epoch:  8 



Batch:  1 / 84
Batch Recognition loss:  0.8442387538754934
Batch:  21 / 84
Batch Recognition loss:  1.0368368146307165
Batch:  41 / 84
Batch Recognition loss:  0.9563012001164395
Batch:  61 / 84
Batch Recognition loss:  0.8489801411723368
Batch:  81 / 84
Batch Recognition loss:  0.8406144571830764

[[701   0 105]
 [723   0 200]
 [186   0 746]]
Average_Loss:  0.9275518424624563
Average_Accuracy:  0.5437805336339722
Validation

[[265   0  34]
 [245   0  36]
 [106   0  80]]
1.0507666655018655
Accuracy:  0.45039164490861616
Training Epoch:  9 



Batch:  1 / 84
Batch Recognition loss:  0.9483152454590745
Batch:  21 / 84
Batch Recognition loss:  0.8685416650357516
Batch:  41 / 84
Batch Recognition loss:  0.9116131578857448
Batch:  61 / 84
Batch Recognition loss:  0.9070087330132747
Batch:  81 / 84
Batch Recognition loss:  0.918290148378285

[[699   0 107]
 [735   0 188]
 [172   0 760]]
Average_Loss:  0.9209167272721582
Average_Accuracy:  0.5482901164975573
Validation

[[216   0  83]
 [211   0  70]
 [ 43   0 143]]
1.035991594654747
Accuracy:  0.46866840731070497
Training Epoch:  10 



Batch:  1 / 84
Batch Recognition loss:  1.0059769183741605
Batch:  21 / 84
Batch Recognition loss:  0.8740405183975731
Batch:  41 / 84
Batch Recognition loss:  0.9354955618685769
Batch:  61 / 84
Batch Recognition loss:  0.8848182761964919
Batch:  81 / 84
Batch Recognition loss:  0.9019424834662773

[[698   0 108]
 [740   0 183]
 [184   0 748]]
Average_Loss:  0.923366215479727
Average_Accuracy:  0.5434047350620068
Validation

[[245   0  54]
 [231   0  50]
 [ 69   0 117]]
1.0389594656159156
Accuracy:  0.4725848563968668
Training Epoch:  11 



Batch:  1 / 84
Batch Recognition loss:  0.8726108721658359
Batch:  21 / 84
Batch Recognition loss:  0.9231616809834325
Batch:  41 / 84
Batch Recognition loss:  0.9716981956905032
Batch:  61 / 84
Batch Recognition loss:  0.7950367068137705
Batch:  81 / 84
Batch Recognition loss:  0.7998117713662636

[[715   0  91]
 [748   0 175]
 [175   0 757]]
Average_Loss:  0.9088130310981418
Average_Accuracy:  0.5531754979331078
Validation

[[210   0  89]
 [196   0  85]
 [ 67   0 119]]
1.0587408964418936
Accuracy:  0.42950391644908614
Training Epoch:  12 



Batch:  1 / 84
Batch Recognition loss:  0.9946031244880039
Batch:  21 / 84
Batch Recognition loss:  0.8851227499331992
Batch:  41 / 84
Batch Recognition loss:  0.9449776538554235
Batch:  61 / 84
Batch Recognition loss:  0.8254388970996416
Batch:  81 / 84
Batch Recognition loss:  0.8655509592398005

[[706   0 100]
 [759   0 164]
 [182   0 750]]
Average_Loss:  0.9079300008990416
Average_Accuracy:  0.5471627207816611
Validation

[[194   0 105]
 [206   0  75]
 [ 41   0 145]]
1.0536114909254042
Accuracy:  0.4425587467362924
Training Epoch:  13 



Batch:  1 / 84
Batch Recognition loss:  0.8863900184682058
Batch:  21 / 84
Batch Recognition loss:  0.8156612295423743
Batch:  41 / 84
Batch Recognition loss:  0.9843141423109739
Batch:  61 / 84
Batch Recognition loss:  0.8919456038024788
Batch:  81 / 84
Batch Recognition loss:  0.8535005063103597

[[723   0  83]
 [766   0 157]
 [167   0 765]]
Average_Loss:  0.8939750152882129
Average_Accuracy:  0.5591882750845547
Validation

[[208   0  91]
 [226   0  55]
 [ 62   0 124]]
1.0445013631893978
Accuracy:  0.43342036553524804
Training Epoch:  14 



Batch:  1 / 84
Batch Recognition loss:  0.909366541787817
Batch:  21 / 84
Batch Recognition loss:  0.8353261197779879
Batch:  41 / 84
Batch Recognition loss:  0.8551336448785885
Batch:  61 / 84
Batch Recognition loss:  0.9382439470875125
Batch:  81 / 84
Batch Recognition loss:  0.8324444848222434

[[719   0  87]
 [767   0 156]
 [157   0 775]]
Average_Loss:  0.8956919840987587
Average_Accuracy:  0.5614430665163472
Validation

[[207   0  92]
 [205   0  76]
 [ 48   0 138]]
1.0525050571792405
Accuracy:  0.45039164490861616
Training Epoch:  15 



Batch:  1 / 84
Batch Recognition loss:  0.9774938140349605
Batch:  21 / 84
Batch Recognition loss:  0.9059156596920236
Batch:  41 / 84
Batch Recognition loss:  0.832036786102751
Batch:  61 / 84
Batch Recognition loss:  0.8170114555504836
Batch:  81 / 84
Batch Recognition loss:  0.8753863924002638

[[726   0  80]
 [748   0 175]
 [167   0 765]]
Average_Loss:  0.9027103079422323
Average_Accuracy:  0.560315670800451
Validation

[[217   0  82]
 [206   0  75]
 [ 62   0 124]]
1.047002638736521
Accuracy:  0.4451697127937337
Training Epoch:  16 



Batch:  1 / 84
Batch Recognition loss:  0.7896489650483478
Batch:  21 / 84
Batch Recognition loss:  0.8315218353133731
Batch:  41 / 84
Batch Recognition loss:  0.829845972246387
Batch:  61 / 84
Batch Recognition loss:  0.903336709874529
Batch:  81 / 84
Batch Recognition loss:  0.9473607848934534

[[736   0  70]
 [769   0 154]
 [157   0 775]]
Average_Loss:  0.8912996514776723
Average_Accuracy:  0.5678316422397595
Validation

[[202   0  97]
 [216   0  65]
 [ 38   0 148]]
1.044528019870427
Accuracy:  0.45691906005221933
Training Epoch:  17 



Batch:  1 / 84
Batch Recognition loss:  0.8740529587545992
Batch:  21 / 84
Batch Recognition loss:  0.8642028071888389
Batch:  41 / 84
Batch Recognition loss:  0.8787183792430536
Batch:  61 / 84
Batch Recognition loss:  0.8117245431285859
Batch:  81 / 84
Batch Recognition loss:  0.907729001485513

[[729   0  77]
 [767   0 156]
 [148   0 784]]
Average_Loss:  0.8868151376683278
Average_Accuracy:  0.5685832393836904
Validation

[[268   0  31]
 [245   0  36]
 [108   0  78]]
1.0280959923742787
Accuracy:  0.4516971279373368
Training Epoch:  18 



Batch:  1 / 84
Batch Recognition loss:  0.8677951430144694
Batch:  21 / 84
Batch Recognition loss:  0.9526891079699809
Batch:  41 / 84
Batch Recognition loss:  0.8627462554980646
Batch:  61 / 84
Batch Recognition loss:  0.8919870511363921
Batch:  81 / 84
Batch Recognition loss:  0.8967352408009495

[[739   0  67]
 [747   0 176]
 [150   0 782]]
Average_Loss:  0.8843209835608251
Average_Accuracy:  0.5715896279594137
Validation

[[286   0  13]
 [267   0  14]
 [165   0  21]]
1.0962828389083992
Accuracy:  0.4007832898172324
Training Epoch:  19 



Batch:  1 / 84
Batch Recognition loss:  0.8959200067212423
Batch:  21 / 84
Batch Recognition loss:  0.8515954335167202
Batch:  41 / 84
Batch Recognition loss:  0.8779243493614618
Batch:  61 / 84
Batch Recognition loss:  0.886039388651647
Batch:  81 / 84
Batch Recognition loss:  0.9125868570708777

[[711   0  95]
 [748   0 175]
 [229   0 703]]
Average_Loss:  0.9355518378775081
Average_Accuracy:  0.5313791807591132
Validation

[[233   0  66]
 [228   0  53]
 [101   0  85]]
1.0609189060803834
Accuracy:  0.4151436031331593
Training Epoch:  20 



Batch:  1 / 84
Batch Recognition loss:  0.9936416735892304
Batch:  21 / 84
Batch Recognition loss:  0.909139766019582
Batch:  41 / 84
Batch Recognition loss:  1.0144843973342754
Batch:  61 / 84
Batch Recognition loss:  0.8928965056549255
Batch:  81 / 84
Batch Recognition loss:  0.9447122266107026

[[719   0  87]
 [742   0 181]
 [208   0 724]]
Average_Loss:  0.9232164562231922
Average_Accuracy:  0.5422773393461104
Validation

[[242   0  57]
 [233   0  48]
 [ 63   0 123]]
1.0407181983358358
Accuracy:  0.4765013054830287


In [ ]:
    model.eval()   
    correct=0
    total_samples=0
    avg_vloss=0
    first=True
    for i_batch, (sample_batched,_,label) in enumerate(valid_dataloader):
        batch_size=sample_batched.size(0)
        sample_batched=sample_batched.to(device)
        output=model(sample_batched)
        loss=criterion(output,label.to(device))
      #  loss=loss_func(output,label.float().to(device))
        avg_vloss+=loss.item()
        predicted = torch.max(output, 1)
        prediction=predicted.indices.detach().cpu()
        correct +=num_correct(prediction,label)
        total_samples+=batch_size
        
        true_label=label.detach().cpu()
        if first:
            first=False
            conf_mat=confusion_matrix( true_label,prediction,labels=[0,1,2])
        else:
            conf_mat+=confusion_matrix(true_label,prediction,labels=[0,1,2])
    print(conf_mat)
    avg_vloss=avg_vloss/len(valid_dataloader)
    print(avg_vloss)
    avg_vaccuracy=correct/(total_samples)
    print("Accuracy: ", avg_vaccuracy)
    
    data = " %d,%d,%d,%d \n" % (avg_tloss,avg_taccuracy,avg_vloss,avg_vaccuracy)


In [ ]:
valid_data1=dataload.Video_Frame_Data(Val_labels,base_path_v=Val_video,strict_num=26)

valid_dataloader1 = DataLoader(valid_data1, batch_size=32
                       , num_workers=0)

In [ ]:
    model.eval()   
    correct=0
    total_samples=0
    avg_vloss=0
    first=True
    model=model.float()
    for i_batch, (sample_batched,_,label) in enumerate(valid_dataloader1):
        batch_size=sample_batched.size(0)
        sample_batched=sample_batched.to(device)
        sample_batched=model.posencoding(model.stack_frame(sample_batched))
        output=model(sample_batched)
        loss=criterion(output,label.to(device))
      #  loss=loss_func(output,label.float().to(device))
        avg_vloss+=loss.item()
        predicted = torch.max(output, 1)
        prediction=predicted.indices.detach().cpu()
        correct +=num_correct(prediction,label)
        total_samples+=batch_size
        
        true_label=label.detach().cpu()
        if first:
            first=False
            conf_mat=confusion_matrix( true_label,prediction,labels=[0,1,2])
        else:
            conf_mat+=confusion_matrix(true_label,prediction,labels=[0,1,2])
    print(conf_mat)
    avg_vloss=avg_vloss/len(valid_dataloader)
    print(avg_vloss)
    avg_vaccuracy=correct/(total_samples)
    print("Accuracy: ", avg_vaccuracy)
    
   # data = " %d,%d,%d,%d \n" % (avg_tloss,avg_taccuracy,avg_vloss,avg_vaccuracy)


In [ ]:
sample_batched

In [ ]:
for i_batch, (sample_batched,label) in enumerate(valid_dataloader):
    debug=sample_batched
    break

In [ ]:
debug

In [ ]:

        output=model(sample_batched)
                                         
        loss=criterion(output,label.to(device))
      #  loss=loss_func(output,label.float().to(device))
        avg_vloss+=loss.item()
        predicted = torch.max(output, 1)
        prediction=predicted.indices.detach().cpu()
        correct +=num_correct(prediction,label)
        total_samples+=batch_size
        
        true_label=label.detach().cpu()
        if first:
            first=False
            conf_mat=confusion_matrix( true_label,prediction,labels=[0,1,2])
        else:
            conf_mat+=confusion_matrix(true_label,prediction,labels=[0,1,2])
    print(conf_mat)
    avg_vloss=avg_vloss/len(valid_dataloader)
    print(avg_vloss)
    avg_vaccuracy=correct/(total_samples)
    print("Accuracy: ", avg_vaccuracy)

In [ ]:
train(1)