In [1]:
#Slef-made Function
from Dataload import dataload
#from module import transformer,video_model

from module import video_model_attention
from constant import EMOTIPATH,EMOTIFACEPATH,EMOTIAUDIOPATH
from train import methods


#Torch Library

import torch
import torch.nn as nn
from torchsummary import summary
from torch.utils.data import Dataset, DataLoader
from torchvision import  utils

#Sub tools
import pandas as pd

import os
import matplotlib.pylab as plt

#Util Library
import time
from tqdm.notebook import tqdm
from mpl_toolkits.axes_grid1 import ImageGrid  

Train_label=os.path.join(EMOTIPATH,"Train_labels.txt")
Train_video_pt=os.path.join(EMOTIPATH,"pt","Train")
Train_face_pt=os.path.join(EMOTIFACEPATH,"pt_stacked","Train")
Audio_Train=os.path.join(EMOTIAUDIOPATH,"Train_audio.csv")

Val_labels=os.path.join(EMOTIPATH,"Val_labels.txt")
Val_video_pt=os.path.join(EMOTIPATH,"pt","Valid")
Val_face_pt=os.path.join(EMOTIFACEPATH,"pt_stacked","Valid")
Audio_Valid=os.path.join(EMOTIAUDIOPATH,"Val_audio.csv")


train_table = pd.read_csv(Train_label,delimiter=' ')
val_table = pd.read_csv(Val_labels,delimiter=' ')
print(train_table['Label'].value_counts())
print(val_table['Label'].value_counts())



device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
torch.set_default_tensor_type(torch.cuda.FloatTensor)



frame_num=10

train_data_pt=dataload.Video_Frame_Data(Train_label,base_path_v=Train_video_pt,face_path=Train_face_pt,frame_num=frame_num,direct=True,audio_csv=Audio_Train)
valid_data_pt=dataload.Video_Frame_Data(Val_labels,base_path_v=Val_video_pt,face_path=Val_face_pt,frame_num=frame_num,direct=True,audio_csv=Audio_Valid)





def load_pretrained_model(pre_train):
    face_model=torch.load("pre_trained_model/" +"pre_trained_resnet18_face.h")
    
   # face_model=torch.load("pre_trained_model/" +"pre_trained_resnet18_facev2.h")
    audio_model=video_model_attention.AudioRecognition(softmax=pre_train)
    audio_model.load_state_dict(torch.load("pre_trained_model/pre_embedded_audio.pth"),strict=False)
    image_model=video_model_attention.Video_modeller(frame_num,face_model=face_model,pre_train=pre_train)
    image_model.load_state_dict(torch.load("image_train_v2/image_train_15.pth"),strict=False)
    return(image_model,audio_model)



def show_img(dataset,index,frame):
    x=dataset[index][0][frame].cpu().numpy()
    plt.figure(1,(15,15))
    plt.axis('off')
    image = (x*0.5+0.5).transpose((1, 2, 0)).squeeze()
    plt.imshow(image)
    
    fig = plt.figure(2,(15,15))
   # plt.axis('off')
    grid = ImageGrid(fig, 111,
                     nrows_ncols=(1,5),
                     axes_pad=0.1,
                     )
    for i in range(5):
        face=dataset[index][1][frame].cpu().numpy()
        image = (face[i,:]*0.5+0.5).transpose((1, 2, 0)).squeeze()
        grid[i].imshow(image,cmap='gray',interpolation='none')
        
img_model,audio_model=load_pretrained_model(False)
model=video_model_attention.video_transformer(img_model,audio_model)


3    932
2    923
1    806
Name: Label, dtype: int64
1    299
2    281
3    186
Name: Label, dtype: int64


In [2]:


weights=[932/932,932/923,932/806]
class_weights = torch.FloatTensor(weights).to(device)

train_dataloader = DataLoader(train_data_pt, batch_size=32
                       , num_workers=0,shuffle=True)
valid_dataloader = DataLoader(valid_data_pt, batch_size=32
                   , num_workers=0)
#model=video_model.video_transformer(img_model,audio_model)
model=model.to(device)

num_epochs=50
criterion = nn.CrossEntropyLoss(weight=class_weights)  

for name, child in model.named_children():
    if not name in ['face_model','frame_model' ]:
        print(name + ' is unfrozen')
        for param in child.parameters():
            param.requires_grad = True
    else:
        print(name + ' is frozen')
        for param in child.parameters():
               param.requires_grad = False

video_model is unfrozen
audio_model is unfrozen
fc1 is unfrozen
fc2 is unfrozen
relu is unfrozen


In [ ]:

optimizer = torch.optim.Adam(filter(lambda p: p.requires_grad, model.parameters()), lr=0.0005, betas=(0.5, 0.999))


model_name="v4_attention"

print(model_name)

methods.full_train("v4_model",num_epochs,model_name,model,train_dataloader,valid_dataloader,optimizer,criterion,device)


v4_attention
Epoch:  1 

Validation 

Validation Loss:  1.0965209652980168
Validation Accuracy:  0.381201044386423
Confusion Matrix: 
 [[145 120  34]
 [140 117  24]
 [124  32  30]]
Train 



Batch:  40 / 84
Batch Recognition loss:  0.9153034090995789
Batch:  80 / 84
Batch Recognition loss:  1.0066038370132446

Average_Loss:  0.9368950447865895
Average_Accuracy:  0.6279594137542277
Confusion Matrix: 
 [[394 205 207]
 [128 645 150]
 [133 167 632]]
Epoch:  2 

Validation 

Validation Loss:  1.0538938790559769
Validation Accuracy:  0.46866840731070497
Confusion Matrix: 
 [[ 98 114  87]
 [ 72 160  49]
 [ 31  54 101]]
Train 



Batch:  40 / 84
Batch Recognition loss:  0.8597193360328674
Batch:  80 / 84
Batch Recognition loss:  0.9309583902359009

Average_Loss:  0.89076138819967
Average_Accuracy:  0.6565201052236002
Confusion Matrix: 
 [[438 180 188]
 [135 644 144]
 [130 137 665]]
Epoch:  3 

Validation 

Validation Loss:  1.0587230895956357
Validation Accuracy:  0.46736292428198434
Confusion Matrix: 
 [[102 104  93]
 [ 72 152  57]
 [ 31  51 104]]
Train 



Batch:  40 / 84
Batch Recognition loss:  0.8649159669876099
Batch:  80 / 84
Batch Recognition loss:  1.0439327955245972

Average_Loss:  0.8753661335933776
Average_Accuracy:  0.6621570838030816
Confusion Matrix: 
 [[457 182 167]
 [142 650 131]
 [132 145 655]]
Epoch:  4 

Validation 

Validation Loss:  1.0528745080033939
Validation Accuracy:  0.47389033942558745
Confusion Matrix: 
 [[105 114  80]
 [ 69 158  54]
 [ 32  54 100]]
Train 



Batch:  40 / 84
Batch Recognition loss:  0.8312543034553528
Batch:  80 / 84
Batch Recognition loss:  1.0222537517547607

Average_Loss:  0.8730565522398267
Average_Accuracy:  0.6700488538143555
Confusion Matrix: 
 [[469 169 168]
 [135 640 148]
 [111 147 674]]
Epoch:  5 

Validation 

Validation Loss:  1.0494604880611103
Validation Accuracy:  0.4804177545691906
Confusion Matrix: 
 [[102 115  82]
 [ 66 161  54]
 [ 29  52 105]]
Train 



Batch:  40 / 84
Batch Recognition loss:  0.8264645934104919
Batch:  80 / 84
Batch Recognition loss:  0.8521234393119812

Average_Loss:  0.8691498800402596
Average_Accuracy:  0.670424652386321
Confusion Matrix: 
 [[455 179 172]
 [125 646 152]
 [ 99 150 683]]
Epoch:  6 

Validation 

Validation Loss:  1.0433305601278942
Validation Accuracy:  0.4869451697127937
Confusion Matrix: 
 [[112 112  75]
 [ 74 155  52]
 [ 40  40 106]]
Train 



Batch:  40 / 84
Batch Recognition loss:  0.8812375068664551
Batch:  80 / 84
Batch Recognition loss:  0.7900131940841675

Average_Loss:  0.871400909054847
Average_Accuracy:  0.6685456595264938
Confusion Matrix: 
 [[459 164 183]
 [135 624 164]
 [100 136 696]]
Epoch:  7 

Validation 

Validation Loss:  1.0506364777684212
Validation Accuracy:  0.47780678851174935
Confusion Matrix: 
 [[100 103  96]
 [ 67 144  70]
 [ 26  38 122]]
Train 



Batch:  40 / 84
Batch Recognition loss:  0.8187997341156006
Batch:  80 / 84
Batch Recognition loss:  0.7827755212783813

Average_Loss:  0.8664833165350414
Average_Accuracy:  0.677564825253664
Confusion Matrix: 
 [[472 164 170]
 [132 649 142]
 [117 133 682]]
Epoch:  8 

Validation 

Validation Loss:  1.058984450995922
Validation Accuracy:  0.4595300261096606
Confusion Matrix: 
 [[100 125  74]
 [ 70 158  53]
 [ 33  59  94]]
Train 



Batch:  40 / 84
Batch Recognition loss:  0.9213515520095825
Batch:  80 / 84
Batch Recognition loss:  0.845168948173523

Average_Loss:  0.8666806071996689
Average_Accuracy:  0.6768132281097332
Confusion Matrix: 
 [[485 149 172]
 [147 635 141]
 [122 129 681]]
Epoch:  9 

Validation 

Validation Loss:  1.0431747982899349
Validation Accuracy:  0.48433420365535246
Confusion Matrix: 
 [[110  99  90]
 [ 74 144  63]
 [ 32  37 117]]
Train 



Batch:  40 / 84
Batch Recognition loss:  0.777309238910675
Batch:  80 / 84
Batch Recognition loss:  0.8695876598358154

Average_Loss:  0.8598603627511433
Average_Accuracy:  0.6798196166854565
Confusion Matrix: 
 [[483 166 157]
 [142 639 142]
 [109 136 687]]
Epoch:  10 

Validation 

Validation Loss:  1.0456963578859966
Validation Accuracy:  0.47389033942558745
Confusion Matrix: 
 [[118 109  72]
 [ 77 150  54]
 [ 42  49  95]]
Train 



Batch:  40 / 84
Batch Recognition loss:  0.7726246118545532
Batch:  80 / 84
Batch Recognition loss:  0.831669807434082

Average_Loss:  0.857273838349751
Average_Accuracy:  0.6888387824126269
Confusion Matrix: 
 [[500 141 165]
 [144 630 149]
 [109 120 703]]
Epoch:  11 

Validation 

Validation Loss:  1.0366044665376346
Validation Accuracy:  0.48433420365535246
Confusion Matrix: 
 [[107 105  87]
 [ 70 148  63]
 [ 27  43 116]]
Train 



Batch:  40 / 84
Batch Recognition loss:  0.8301806449890137
Batch:  80 / 84
Batch Recognition loss:  0.8506730198860168

Average_Loss:  0.8550065734556743
Average_Accuracy:  0.6884629838406614
Confusion Matrix: 
 [[514 141 151]
 [151 633 139]
 [114 133 685]]
Epoch:  12 

Validation 

Validation Loss:  1.0348349958658218
Validation Accuracy:  0.49216710182767626
Confusion Matrix: 
 [[118 106  75]
 [ 74 146  61]
 [ 31  42 113]]
Train 



Batch:  40 / 84
Batch Recognition loss:  0.6637961864471436
Batch:  80 / 84
Batch Recognition loss:  0.7566700577735901

Average_Loss:  0.8571194530952544
Average_Accuracy:  0.6858323938369034
Confusion Matrix: 
 [[492 161 153]
 [143 634 146]
 [103 130 699]]
Epoch:  13 

Validation 

Validation Loss:  1.0311979874968529
Validation Accuracy:  0.49869451697127937
Confusion Matrix: 
 [[125  99  75]
 [ 81 139  61]
 [ 32  36 118]]
Train 



Batch:  40 / 84
Batch Recognition loss:  0.9487319588661194
Batch:  80 / 84
Batch Recognition loss:  0.8737961053848267

Average_Loss:  0.8554764780260268
Average_Accuracy:  0.6907177752724539
Confusion Matrix: 
 [[514 144 148]
 [144 644 135]
 [111 141 680]]
Epoch:  14 

Validation 

Validation Loss:  1.034984938800335
Validation Accuracy:  0.49216710182767626
Confusion Matrix: 
 [[116 113  70]
 [ 78 157  46]
 [ 35  47 104]]
Train 



Batch:  40 / 84
Batch Recognition loss:  0.8973655104637146
Batch:  80 / 84
Batch Recognition loss:  0.867968738079071

Average_Loss:  0.8591932377644947
Average_Accuracy:  0.6843291995490417
Confusion Matrix: 
 [[523 138 145]
 [151 619 153]
 [124 129 679]]
Epoch:  15 

Validation 

Validation Loss:  1.027729871372382
Validation Accuracy:  0.5026109660574413
Confusion Matrix: 
 [[150 115  34]
 [ 99 154  28]
 [ 56  49  81]]
Train 



Batch:  40 / 84
Batch Recognition loss:  0.8058121800422668
Batch:  80 / 84
Batch Recognition loss:  0.8470134139060974

Average_Loss:  0.8592638146309626
Average_Accuracy:  0.6910935738444194
Confusion Matrix: 
 [[533 133 140]
 [153 637 133]
 [136 127 669]]
Epoch:  16 

Validation 

Validation Loss:  1.0518681928515434
Validation Accuracy:  0.47127937336814624
Confusion Matrix: 
 [[ 83 123  93]
 [ 52 167  62]
 [ 18  57 111]]
Train 



Batch:  40 / 84
Batch Recognition loss:  0.8285945653915405
Batch:  80 / 84
Batch Recognition loss:  0.8552040457725525

Average_Loss:  0.8538700562147867
Average_Accuracy:  0.6899661781285231
Confusion Matrix: 
 [[510 153 143]
 [148 647 128]
 [124 129 679]]
Epoch:  17 

Validation 

Validation Loss:  1.0346844121813774
Validation Accuracy:  0.5
Confusion Matrix: 
 [[112 113  74]
 [ 67 154  60]
 [ 24  45 117]]
Train 



Batch:  40 / 84
Batch Recognition loss:  0.8176689743995667
Batch:  80 / 84
Batch Recognition loss:  0.9854987859725952

Average_Loss:  0.8573466411658696
Average_Accuracy:  0.6816986095452837
Confusion Matrix: 
 [[489 150 167]
 [134 642 147]
 [109 140 683]]
Epoch:  18 

Validation 

Validation Loss:  1.047927553455035
Validation Accuracy:  0.47389033942558745
Confusion Matrix: 
 [[116 101  82]
 [ 77 148  56]
 [ 40  47  99]]
Train 



Batch:  40 / 84
Batch Recognition loss:  0.7643409371376038
Batch:  80 / 84
Batch Recognition loss:  0.8754440546035767

Average_Loss:  0.8510584213903972
Average_Accuracy:  0.6918451709883502
Confusion Matrix: 
 [[531 144 131]
 [157 625 141]
 [121 126 685]]
Epoch:  19 

Validation 

Validation Loss:  1.0611195812622707
Validation Accuracy:  0.4595300261096606
Confusion Matrix: 
 [[ 87 104 108]
 [ 60 151  70]
 [ 23  49 114]]
Train 



Batch:  40 / 84
Batch Recognition loss:  0.8418298363685608
Batch:  80 / 84
Batch Recognition loss:  0.9211898446083069

Average_Loss:  0.8542213141918182
Average_Accuracy:  0.6933483652762119
Confusion Matrix: 
 [[506 153 147]
 [148 642 133]
 [106 129 697]]
Epoch:  20 

Validation 

Validation Loss:  1.0419714177648227
Validation Accuracy:  0.4856396866840731
Confusion Matrix: 
 [[121  99  79]
 [ 81 142  58]
 [ 40  37 109]]
Train 



Batch:  40 / 84
Batch Recognition loss:  0.919960618019104
Batch:  80 / 84
Batch Recognition loss:  0.9131171107292175

Average_Loss:  0.8464809869016919
Average_Accuracy:  0.6982337467117625
Confusion Matrix: 
 [[533 153 120]
 [147 639 137]
 [121 125 686]]
Epoch:  21 

Validation 

Validation Loss:  1.065378745396932
Validation Accuracy:  0.45691906005221933
Confusion Matrix: 
 [[ 85  96 118]
 [ 64 142  75]
 [ 24  39 123]]
Train 



Batch:  40 / 84
Batch Recognition loss:  0.7978535294532776
Batch:  80 / 84
Batch Recognition loss:  1.0273592472076416

Average_Loss:  0.8494418178285871
Average_Accuracy:  0.6933483652762119
Confusion Matrix: 
 [[523 148 135]
 [146 637 140]
 [115 132 685]]
Epoch:  22 

Validation 

Validation Loss:  1.0484611814220746
Validation Accuracy:  0.4765013054830287
Confusion Matrix: 
 [[ 98 116  85]
 [ 67 159  55]
 [ 28  50 108]]
Train 



Batch:  40 / 84
Batch Recognition loss:  0.8208186626434326
Batch:  80 / 84
Batch Recognition loss:  0.8895208835601807

Average_Loss:  0.8387816988286518
Average_Accuracy:  0.700488538143555
Confusion Matrix: 
 [[540 138 128]
 [156 638 129]
 [117 129 686]]
Epoch:  23 

Validation 

Validation Loss:  1.0567192509770393
Validation Accuracy:  0.4699738903394256
Confusion Matrix: 
 [[ 89 118  92]
 [ 59 163  59]
 [ 28  50 108]]
Train 



Batch:  40 / 84
Batch Recognition loss:  0.8512193560600281
Batch:  80 / 84
Batch Recognition loss:  0.9215249419212341

Average_Loss:  0.8508020156905765
Average_Accuracy:  0.6914693724163848
Confusion Matrix: 
 [[515 158 133]
 [145 640 138]
 [112 135 685]]
Epoch:  24 

Validation 

Validation Loss:  1.0792188743750255
Validation Accuracy:  0.4451697127937337
Confusion Matrix: 
 [[ 68  85 146]
 [ 55 138  88]
 [ 14  37 135]]
Train 



Batch:  40 / 84
Batch Recognition loss:  0.7344244718551636
Batch:  80 / 84
Batch Recognition loss:  0.7774284482002258

Average_Loss:  0.8559054590406872
Average_Accuracy:  0.6910935738444194
Confusion Matrix: 
 [[512 155 139]
 [151 638 134]
 [126 117 689]]
Epoch:  25 

Validation 

Validation Loss:  1.0419583121935527
Validation Accuracy:  0.4869451697127937
Confusion Matrix: 
 [[118 107  74]
 [ 78 149  54]
 [ 36  44 106]]
Train 



Batch:  40 / 84
Batch Recognition loss:  0.7394565343856812
Batch:  80 / 84
Batch Recognition loss:  0.7508354783058167

Average_Loss:  0.8398755426917758
Average_Accuracy:  0.7049981210071402
Confusion Matrix: 
 [[537 150 119]
 [155 642 126]
 [114 121 697]]
Epoch:  26 

Validation 

Validation Loss:  1.0418142726023991
Validation Accuracy:  0.48172323759791125
Confusion Matrix: 
 [[102 104  93]
 [ 72 158  51]
 [ 29  48 109]]
Train 



Batch:  40 / 84
Batch Recognition loss:  0.8617422580718994
Batch:  80 / 84
Batch Recognition loss:  0.8241968154907227

Average_Loss:  0.8426915031103861
Average_Accuracy:  0.7034949267192785
Confusion Matrix: 
 [[514 152 140]
 [127 657 139]
 [106 125 701]]
Epoch:  27 

Validation 

Validation Loss:  1.047117494046688
Validation Accuracy:  0.47389033942558745
Confusion Matrix: 
 [[ 91 101 107]
 [ 61 150  70]
 [ 24  40 122]]
Train 



Batch:  40 / 84
Batch Recognition loss:  0.892154335975647
Batch:  80 / 84
Batch Recognition loss:  0.8868499994277954

Average_Loss:  0.8444286081052962
Average_Accuracy:  0.6993611424276588
Confusion Matrix: 
 [[521 154 131]
 [128 658 137]
 [121 129 682]]
Epoch:  28 

Validation 

Validation Loss:  1.0603405435880024
Validation Accuracy:  0.46475195822454307
Confusion Matrix: 
 [[ 84 103 112]
 [ 62 150  69]
 [ 22  42 122]]
Train 



Batch:  40 / 84
Batch Recognition loss:  0.8232200741767883
Batch:  80 / 84
Batch Recognition loss:  0.7545556426048279

Average_Loss:  0.8579754055965514
Average_Accuracy:  0.6907177752724539
Confusion Matrix: 
 [[498 158 150]
 [134 661 128]
 [123 130 679]]
Epoch:  29 

Validation 

Validation Loss:  1.04794442653656
Validation Accuracy:  0.48433420365535246
Confusion Matrix: 
 [[111 103  85]
 [ 74 149  58]
 [ 32  43 111]]
Train 



Batch:  40 / 84
Batch Recognition loss:  0.9167807698249817
Batch:  80 / 84
Batch Recognition loss:  0.7913594841957092

Average_Loss:  0.8480708279779979
Average_Accuracy:  0.6899661781285231
Confusion Matrix: 
 [[497 157 152]
 [137 650 136]
 [119 124 689]]
Epoch:  30 

Validation 

Validation Loss:  1.0411730607350667
Validation Accuracy:  0.489556135770235
Confusion Matrix: 
 [[107 103  89]
 [ 66 157  58]
 [ 26  49 111]]
Train 



Batch:  40 / 84
Batch Recognition loss:  0.8838581442832947
Batch:  80 / 84
Batch Recognition loss:  1.0248360633850098

Average_Loss:  0.8501716412249065
Average_Accuracy:  0.6903419767004886
Confusion Matrix: 
 [[501 157 148]
 [139 654 130]
 [125 125 682]]
Epoch:  31 

Validation 

Validation Loss:  1.042866160472234
Validation Accuracy:  0.489556135770235
Confusion Matrix: 
 [[111 103  85]
 [ 74 152  55]
 [ 28  46 112]]
Train 



Batch:  40 / 84
Batch Recognition loss:  0.8067657947540283
Batch:  80 / 84
Batch Recognition loss:  0.9426125884056091

Average_Loss:  0.8545809068850109
Average_Accuracy:  0.685456595264938
Confusion Matrix: 
 [[495 153 158]
 [149 639 135]
 [114 128 690]]
Epoch:  32 

Validation 

Validation Loss:  1.0421347866455715
Validation Accuracy:  0.49216710182767626
Confusion Matrix: 
 [[ 94 116  89]
 [ 57 168  56]
 [ 26  45 115]]
Train 



Batch:  40 / 84
Batch Recognition loss:  0.7909013628959656
Batch:  80 / 84
Batch Recognition loss:  0.7839218378067017

Average_Loss:  0.853480359628087
Average_Accuracy:  0.6922209695603156
Confusion Matrix: 
 [[511 148 147]
 [131 644 148]
 [120 125 687]]
Epoch:  33 

Validation 

Validation Loss:  1.0381359482804935
Validation Accuracy:  0.4908616187989556
Confusion Matrix: 
 [[114 100  85]
 [ 76 152  53]
 [ 32  44 110]]
Train 



Batch:  40 / 84
Batch Recognition loss:  0.9427602291107178
