In [1]:
#Slef-made Function
from Dataload import dataload
#from module import transformer,video_model

from module import video_model_attention
from constant import EMOTIPATH,EMOTIFACEPATH,EMOTIAUDIOPATH
from train import methods


#Torch Library

import torch
import torch.nn as nn
from torchsummary import summary
from torch.utils.data import Dataset, DataLoader
from torchvision import  utils

#Sub tools
import pandas as pd

import os
import matplotlib.pylab as plt

#Util Library
import time
from tqdm.notebook import tqdm
from mpl_toolkits.axes_grid1 import ImageGrid  

Train_label=os.path.join(EMOTIPATH,"Train_labels.txt")
Train_video_pt=os.path.join(EMOTIPATH,"pt","Train")
Train_face_pt=os.path.join(EMOTIFACEPATH,"pt_stacked","Train")
Audio_Train=os.path.join(EMOTIAUDIOPATH,"training_audio_compare_filtered.csv")

Val_labels=os.path.join(EMOTIPATH,"Val_labels.txt")
Val_video_pt=os.path.join(EMOTIPATH,"pt","Valid")
Val_face_pt=os.path.join(EMOTIFACEPATH,"pt_stacked","Valid")
Audio_Valid=os.path.join(EMOTIAUDIOPATH,"validation_audio_compare_filtered.csv")


train_table = pd.read_csv(Train_label,delimiter=' ')
val_table = pd.read_csv(Val_labels,delimiter=' ')
print(train_table['Label'].value_counts())
print(val_table['Label'].value_counts())



device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
torch.set_default_tensor_type(torch.cuda.FloatTensor)



frame_num=10

train_data_pt=dataload.Video_Frame_Data(Train_label,base_path_v=Train_video_pt,face_path=Train_face_pt,frame_num=frame_num,direct=True,audio_csv=Audio_Train)
valid_data_pt=dataload.Video_Frame_Data(Val_labels,base_path_v=Val_video_pt,face_path=Val_face_pt,frame_num=frame_num,direct=True,audio_csv=Audio_Valid)





def load_pretrained_model(pre_train):
    face_model=torch.load("pre_trained_model/" +"pre_trained_resnet18_face.h")
    
   # face_model=torch.load("pre_trained_model/" +"pre_trained_resnet18_facev2.h")
    audio_model=video_model_attention.AudioRecognition(softmax=pre_train)
   # audio_model.load_state_dict(torch.load("pre_trained_model/pre_embedded_audio.pth"),strict=False)
    image_model=video_model_attention.Video_modeller(frame_num,face_model=face_model,pre_train=pre_train)
   # image_model.load_state_dict(torch.load("saved_model_img/img_global_5.pth"),strict=False)
    return(image_model,audio_model)



def show_img(dataset,index,frame):
    x=dataset[index][0][frame].cpu().numpy()
    plt.figure(1,(15,15))
    plt.axis('off')
    image = (x*0.5+0.5).transpose((1, 2, 0)).squeeze()
    plt.imshow(image)
    
    fig = plt.figure(2,(15,15))
   # plt.axis('off')
    grid = ImageGrid(fig, 111,
                     nrows_ncols=(1,5),
                     axes_pad=0.1,
                     )
    for i in range(5):
        face=dataset[index][1][frame].cpu().numpy()
        image = (face[i,:]*0.5+0.5).transpose((1, 2, 0)).squeeze()
        grid[i].imshow(image,cmap='gray',interpolation='none')
        
#img_model,audi=load_pretrained_model(True)
audio_model=video_model_attention.AudioRecognition(softmax=True)


3    932
2    923
1    806
Name: Label, dtype: int64
1    299
2    281
3    186
Name: Label, dtype: int64


In [2]:
df1=pd.read_csv(os.path.join(EMOTIAUDIOPATH,"training_audio_compare.csv"))

In [3]:
df1

Unnamed: 0    file_name  audspec_lengthL1norm_sma_maxPos  \
0              0   101_1.arff                         0.820565   
1              0  101_10.arff                         0.860887   
2              0  101_11.arff                         0.133065   
3              0  101_12.arff                         0.973790   
4              0  101_13.arff                         0.137097   
...          ...          ...                              ...   
2656           0     9_5.arff                         0.520161   
2657           0     9_6.arff                         0.766129   
2658           0     9_7.arff                         0.451613   
2659           0     9_8.arff                         0.616935   
2660           0     9_9.arff                         0.334677   

      audspec_lengthL1norm_sma_minPos  audspec_lengthL1norm_sma_quartile1  \
0                            0.074597                            1.533161   
1                            0.000000                            1.541169   
2                            0.820565                            0.749147   
3                            0.260081                            1.201816   
4                            0.877016                            2.149037   
...                               ...                                 ...   
2656                         0.381048                            0.329917   
2657                         0.614919                            0.171487   
2658                         0.921371                            0.001963   
2659                         0.147177                            0.793189   
2660                         0.000000                            0.678349   

      audspec_lengthL1norm_sma_quartile2  audspec_lengthL1norm_sma_quartile3  \
0                               2.116676                            2.989286   
1                               2.171726                            2.637154   
2                               1.447200                            2.007862   
3                               1.745465                            2.246745   
4                               2.760834                            3.297577   
...                                  ...                                 ...   
2656                            0.544102                            0.764169   
2657                            0.404498                            0.947121   
2658                            0.155606                            0.561355   
2659                            1.099609                            1.490128   
2660                            0.988422                            1.314713   

      audspec_lengthL1norm_sma_iqr1-2  audspec_lengthL1norm_sma_iqr2-3  \
0                            0.583515                         0.872610   
1                            0.630556                         0.465429   
2                            0.698052                         0.560662   
3                            0.543649                         0.501280   
4                            0.611797                         0.536744   
...                               ...                              ...   
2656                         0.214186                         0.220067   
2657                         0.233012                         0.542622   
2658                         0.153643                         0.405749   
2659                         0.306420                         0.390518   
2660                         0.310072                         0.326292   

      audspec_lengthL1norm_sma_iqr1-3  ...  mfcc_sma_de[14]_peakRangeAbs  \
0                            1.456125  ...                     11.437800   
1                            1.095985  ...                      8.345563   
2                            1.258715  ...                      7.392002   
3                            1.044929  ...                      6.569743   
4                            1.148541  ...                

In [4]:
list_na=df1.columns[df1.isna().any()].tolist()

In [5]:
list_na

['pcm_fftMag_spectralSlope_sma_de_lpgain',
 'pcm_fftMag_spectralSlope_sma_de_lpc0',
 'pcm_fftMag_spectralSlope_sma_de_lpc1',
 'pcm_fftMag_spectralSlope_sma_de_lpc2',
 'pcm_fftMag_spectralSlope_sma_de_lpc3',
 'pcm_fftMag_spectralSlope_sma_de_lpc4']

In [6]:


weights=[932/932,932/923,932/806]
class_weights = torch.FloatTensor(weights).to(device)

train_dataloader = DataLoader(train_data_pt, batch_size=32
                       , num_workers=0,shuffle=True)
valid_dataloader = DataLoader(valid_data_pt, batch_size=32
                   , num_workers=0)
#model=video_model.video_transformer(img_model,audio_model)
model=audio_model
model=model.to(device)

num_epochs=50
criterion = nn.CrossEntropyLoss(weight=class_weights)  

for name, child in model.named_children():
    if not name in ['face_model','frame_model' ]:
        print(name + ' is unfrozen')
        for param in child.parameters():
            param.requires_grad = True
    else:
        print(name + ' is frozen')
        for param in child.parameters():
               param.requires_grad = False

fc1 is unfrozen
fc2 is unfrozen
fc3 is unfrozen
relu is unfrozen
tanh is unfrozen


In [7]:
model(train_data_pt[8][2].unsqueeze(0).float().to(device))

tensor([[0., 1., 0.]], grad_fn=<SoftmaxBackward>)

In [8]:
train_data_pt[6][2]

tensor([ 0.5242,  0.5887,  0.5940,  ..., 50.9046, 95.2676, 45.5413],
       device='cpu', dtype=torch.float64)

In [9]:

optimizer = torch.optim.Adam(filter(lambda p: p.requires_grad, model.parameters()), lr=0.0005, betas=(0.5, 0.999))


model_name="audio_train_v2"

print(model_name)

methods.audio_train("audio_train_v2",num_epochs,model_name,model,train_dataloader,valid_dataloader,optimizer,criterion,device)


audio_train_v2
Epoch:  1 

Validation 

Validation Loss:  1.1905978148182232
Validation Accuracy:  0.3668407310704961
Confusion Matrix: 
 [[  0 299   0]
 [  0 281   0]
 [  0 186   0]]


Batch:  40 / 84
Batch Recognition loss:  1.2826348543167114
Batch:  80 / 84
Batch Recognition loss:  1.3451135158538818

Average_Loss:  1.2213762516067141
Average_Accuracy:  0.34723788049605414
Confusion Matrix: 
 [[  2 803   1]
 [  0 922   1]
 [  0 932   0]]
Epoch:  2 

Validation 

Validation Loss:  1.1911175573865573
Validation Accuracy:  0.3668407310704961
Confusion Matrix: 
 [[  0 299   0]
 [  0 281   0]
 [  0 186   0]]


Batch:  40 / 84
Batch Recognition loss:  1.2838720083236694
Batch:  80 / 84
Batch Recognition loss:  1.3753430843353271

Average_Loss:  1.2189583381017048
Average_Accuracy:  0.34723788049605414
Confusion Matrix: 
 [[  2 803   1]
 [  0 922   1]
 [  0 932   0]]
Epoch:  3 

Validation 

Validation Loss:  1.1911175573865573
Validation Accuracy:  0.3668407310704961
Confusion Matrix: 
 [[  0 299   0]
 [  0 281   0]
 [  0 186   0]]


Batch:  40 / 84
Batch Recognition loss:  1.3712489604949951
Batch:  80 / 84
Batch Recognition loss:  1.3469796180725098

Average_Loss:  1.2192763899053847
Average_Accuracy:  0.34723788049605414
Confusion Matrix: 
 [[  2 803   1]
 [  0 922   1]
 [  0 932   0]]
Epoch:  4 

Validation 

Validation Loss:  1.1911175573865573
Validation Accuracy:  0.3668407310704961
Confusion Matrix: 
 [[  0 299   0]
 [  0 281   0]
 [  0 186   0]]


Batch:  40 / 84
Batch Recognition loss:  1.167160987854004
Batch:  80 / 84
Batch Recognition loss:  1.1653939485549927

Average_Loss:  1.2210407767977034
Average_Accuracy:  0.34723788049605414
Confusion Matrix: 
 [[  2 803   1]
 [  0 922   1]
 [  0 932   0]]
Epoch:  5 

Validation 

Validation Loss:  1.1911175573865573
Validation Accuracy:  0.3668407310704961
Confusion Matrix: 
 [[  0 299   0]
 [  0 281   0]
 [  0 186   0]]


Batch:  40 / 84
Batch Recognition loss:  1.1900014877319336
Batch:  80 / 84
Batch Recognition loss:  1.2839490175247192

Average_Loss:  1.2229453594911666
Average_Accuracy:  0.34723788049605414
Confusion Matrix: 
 [[  2 803   1]
 [  0 922   1]
 [  0 932   0]]
Epoch:  6 

Validation 

Validation Loss:  1.1911175573865573
Validation Accuracy:  0.3668407310704961
Confusion Matrix: 
 [[  0 299   0]
 [  0 281   0]
 [  0 186   0]]


Batch:  40 / 84
Batch Recognition loss:  1.2528533935546875
Batch:  80 / 84
Batch Recognition loss:  1.2245991230010986

Average_Loss:  1.2228876494226002
Average_Accuracy:  0.34723788049605414
Confusion Matrix: 
 [[  2 803   1]
 [  0 922   1]
 [  0 932   0]]
Epoch:  7 

Validation 

Validation Loss:  1.1911175573865573
Validation Accuracy:  0.3668407310704961
Confusion Matrix: 
 [[  0 299   0]
 [  0 281   0]
 [  0 186   0]]


Batch:  40 / 84
Batch Recognition loss:  1.2230887413024902
Batch:  80 / 84
Batch Recognition loss:  1.2850980758666992

Average_Loss:  1.219477375348409
Average_Accuracy:  0.34723788049605414
Confusion Matrix: 
 [[  2 803   1]
 [  0 922   1]
 [  0 932   0]]
Epoch:  8 

Validation 

Validation Loss:  1.1911175573865573
Validation Accuracy:  0.3668407310704961
Confusion Matrix: 
 [[  0 299   0]
 [  0 281   0]
 [  0 186   0]]


Batch:  40 / 84
Batch Recognition loss:  1.1933413743972778
Batch:  80 / 84
Batch Recognition loss:  1.2230888605117798

Average_Loss:  1.2191573154358637
Average_Accuracy:  0.34723788049605414
Confusion Matrix: 
 [[  2 803   1]
 [  0 922   1]
 [  0 932   0]]
Epoch:  9 

Validation 

Validation Loss:  1.1911175573865573
Validation Accuracy:  0.3668407310704961
Confusion Matrix: 
 [[  0 299   0]
 [  0 281   0]
 [  0 186   0]]


Batch:  40 / 84
Batch Recognition loss:  1.1563111543655396
Batch:  80 / 84
Batch Recognition loss:  1.1816667318344116

Average_Loss:  1.2212003739107222
Average_Accuracy:  0.34723788049605414
Confusion Matrix: 
 [[  2 803   1]
 [  0 922   1]
 [  0 932   0]]
Epoch:  10 

Validation 

Validation Loss:  1.1911175573865573
Validation Accuracy:  0.3668407310704961
Confusion Matrix: 
 [[  0 299   0]
 [  0 281   0]
 [  0 186   0]]


Batch:  40 / 84
Batch Recognition loss:  1.1319609880447388
Batch:  80 / 84
Batch Recognition loss:  1.1966198682785034

Average_Loss:  1.2154504507780075
Average_Accuracy:  0.34723788049605414
Confusion Matrix: 
 [[  2 803   1]
 [  0 922   1]
 [  0 932   0]]
Epoch:  11 

Validation 

Validation Loss:  1.1911175573865573
Validation Accuracy:  0.3668407310704961
Confusion Matrix: 
 [[  0 299   0]
 [  0 281   0]
 [  0 186   0]]


Batch:  40 / 84
Batch Recognition loss:  1.3469798564910889
Batch:  80 / 84
Batch Recognition loss:  1.1599953174591064

Average_Loss:  1.2191288598946162
Average_Accuracy:  0.34723788049605414
Confusion Matrix: 
 [[  2 803   1]
 [  0 922   1]
 [  0 932   0]]
Epoch:  12 

Validation 

Validation Loss:  1.1911175573865573
Validation Accuracy:  0.3668407310704961
Confusion Matrix: 
 [[  0 299   0]
 [  0 281   0]
 [  0 186   0]]


Batch:  40 / 84
Batch Recognition loss:  1.194988489151001
Batch:  80 / 84
Batch Recognition loss:  1.2595986127853394

Average_Loss:  1.219390652009419
Average_Accuracy:  0.34723788049605414
Confusion Matrix: 
 [[  2 803   1]
 [  0 922   1]
 [  0 932   0]]
Epoch:  13 

Validation 

Validation Loss:  1.1911175573865573
Validation Accuracy:  0.3668407310704961
Confusion Matrix: 
 [[  0 299   0]
 [  0 281   0]
 [  0 186   0]]


Batch:  40 / 84
Batch Recognition loss:  1.1933413743972778
Batch:  80 / 84
Batch Recognition loss:  1.3432132005691528

Average_Loss:  1.2231564621130626
Average_Accuracy:  0.34723788049605414
Confusion Matrix: 
 [[  2 803   1]
 [  0 922   1]
 [  0 932   0]]
Epoch:  14 

Validation 

Validation Loss:  1.1911175573865573
Validation Accuracy:  0.3668407310704961
Confusion Matrix: 
 [[  0 299   0]
 [  0 281   0]
 [  0 186   0]]


RuntimeError: CUDA out of memory. Tried to allocate 150.00 MiB (GPU 0; 10.75 GiB total capacity; 6.07 GiB already allocated; 129.00 MiB free; 117.38 MiB cached)