In [1]:
#Slef-made Function
from Dataload import dataload
#from module import transformer,video_model

from module import video_model_attention
from constant import EMOTIPATH,EMOTIFACEPATH,EMOTIAUDIOPATH
from train import methods


#Torch Library

import torch
import torch.nn as nn
from torchsummary import summary
from torch.utils.data import Dataset, DataLoader
from torchvision import  utils

#Sub tools
import pandas as pd

import os
import matplotlib.pylab as plt

#Util Library
import time
from tqdm.notebook import tqdm
from mpl_toolkits.axes_grid1 import ImageGrid  

Train_label=os.path.join(EMOTIPATH,"Train_labels.txt")
Train_video_pt=os.path.join(EMOTIPATH,"pt","Train")
Train_face_pt=os.path.join(EMOTIFACEPATH,"pt_stacked","Train")
Audio_Train=os.path.join(EMOTIAUDIOPATH,"training_audio_compare.csv")

Val_labels=os.path.join(EMOTIPATH,"Val_labels.txt")
Val_video_pt=os.path.join(EMOTIPATH,"pt","Valid")
Val_face_pt=os.path.join(EMOTIFACEPATH,"pt_stacked","Valid")
Audio_Valid=os.path.join(EMOTIAUDIOPATH,"validation_audio_compare.csv")


train_table = pd.read_csv(Train_label,delimiter=' ')
val_table = pd.read_csv(Val_labels,delimiter=' ')
print(train_table['Label'].value_counts())
print(val_table['Label'].value_counts())



device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
torch.set_default_tensor_type(torch.cuda.FloatTensor)



frame_num=10

train_data_pt=dataload.Video_Frame_Data(Train_label,base_path_v=Train_video_pt,face_path=Train_face_pt,frame_num=frame_num,direct=True,audio_csv=Audio_Train)
valid_data_pt=dataload.Video_Frame_Data(Val_labels,base_path_v=Val_video_pt,face_path=Val_face_pt,frame_num=frame_num,direct=True,audio_csv=Audio_Valid)





def load_pretrained_model(pre_train):
    face_model=torch.load("pre_trained_model/" +"pre_trained_resnet18_face.h")
    
   # face_model=torch.load("pre_trained_model/" +"pre_trained_resnet18_facev2.h")
   # audio_model=video_model_attention.AudioRecognition(softmax=pre_train)
   # audio_model.load_state_dict(torch.load("pre_trained_model/pre_embedded_audio.pth"),strict=False)
    image_model=video_model_attention.Video_modeller(frame_num,face_model=face_model,pre_train=pre_train)
   # image_model.load_state_dict(torch.load("saved_model_img/img_global_5.pth"),strict=False)
    return(image_model)#,audio_model)



def show_img(dataset,index,frame):
    x=dataset[index][0][frame].cpu().numpy()
    plt.figure(1,(15,15))
    plt.axis('off')
    image = (x*0.5+0.5).transpose((1, 2, 0)).squeeze()
    plt.imshow(image)
    
    fig = plt.figure(2,(15,15))
   # plt.axis('off')
    grid = ImageGrid(fig, 111,
                     nrows_ncols=(1,5),
                     axes_pad=0.1,
                     )
    for i in range(5):
        face=dataset[index][1][frame].cpu().numpy()
        image = (face[i,:]*0.5+0.5).transpose((1, 2, 0)).squeeze()
        grid[i].imshow(image,cmap='gray',interpolation='none')
        
img_model=load_pretrained_model(True)
#audio_model=video_model_attention.AudioRecognition(softmax=True)


3    932
2    923
1    806
Name: Label, dtype: int64
1    299
2    281
3    186
Name: Label, dtype: int64


In [2]:


weights=[932/932,932/923,932/806]
class_weights = torch.FloatTensor(weights).to(device)

train_dataloader = DataLoader(train_data_pt, batch_size=32
                       , num_workers=0,shuffle=True)
valid_dataloader = DataLoader(valid_data_pt, batch_size=32
                   , num_workers=0)
#model=video_model.video_transformer(img_model,audio_model)
model=img_model
model=model.to(device)

num_epochs=50
criterion = nn.CrossEntropyLoss(weight=class_weights)  

for name, child in model.named_children():
    if not name in ['face_model','frame_model' ]:
        print(name + ' is unfrozen')
        for param in child.parameters():
            param.requires_grad = True
    else:
        print(name + ' is frozen')
        for param in child.parameters():
               param.requires_grad = False

frame_model is frozen
face_model is frozen
en1 is unfrozen
en2 is unfrozen
fc1 is unfrozen
fc2 is unfrozen
fc3 is unfrozen
dropout is unfrozen


In [3]:
model(train_data_pt[6][0].unsqueeze(0).float().to(device),None)

tensor([[0.1466, 0.3838, 0.4696]], grad_fn=<SoftmaxBackward>)

In [4]:
model(None,train_data_pt[0][1].unsqueeze(0).float().to(device))

tensor([[0.1741, 0.3477, 0.4782]], grad_fn=<SoftmaxBackward>)

In [5]:

optimizer = torch.optim.Adam(filter(lambda p: p.requires_grad, model.parameters()), lr=0.0005, betas=(0.5, 0.999))


model_name="global_attetnion"

print(model_name)

methods.frame_train("global_image_train_v2",num_epochs,model_name,model,train_dataloader,valid_dataloader,optimizer,criterion,device)


global_attetnion
Epoch:  1 

Validation 

Validation Loss:  1.122681496044
Validation Accuracy:  0.3968668407310705
Confusion Matrix: 
 [[  0 292   7]
 [  0 267  14]
 [  0 149  37]]


Batch:  40 / 84
Batch Recognition loss:  1.067987084388733
Batch:  80 / 84
Batch Recognition loss:  1.0076818466186523

Average_Loss:  0.978890468676885
Average_Accuracy:  0.5377677564825254
Confusion Matrix: 
 [[304 261 241]
 [203 480 240]
 [112 173 647]]
Epoch:  2 

Validation 

Validation Loss:  1.0212591538826625
Validation Accuracy:  0.4960835509138381
Confusion Matrix: 
 [[164  39  96]
 [140  97  44]
 [ 23  44 119]]


Batch:  40 / 84
Batch Recognition loss:  0.8937707543373108
Batch:  80 / 84
Batch Recognition loss:  1.0243604183197021

Average_Loss:  0.9255925913651785
Average_Accuracy:  0.608793686583991
Confusion Matrix: 
 [[391 228 187]
 [171 552 200]
 [ 88 167 677]]
Epoch:  3 

Validation 

Validation Loss:  1.0105154166618984
Validation Accuracy:  0.5052219321148825
Confusion Matrix: 
 [[174  55  70]
 [114 138  29]
 [ 47  64  75]]


Batch:  40 / 84
Batch Recognition loss:  0.8208170533180237
Batch:  80 / 84
Batch Recognition loss:  0.9051774740219116

Average_Loss:  0.8968622407742909
Average_Accuracy:  0.6366027809094326
Confusion Matrix: 
 [[417 218 171]
 [177 584 162]
 [ 87 152 693]]
Epoch:  4 

Validation 

Validation Loss:  0.9821802228689194
Validation Accuracy:  0.5339425587467362
Confusion Matrix: 
 [[126  70 103]
 [ 63 138  80]
 [ 20  21 145]]


Batch:  40 / 84
Batch Recognition loss:  0.8362656831741333
Batch:  80 / 84
Batch Recognition loss:  0.9653229713439941

Average_Loss:  0.876470535283997
Average_Accuracy:  0.6557685080796692
Confusion Matrix: 
 [[459 184 163]
 [173 575 175]
 [ 98 123 711]]
Epoch:  5 

Validation 

Validation Loss:  1.001938745379448
Validation Accuracy:  0.5078328981723238
Confusion Matrix: 
 [[119  76 104]
 [ 87 134  60]
 [ 28  22 136]]


Batch:  40 / 84
Batch Recognition loss:  1.0016796588897705
Batch:  80 / 84
Batch Recognition loss:  0.8131349682807922

Average_Loss:  0.8697719737177804
Average_Accuracy:  0.6677940623825629
Confusion Matrix: 
 [[456 195 155]
 [165 584 174]
 [ 85 110 737]]
Epoch:  6 

Validation 

Validation Loss:  0.9879389926791191
Validation Accuracy:  0.5469973890339426
Confusion Matrix: 
 [[146 117  36]
 [ 78 189  14]
 [ 50  52  84]]


Batch:  40 / 84
Batch Recognition loss:  0.9247068762779236
Batch:  80 / 84
Batch Recognition loss:  0.9670823812484741

Average_Loss:  0.8634782043241319
Average_Accuracy:  0.6753100338218715
Confusion Matrix: 
 [[461 199 146]
 [143 612 168]
 [ 85 123 724]]
Epoch:  7 

Validation 

Validation Loss:  0.9952866559227308
Validation Accuracy:  0.5143603133159269
Confusion Matrix: 
 [[183  44  72]
 [135  91  55]
 [ 53  13 120]]


Batch:  40 / 84
Batch Recognition loss:  0.8637521862983704
Batch:  80 / 84
Batch Recognition loss:  0.8911202549934387

Average_Loss:  0.8546858032544454
Average_Accuracy:  0.6907177752724539
Confusion Matrix: 
 [[481 196 129]
 [145 626 152]
 [ 82 119 731]]
Epoch:  8 

Validation 

Validation Loss:  0.997890534500281
Validation Accuracy:  0.5300261096605744
Confusion Matrix: 
 [[207  44  48]
 [147  90  44]
 [ 70   7 109]]


Batch:  40 / 84
Batch Recognition loss:  0.73744797706604
Batch:  80 / 84
Batch Recognition loss:  0.7017444372177124

Average_Loss:  0.8410401599747794
Average_Accuracy:  0.6997369409996242
Confusion Matrix: 
 [[515 172 119]
 [155 613 155]
 [ 76 122 734]]
Epoch:  9 

Validation 

Validation Loss:  1.0017687504490216
Validation Accuracy:  0.5287206266318538
Confusion Matrix: 
 [[159  93  47]
 [100 152  29]
 [ 75  17  94]]


Batch:  40 / 84
Batch Recognition loss:  0.9425851702690125
Batch:  80 / 84
Batch Recognition loss:  0.8114534616470337

Average_Loss:  0.8378681320519674
Average_Accuracy:  0.703870725291244
Confusion Matrix: 
 [[521 164 121]
 [151 617 155]
 [ 93 104 735]]
Epoch:  10 

Validation 

Validation Loss:  1.037238302330176
Validation Accuracy:  0.47389033942558745
Confusion Matrix: 
 [[ 71 104 124]
 [ 45 154  82]
 [ 22  26 138]]


Batch:  40 / 84
Batch Recognition loss:  0.8506784439086914
Batch:  80 / 84
Batch Recognition loss:  0.8821864724159241

Average_Loss:  0.8266832644031161
Average_Accuracy:  0.7177752724539647
Confusion Matrix: 
 [[502 183 121]
 [123 649 151]
 [ 65 108 759]]
Epoch:  11 

Validation 

Validation Loss:  1.058776470522086
Validation Accuracy:  0.4451697127937337
Confusion Matrix: 
 [[ 41 145 113]
 [ 47 182  52]
 [ 40  28 118]]


Batch:  40 / 84
Batch Recognition loss:  0.7425724267959595
Batch:  80 / 84
Batch Recognition loss:  0.7960951924324036

Average_Loss:  0.8238337359258107
Average_Accuracy:  0.7113866967305524
Confusion Matrix: 
 [[496 197 113]
 [148 641 134]
 [ 57 119 756]]
Epoch:  12 

Validation 

Validation Loss:  1.066548151274522
Validation Accuracy:  0.4516971279373368
Confusion Matrix: 
 [[108  47 144]
 [ 99  93  89]
 [ 37   4 145]]


Batch:  40 / 84
Batch Recognition loss:  0.9009593725204468
Batch:  80 / 84
Batch Recognition loss:  0.6980078816413879

Average_Loss:  0.8141272791794368
Average_Accuracy:  0.7234122510334461
Confusion Matrix: 
 [[522 178 106]
 [140 654 129]
 [ 66 117 749]]
Epoch:  13 

Validation 

Validation Loss:  0.9636167958378792
Validation Accuracy:  0.5704960835509139
Confusion Matrix: 
 [[139 111  49]
 [ 77 170  34]
 [ 31  27 128]]


Batch:  40 / 84
Batch Recognition loss:  0.797113299369812
Batch:  80 / 84
Batch Recognition loss:  0.8831629753112793

Average_Loss:  0.8044029303959438
Average_Accuracy:  0.7380683953400977
Confusion Matrix: 
 [[539 144 123]
 [132 653 138]
 [ 62  98 772]]
Epoch:  14 

Validation 

Validation Loss:  1.0173350845774014
Validation Accuracy:  0.5078328981723238
Confusion Matrix: 
 [[144  88  67]
 [ 91 154  36]
 [ 72  23  91]]


Batch:  40 / 84
Batch Recognition loss:  0.70585036277771
Batch:  80 / 84
Batch Recognition loss:  0.778419017791748

Average_Loss:  0.7935718397299448
Average_Accuracy:  0.7474633596392334
Confusion Matrix: 
 [[540 165 101]
 [130 661 132]
 [ 52  92 788]]
Epoch:  15 

Validation 

Validation Loss:  1.0626370410124462
Validation Accuracy:  0.4595300261096606
Confusion Matrix: 
 [[113  80 106]
 [113 114  54]
 [ 53   8 125]]


Batch:  40 / 84
Batch Recognition loss:  0.758033812046051
Batch:  80 / 84
Batch Recognition loss:  0.8746766448020935

Average_Loss:  0.7904762568927947
Average_Accuracy:  0.7564825253664036
Confusion Matrix: 
 [[543 160 103]
 [110 676 137]
 [ 53  85 794]]
Epoch:  16 

Validation 

Validation Loss:  1.0584629277388256
Validation Accuracy:  0.4516971279373368
Confusion Matrix: 
 [[ 88  63 148]
 [ 62 110 109]
 [ 27  11 148]]


Batch:  40 / 84
Batch Recognition loss:  0.7736694812774658
Batch:  80 / 84
Batch Recognition loss:  0.9468644261360168

Average_Loss:  0.7950658635014579
Average_Accuracy:  0.7485907553551296
Confusion Matrix: 
 [[549 153 104]
 [120 682 121]
 [ 62 109 761]]
Epoch:  17 

Validation 

Validation Loss:  1.0705550263325374
Validation Accuracy:  0.4386422976501306
Confusion Matrix: 
 [[ 67  61 171]
 [ 39 107 135]
 [ 12  12 162]]


Batch:  40 / 84
Batch Recognition loss:  0.7546444535255432


ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.



Traceback (most recent call last):
  File "/opt/conda/envs/torch/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3319, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-5-ecaa81700cf1>", line 8, in <module>
    methods.frame_train("global_image_train_v2",num_epochs,model_name,model,train_dataloader,valid_dataloader,optimizer,criterion,device)
  File "/opt/notebooks/Github/EmotiW2020/train/methods.py", line 144, in frame_train
    for i_batch, (frame_batch,_,_,label) in tqdm(enumerate(train_dataloader)):
  File "/opt/conda/envs/torch/lib/python3.7/site-packages/tqdm/notebook.py", line 215, in __iter__
    for obj in super(tqdm_notebook, self).__iter__(*args, **kwargs):
  File "/opt/conda/envs/torch/lib/python3.7/site-packages/tqdm/std.py", line 1097, in __iter__
    for obj in iterable:
  File "/opt/conda/envs/torch/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 346, in __next__
    data = self._dataset_fetche

KeyboardInterrupt: 