In [1]:
#Slef-made Function
from Dataload import dataload
#from module import transformer,video_model

from module import video_model_attention
from constant import EMOTIPATH,EMOTIFACEPATH,EMOTIAUDIOPATH
from train import methods


#Torch Library

import torch
import torch.nn as nn
from torchsummary import summary
from torch.utils.data import Dataset, DataLoader
from torchvision import  utils

#Sub tools
import pandas as pd

import os
import matplotlib.pylab as plt

#Util Library
import time
from tqdm.notebook import tqdm
from mpl_toolkits.axes_grid1 import ImageGrid  

Train_label=os.path.join(EMOTIPATH,"Train_labels.txt")
Train_video_pt=os.path.join(EMOTIPATH,"pt","Train")
Train_face_pt=os.path.join(EMOTIFACEPATH,"pt_stacked","Train")
Audio_Train=os.path.join(EMOTIAUDIOPATH,"training_audio_compare.csv")

Val_labels=os.path.join(EMOTIPATH,"Val_labels.txt")
Val_video_pt=os.path.join(EMOTIPATH,"pt","Valid")
Val_face_pt=os.path.join(EMOTIFACEPATH,"pt_stacked","Valid")
Audio_Valid=os.path.join(EMOTIAUDIOPATH,"validation_audio_compare.csv")


train_table = pd.read_csv(Train_label,delimiter=' ')
val_table = pd.read_csv(Val_labels,delimiter=' ')
print(train_table['Label'].value_counts())
print(val_table['Label'].value_counts())



device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
torch.set_default_tensor_type(torch.cuda.FloatTensor)



frame_num=10

train_data_pt=dataload.Video_Frame_Data(Train_label,base_path_v=Train_video_pt,face_path=Train_face_pt,frame_num=frame_num,direct=True,audio_csv=Audio_Train)
valid_data_pt=dataload.Video_Frame_Data(Val_labels,base_path_v=Val_video_pt,face_path=Val_face_pt,frame_num=frame_num,direct=True,audio_csv=Audio_Valid)





def load_pretrained_model(pre_train):
    
    face_model=torch.load("pre_trained_model/" +"pre_trained_resnet18_facev2.h")
   # audio_model=video_model_attention.AudioRecognition(softmax=pre_train)
   # audio_model.load_state_dict(torch.load("pre_trained_model/pre_embedded_audio.pth"),strict=False)
    image_model=video_model_attention.Video_modeller(frame_num,face_model=face_model,pre_train=pre_train)
   # image_model.load_state_dict(torch.load("saved_model_img/img_global_5.pth"),strict=False)
    return(image_model)#,audio_model)



def show_img(dataset,index,frame):
    x=dataset[index][0][frame].cpu().numpy()
    plt.figure(1,(15,15))
    plt.axis('off')
    image = (x*0.5+0.5).transpose((1, 2, 0)).squeeze()
    plt.imshow(image)
    
    fig = plt.figure(2,(15,15))
   # plt.axis('off')
    grid = ImageGrid(fig, 111,
                     nrows_ncols=(1,5),
                     axes_pad=0.1,
                     )
    for i in range(5):
        face=dataset[index][1][frame].cpu().numpy()
        image = (face[i,:]*0.5+0.5).transpose((1, 2, 0)).squeeze()
        grid[i].imshow(image,cmap='gray',interpolation='none')
        
img_model=load_pretrained_model(True)
#audio_model=video_model_attention.AudioRecognition(softmax=True)


3    932
2    923
1    806
Name: Label, dtype: int64
1    299
2    281
3    186
Name: Label, dtype: int64


In [2]:


weights=[932/932,932/923,932/806]
class_weights = torch.FloatTensor(weights).to(device)

train_dataloader = DataLoader(train_data_pt, batch_size=32
                       , num_workers=0,shuffle=True)
valid_dataloader = DataLoader(valid_data_pt, batch_size=32
                   , num_workers=0)
#model=video_model.video_transformer(img_model,audio_model)
model=img_model
model=model.to(device)

num_epochs=50
criterion = nn.CrossEntropyLoss(weight=class_weights)  

for name, child in model.named_children():
    if not name in ['face_model','frame_model' ]:
        print(name + ' is unfrozen')
        for param in child.parameters():
            param.requires_grad = True
    else:
        print(name + ' is frozen')
        for param in child.parameters():
               param.requires_grad = False

frame_model is frozen
face_model is frozen
en1 is unfrozen
en2 is unfrozen
fc1 is unfrozen
fc2 is unfrozen
fc3 is unfrozen
dropout is unfrozen


In [3]:
model(train_data_pt[6][0].unsqueeze(0).float().to(device),None)

tensor([[0.1466, 0.3838, 0.4696]], grad_fn=<SoftmaxBackward>)

In [4]:
model(None,train_data_pt[0][1].unsqueeze(0).float().to(device))

tensor([[0.9290, 0.0690, 0.0020]], grad_fn=<SoftmaxBackward>)

In [5]:

optimizer = torch.optim.Adam(filter(lambda p: p.requires_grad, model.parameters()), lr=0.0005, betas=(0.5, 0.999))


model_name="global_attetnion"

print(model_name)

methods.frame_train("global_image_train_v2",num_epochs,model_name,model,train_dataloader,valid_dataloader,optimizer,criterion,device)


global_attetnion
Epoch:  1 

Validation 

Validation Loss:  1.122681496044
Validation Accuracy:  0.3968668407310705
Confusion Matrix: 
 [[  0 292   7]
 [  0 267  14]
 [  0 149  37]]


Batch:  40 / 84
Batch Recognition loss:  1.067987084388733
Batch:  80 / 84
Batch Recognition loss:  1.0076818466186523

Average_Loss:  0.978890468676885
Average_Accuracy:  0.5377677564825254
Confusion Matrix: 
 [[304 261 241]
 [203 480 240]
 [112 173 647]]
Epoch:  2 

Validation 

Validation Loss:  1.0212591538826625
Validation Accuracy:  0.4960835509138381
Confusion Matrix: 
 [[164  39  96]
 [140  97  44]
 [ 23  44 119]]


Batch:  40 / 84
Batch Recognition loss:  0.8937707543373108
Batch:  80 / 84
Batch Recognition loss:  1.0243604183197021

Average_Loss:  0.9255925913651785
Average_Accuracy:  0.608793686583991
Confusion Matrix: 
 [[391 228 187]
 [171 552 200]
 [ 88 167 677]]
Epoch:  3 

Validation 

Validation Loss:  1.0105154166618984
Validation Accuracy:  0.5052219321148825
Confusion Matrix: 
 [[174  55  70]
 [114 138  29]
 [ 47  64  75]]


Batch:  40 / 84
Batch Recognition loss:  0.8208170533180237
Batch:  80 / 84
Batch Recognition loss:  0.9051774740219116

Average_Loss:  0.8968622407742909
Average_Accuracy:  0.6366027809094326
Confusion Matrix: 
 [[417 218 171]
 [177 584 162]
 [ 87 152 693]]
Epoch:  4 

Validation 

Validation Loss:  0.9821802228689194
Validation Accuracy:  0.5339425587467362
Confusion Matrix: 
 [[126  70 103]
 [ 63 138  80]
 [ 20  21 145]]


Batch:  40 / 84
Batch Recognition loss:  0.8362656831741333
Batch:  80 / 84
Batch Recognition loss:  0.9653229713439941

Average_Loss:  0.876470535283997
Average_Accuracy:  0.6557685080796692
Confusion Matrix: 
 [[459 184 163]
 [173 575 175]
 [ 98 123 711]]
Epoch:  5 

Validation 

Validation Loss:  1.001938745379448
Validation Accuracy:  0.5078328981723238
Confusion Matrix: 
 [[119  76 104]
 [ 87 134  60]
 [ 28  22 136]]


Batch:  40 / 84
Batch Recognition loss:  1.0016796588897705
Batch:  80 / 84
Batch Recognition loss:  0.8131349682807922

Average_Loss:  0.8697719737177804
Average_Accuracy:  0.6677940623825629
Confusion Matrix: 
 [[456 195 155]
 [165 584 174]
 [ 85 110 737]]
Epoch:  6 

Validation 

Validation Loss:  0.9879389926791191
Validation Accuracy:  0.5469973890339426
Confusion Matrix: 
 [[146 117  36]
 [ 78 189  14]
 [ 50  52  84]]


Batch:  40 / 84
Batch Recognition loss:  0.9247068762779236
Batch:  80 / 84
Batch Recognition loss:  0.9670823812484741

Average_Loss:  0.8634782043241319
Average_Accuracy:  0.6753100338218715
Confusion Matrix: 
 [[461 199 146]
 [143 612 168]
 [ 85 123 724]]
Epoch:  7 

Validation 

Validation Loss:  0.9952866559227308
Validation Accuracy:  0.5143603133159269
Confusion Matrix: 
 [[183  44  72]
 [135  91  55]
 [ 53  13 120]]


Batch:  40 / 84
Batch Recognition loss:  0.8637521862983704
Batch:  80 / 84
Batch Recognition loss:  0.8911202549934387

Average_Loss:  0.8546858032544454
Average_Accuracy:  0.6907177752724539
Confusion Matrix: 
 [[481 196 129]
 [145 626 152]
 [ 82 119 731]]
Epoch:  8 

Validation 

Validation Loss:  0.997890534500281
Validation Accuracy:  0.5300261096605744
Confusion Matrix: 
 [[207  44  48]
 [147  90  44]
 [ 70   7 109]]


Batch:  40 / 84
Batch Recognition loss:  0.73744797706604
Batch:  80 / 84
Batch Recognition loss:  0.7017444372177124

Average_Loss:  0.8410401599747794
Average_Accuracy:  0.6997369409996242
Confusion Matrix: 
 [[515 172 119]
 [155 613 155]
 [ 76 122 734]]
Epoch:  9 

Validation 

Validation Loss:  1.0017687504490216
Validation Accuracy:  0.5287206266318538
Confusion Matrix: 
 [[159  93  47]
 [100 152  29]
 [ 75  17  94]]


Batch:  40 / 84
Batch Recognition loss:  0.9425851702690125
Batch:  80 / 84
Batch Recognition loss:  0.8114534616470337

Average_Loss:  0.8378681320519674
Average_Accuracy:  0.703870725291244
Confusion Matrix: 
 [[521 164 121]
 [151 617 155]
 [ 93 104 735]]
Epoch:  10 

Validation 

Validation Loss:  1.037238302330176
Validation Accuracy:  0.47389033942558745
Confusion Matrix: 
 [[ 71 104 124]
 [ 45 154  82]
 [ 22  26 138]]


Batch:  40 / 84
Batch Recognition loss:  0.8506784439086914
Batch:  80 / 84
Batch Recognition loss:  0.8821864724159241

Average_Loss:  0.8266832644031161
Average_Accuracy:  0.7177752724539647
Confusion Matrix: 
 [[502 183 121]
 [123 649 151]
 [ 65 108 759]]
Epoch:  11 

Validation 

Validation Loss:  1.058776470522086
Validation Accuracy:  0.4451697127937337
Confusion Matrix: 
 [[ 41 145 113]
 [ 47 182  52]
 [ 40  28 118]]


Batch:  40 / 84
Batch Recognition loss:  0.7425724267959595
Batch:  80 / 84
Batch Recognition loss:  0.7960951924324036

Average_Loss:  0.8238337359258107
Average_Accuracy:  0.7113866967305524
Confusion Matrix: 
 [[496 197 113]
 [148 641 134]
 [ 57 119 756]]
Epoch:  12 

Validation 

Validation Loss:  1.066548151274522
Validation Accuracy:  0.4516971279373368
Confusion Matrix: 
 [[108  47 144]
 [ 99  93  89]
 [ 37   4 145]]


Batch:  40 / 84
Batch Recognition loss:  0.9009593725204468
Batch:  80 / 84
Batch Recognition loss:  0.6980078816413879

Average_Loss:  0.8141272791794368
Average_Accuracy:  0.7234122510334461
Confusion Matrix: 
 [[522 178 106]
 [140 654 129]
 [ 66 117 749]]
Epoch:  13 

Validation 

Validation Loss:  0.9636167958378792
Validation Accuracy:  0.5704960835509139
Confusion Matrix: 
 [[139 111  49]
 [ 77 170  34]
 [ 31  27 128]]


Batch:  40 / 84
Batch Recognition loss:  0.797113299369812
Batch:  80 / 84
Batch Recognition loss:  0.8831629753112793

Average_Loss:  0.8044029303959438
Average_Accuracy:  0.7380683953400977
Confusion Matrix: 
 [[539 144 123]
 [132 653 138]
 [ 62  98 772]]
Epoch:  14 

Validation 

Validation Loss:  1.0173350845774014
Validation Accuracy:  0.5078328981723238
Confusion Matrix: 
 [[144  88  67]
 [ 91 154  36]
 [ 72  23  91]]


Batch:  40 / 84
Batch Recognition loss:  0.70585036277771
Batch:  80 / 84
Batch Recognition loss:  0.778419017791748

Average_Loss:  0.7935718397299448
Average_Accuracy:  0.7474633596392334
Confusion Matrix: 
 [[540 165 101]
 [130 661 132]
 [ 52  92 788]]
Epoch:  15 

Validation 

Validation Loss:  1.0626370410124462
Validation Accuracy:  0.4595300261096606
Confusion Matrix: 
 [[113  80 106]
 [113 114  54]
 [ 53   8 125]]


Batch:  40 / 84
Batch Recognition loss:  0.758033812046051
Batch:  80 / 84
Batch Recognition loss:  0.8746766448020935

Average_Loss:  0.7904762568927947
Average_Accuracy:  0.7564825253664036
Confusion Matrix: 
 [[543 160 103]
 [110 676 137]
 [ 53  85 794]]
Epoch:  16 

Validation 

Validation Loss:  1.0584629277388256
Validation Accuracy:  0.4516971279373368
Confusion Matrix: 
 [[ 88  63 148]
 [ 62 110 109]
 [ 27  11 148]]


Batch:  40 / 84
Batch Recognition loss:  0.7736694812774658
Batch:  80 / 84
Batch Recognition loss:  0.9468644261360168

Average_Loss:  0.7950658635014579
Average_Accuracy:  0.7485907553551296
Confusion Matrix: 
 [[549 153 104]
 [120 682 121]
 [ 62 109 761]]
Epoch:  17 

Validation 

Validation Loss:  1.0705550263325374
Validation Accuracy:  0.4386422976501306
Confusion Matrix: 
 [[ 67  61 171]
 [ 39 107 135]
 [ 12  12 162]]


Batch:  40 / 84
Batch Recognition loss:  0.7546444535255432
Batch:  80 / 84
Batch Recognition loss:  0.9195698499679565

Average_Loss:  0.8081545531749725
Average_Accuracy:  0.736565201052236
Confusion Matrix: 
 [[515 167 124]
 [122 663 138]
 [ 51  99 782]]
Epoch:  18 

Validation 

Validation Loss:  1.0287384018301964
Validation Accuracy:  0.5
Confusion Matrix: 
 [[131  56 112]
 [ 84 123  74]
 [ 44  13 129]]


Batch:  40 / 84
Batch Recognition loss:  0.762041449546814
Batch:  80 / 84
Batch Recognition loss:  0.9293917417526245

Average_Loss:  0.7922396787575313
Average_Accuracy:  0.7515971439308531
Confusion Matrix: 
 [[558 131 117]
 [120 659 144]
 [ 61  88 783]]
Epoch:  19 

Validation 

Validation Loss:  1.0288551275928814
Validation Accuracy:  0.49477806788511747
Confusion Matrix: 
 [[106  89 104]
 [ 55 141  85]
 [ 35  19 132]]


Batch:  40 / 84
Batch Recognition loss:  0.8310390710830688
Batch:  80 / 84
Batch Recognition loss:  0.7911831736564636

Average_Loss:  0.7916889836390814
Average_Accuracy:  0.756858323938369
Confusion Matrix: 
 [[554 147 105]
 [117 670 136]
 [ 51  91 790]]
Epoch:  20 

Validation 

Validation Loss:  1.0611255690455437
Validation Accuracy:  0.46736292428198434
Confusion Matrix: 
 [[131  78  90]
 [ 95 120  66]
 [ 63  16 107]]


Batch:  40 / 84
Batch Recognition loss:  0.8926702737808228
Batch:  80 / 84
Batch Recognition loss:  0.8033366203308105

Average_Loss:  0.7875565602665856
Average_Accuracy:  0.7549793310785419
Confusion Matrix: 
 [[551 153 102]
 [118 665 140]
 [ 55  84 793]]
Epoch:  21 

Validation 

Validation Loss:  1.0852429841955502
Validation Accuracy:  0.42297650130548303
Confusion Matrix: 
 [[ 64  87 148]
 [ 52 119 110]
 [ 24  21 141]]


Batch:  40 / 84
Batch Recognition loss:  0.7483181357383728
Batch:  80 / 84
Batch Recognition loss:  0.7398842573165894

Average_Loss:  0.7754607519933155
Average_Accuracy:  0.7711386696730552
Confusion Matrix: 
 [[569 137 100]
 [115 680 128]
 [ 51  78 803]]
Epoch:  22 

Validation 

Validation Loss:  1.035183345278104
Validation Accuracy:  0.48825065274151436
Confusion Matrix: 
 [[103 125  71]
 [ 66 167  48]
 [ 34  48 104]]


Batch:  40 / 84
Batch Recognition loss:  0.747097909450531
Batch:  80 / 84
Batch Recognition loss:  0.7500240802764893

Average_Loss:  0.7770761861687615
Average_Accuracy:  0.764750093949643
Confusion Matrix: 
 [[557 154  95]
 [109 672 142]
 [ 47  79 806]]
Epoch:  23 

Validation 

Validation Loss:  1.0742604260643323
Validation Accuracy:  0.45039164490861616
Confusion Matrix: 
 [[104  58 137]
 [ 49 100 132]
 [ 32  13 141]]


Batch:  40 / 84
Batch Recognition loss:  0.7557105422019958
Batch:  80 / 84
Batch Recognition loss:  0.8103845119476318

Average_Loss:  0.7731569480328333
Average_Accuracy:  0.7726418639609169
Confusion Matrix: 
 [[586 128  92]
 [116 667 140]
 [ 47  82 803]]
Epoch:  24 

Validation 

Validation Loss:  1.1110618561506271
Validation Accuracy:  0.42036553524804177
Confusion Matrix: 
 [[ 98  28 173]
 [ 83  72 126]
 [ 30   4 152]]


Batch:  40 / 84
Batch Recognition loss:  0.69477778673172
Batch:  80 / 84
Batch Recognition loss:  0.6909003257751465

Average_Loss:  0.7762069169964109
Average_Accuracy:  0.7685080796692972
Confusion Matrix: 
 [[579 147  80]
 [104 676 143]
 [ 57  85 790]]
Epoch:  25 

Validation 

Validation Loss:  1.090078592300415
Validation Accuracy:  0.4281984334203655
Confusion Matrix: 
 [[ 86 102 111]
 [ 42 128 111]
 [ 43  29 114]]


Batch:  40 / 84
Batch Recognition loss:  0.6080363988876343
Batch:  80 / 84
Batch Recognition loss:  0.7105266451835632

Average_Loss:  0.7722867379585902
Average_Accuracy:  0.7715144682450207
Confusion Matrix: 
 [[573 143  90]
 [116 680 127]
 [ 49  83 800]]
Epoch:  26 

Validation 

Validation Loss:  1.0408327902356784
Validation Accuracy:  0.47780678851174935
Confusion Matrix: 
 [[123  84  92]
 [ 92 133  56]
 [ 54  22 110]]


Batch:  40 / 84
Batch Recognition loss:  0.772824764251709
Batch:  80 / 84
Batch Recognition loss:  0.839616596698761

Average_Loss:  0.762459954335576
Average_Accuracy:  0.787673806839534
Confusion Matrix: 
 [[585 132  89]
 [101 697 125]
 [ 37  81 814]]
Epoch:  27 

Validation 

Validation Loss:  1.0393400291601818
Validation Accuracy:  0.46866840731070497
Confusion Matrix: 
 [[ 82 100 117]
 [ 61 148  72]
 [ 34  23 129]]


Batch:  40 / 84
Batch Recognition loss:  0.7893446087837219
Batch:  80 / 84
Batch Recognition loss:  0.7379740476608276

Average_Loss:  0.7545410650117057
Average_Accuracy:  0.7936865839909808
Confusion Matrix: 
 [[586 143  77]
 [ 99 704 120]
 [ 32  78 822]]
Epoch:  28 

Validation 

Validation Loss:  1.089212216436863
Validation Accuracy:  0.4360313315926893
Confusion Matrix: 
 [[104  80 115]
 [ 58 121 102]
 [ 54  23 109]]


Batch:  40 / 84
Batch Recognition loss:  0.765021562576294
Batch:  80 / 84
Batch Recognition loss:  0.6771499514579773

Average_Loss:  0.7627193012407848
Average_Accuracy:  0.7906801954152575
Confusion Matrix: 
 [[592 134  80]
 [106 692 125]
 [ 39  73 820]]
Epoch:  29 

Validation 

Validation Loss:  1.065958025554816
Validation Accuracy:  0.4595300261096606
Confusion Matrix: 
 [[ 64 114 121]
 [ 42 162  77]
 [ 25  35 126]]


Batch:  40 / 84
Batch Recognition loss:  0.7863268852233887
Batch:  80 / 84
Batch Recognition loss:  0.7562845945358276

Average_Loss:  0.7589113393000194
Average_Accuracy:  0.7914317925591883
Confusion Matrix: 
 [[593 136  77]
 [106 691 126]
 [ 41  69 822]]
Epoch:  30 

Validation 

Validation Loss:  1.0588952451944351
Validation Accuracy:  0.4608355091383812
Confusion Matrix: 
 [[ 89  92 118]
 [ 37 135 109]
 [ 39  18 129]]


Batch:  40 / 84
Batch Recognition loss:  0.6716517210006714
Batch:  80 / 84
Batch Recognition loss:  0.8133718967437744

Average_Loss:  0.7557517389456431
Average_Accuracy:  0.7940623825629463
Confusion Matrix: 
 [[584 133  89]
 [ 87 714 122]
 [ 41  76 815]]
Epoch:  31 

Validation 

Validation Loss:  1.0532334819436073
Validation Accuracy:  0.46866840731070497
Confusion Matrix: 
 [[147  27 125]
 [115  79  87]
 [ 43  10 133]]


Batch:  40 / 84
Batch Recognition loss:  0.7512689828872681
Batch:  80 / 84
Batch Recognition loss:  0.7693846225738525

Average_Loss:  0.7545173870665687
Average_Accuracy:  0.7899285982713266
Confusion Matrix: 
 [[584 138  84]
 [ 98 696 129]
 [ 38  72 822]]
Epoch:  32 

Validation 

Validation Loss:  1.0690325399239857
Validation Accuracy:  0.4595300261096606
Confusion Matrix: 
 [[161  19 119]
 [119  71  91]
 [ 56  10 120]]


Batch:  40 / 84
Batch Recognition loss:  0.7003239393234253
Batch:  80 / 84
Batch Recognition loss:  0.6709669828414917

Average_Loss:  0.7577942758798599
Average_Accuracy:  0.7865464111236378
Confusion Matrix: 
 [[588 130  88]
 [112 699 112]
 [ 50  76 806]]
Epoch:  33 

Validation 

Validation Loss:  1.0782332867383957
Validation Accuracy:  0.4347258485639687
Confusion Matrix: 
 [[ 85 112 102]
 [ 70 152  59]
 [ 62  28  96]]


Batch:  40 / 84
Batch Recognition loss:  0.7790758013725281
Batch:  80 / 84
Batch Recognition loss:  0.8344433307647705

Average_Loss:  0.7412414905570802
Average_Accuracy:  0.8072153325817362
Confusion Matrix: 
 [[607 121  78]
 [ 92 717 114]
 [ 38  70 824]]
Epoch:  34 

Validation 

Validation Loss:  1.108785331249237
Validation Accuracy:  0.4151436031331593
Confusion Matrix: 
 [[ 91  50 158]
 [ 72  94 115]
 [ 40  13 133]]


Batch:  40 / 84
Batch Recognition loss:  0.862923264503479
Batch:  80 / 84
Batch Recognition loss:  0.7549375891685486

Average_Loss:  0.751252545487313
Average_Accuracy:  0.7944381811349117
Confusion Matrix: 
 [[584 124  98]
 [ 94 712 117]
 [ 42  72 818]]
Epoch:  35 

Validation 

Validation Loss:  1.1044451196988423
Validation Accuracy:  0.42036553524804177
Confusion Matrix: 
 [[120  74 105]
 [124  76  81]
 [ 44  16 126]]


Batch:  40 / 84
Batch Recognition loss:  0.7279576063156128
Batch:  80 / 84
Batch Recognition loss:  0.9155505895614624

Average_Loss:  0.762708258770761
Average_Accuracy:  0.787673806839534
Confusion Matrix: 
 [[598 127  81]
 [ 99 705 119]
 [ 49  90 793]]
Epoch:  36 

Validation 

Validation Loss:  1.0841882924238841
Validation Accuracy:  0.4347258485639687
Confusion Matrix: 
 [[ 60  89 150]
 [ 53 126 102]
 [ 23  16 147]]


Batch:  40 / 84
Batch Recognition loss:  0.7252464294433594
Batch:  80 / 84
Batch Recognition loss:  0.9327033162117004

Average_Loss:  0.7520926147699356
Average_Accuracy:  0.7951897782788425
Confusion Matrix: 
 [[577 140  89]
 [ 98 707 118]
 [ 32  68 832]]
Epoch:  37 

Validation 

Validation Loss:  1.0239996785918872
Validation Accuracy:  0.5
Confusion Matrix: 
 [[156  47  96]
 [105 125  51]
 [ 55  29 102]]


Batch:  40 / 84
Batch Recognition loss:  0.7227847576141357
Batch:  80 / 84
Batch Recognition loss:  0.7545055150985718

Average_Loss:  0.7611850343999409
Average_Accuracy:  0.7869222096956031
Confusion Matrix: 
 [[599 120  87]
 [120 696 107]
 [ 46  87 799]]
Epoch:  38 

Validation 



KeyboardInterrupt: 