In [3]:
#Slef-made Function
from Dataload import dataload
from module import transformer,video_model
from constant import EMOTIPATH,EMOTIFACEPATH,EMOTIAUDIOPATH
from train import methods


#Torch Library

import torch
import torch.nn as nn
from torchsummary import summary
from torch.utils.data import Dataset, DataLoader
from torchvision import  utils

#Sub tools
import pandas as pd

import os
import matplotlib.pylab as plt

#Util Library
import time
from tqdm.notebook import tqdm
from mpl_toolkits.axes_grid1 import ImageGrid  

Train_label=os.path.join(EMOTIPATH,"Train_labels.txt")
Train_video_pt=os.path.join(EMOTIPATH,"pt","Train")
Train_face_pt=os.path.join(EMOTIFACEPATH,"pt_stacked","Train")
Audio_Train=os.path.join(EMOTIAUDIOPATH,"Train_audio.csv")

Val_labels=os.path.join(EMOTIPATH,"Val_labels.txt")
Val_video_pt=os.path.join(EMOTIPATH,"pt","Valid")
Val_face_pt=os.path.join(EMOTIFACEPATH,"pt_stacked","Valid")
Audio_Valid=os.path.join(EMOTIAUDIOPATH,"Val_audio.csv")


train_table = pd.read_csv(Train_label,delimiter=' ')
val_table = pd.read_csv(Val_labels,delimiter=' ')
print(train_table['Label'].value_counts())
print(val_table['Label'].value_counts())



device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
torch.set_default_tensor_type(torch.cuda.FloatTensor)



frame_num=10

train_data_pt=dataload.Video_Frame_Data(Train_label,base_path_v=Train_video_pt,face_path=Train_face_pt,frame_num=frame_num,direct=True,audio_csv=Audio_Train)
valid_data_pt=dataload.Video_Frame_Data(Val_labels,base_path_v=Val_video_pt,face_path=Val_face_pt,frame_num=frame_num,direct=True,audio_csv=Audio_Valid)





def load_pretrained_model(pre_train):
    
    face_model=torch.load("pre_trained_model/" +"pre_trained_resnet18_face.h")
    audio_model=video_model.AudioRecognition(softmax=pre_train)
    audio_model.load_state_dict(torch.load("pre_trained_model/pre_embedded_audio.pth"),strict=False)
    image_model=video_model.Video_modeller(frame_num,face_model=face_model,pre_train=pre_train)
    image_model.load_state_dict(torch.load("pre_trained_model/img_global_5.pth"),strict=False)
    return(image_model,audio_model)



def show_img(dataset,index,frame):
    x=dataset[index][0][frame].cpu().numpy()
    plt.figure(1,(15,15))
    plt.axis('off')
    image = (x*0.5+0.5).transpose((1, 2, 0)).squeeze()
    plt.imshow(image)
    
    fig = plt.figure(2,(15,15))
   # plt.axis('off')
    grid = ImageGrid(fig, 111,
                     nrows_ncols=(1,5),
                     axes_pad=0.1,
                     )
    for i in range(5):
        face=dataset[index][1][frame].cpu().numpy()
        image = (face[i,:]*0.5+0.5).transpose((1, 2, 0)).squeeze()
        grid[i].imshow(image,cmap='gray',interpolation='none')
        
img_model,audio_model=load_pretrained_model(False)



3    932
2    923
1    806
Name: Label, dtype: int64
1    299
2    281
3    186
Name: Label, dtype: int64


In [5]:
face_model=torch.load("pre_trained_model/" +"pre_trained_resnet18_face.h")

In [6]:
face_model

ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace=True)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Sequential(
    (0): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (1): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
  

In [ ]:


weights=[932/932,2,932/806]
class_weights = torch.FloatTensor(weights).to(device)

train_dataloader = DataLoader(train_data_pt, batch_size=32
                       , num_workers=0,shuffle=True)
valid_dataloader = DataLoader(valid_data_pt, batch_size=32
                   , num_workers=0)
model=video_model.video_transformer(img_model,audio_model)
model=model.to(device)

num_epochs=50
criterion = nn.CrossEntropyLoss(weight=class_weights)

for name, child in model.named_children():
    if not name in ['face_model','frame_model' ]:
        print(name + ' is unfrozen')
        for param in child.parameters():
            param.requires_grad = True
    else:
        print(name + ' is frozen')
        for param in child.parameters():
               param.requires_grad = False

In [3]:

optimizer = torch.optim.Adam(filter(lambda p: p.requires_grad, model.parameters()), lr=0.0005, betas=(0.5, 0.999))


model_name="v7"

print(model_name)

methods.full_train("v7_model",num_epochs,model_name,model,train_dataloader,valid_dataloader,optimizer,criterion,device)


v7
Epoch:  1 

Validation 

Validation Loss:  1.0793790618578594
Validation Accuracy:  0.3838120104438642
Confusion Matrix: 
 [[140  47 112]
 [187  33  61]
 [ 60   5 121]]
Train 



Batch:  40 / 84
Batch Recognition loss:  0.9089927673339844
Batch:  80 / 84
Batch Recognition loss:  0.9783446192741394

Average_Loss:  0.8549933163892656
Average_Accuracy:  0.6816986095452837
Confusion Matrix: 
 [[423 267 116]
 [ 91 714 118]
 [ 70 185 677]]
Epoch:  2 

Validation 

Validation Loss:  1.0159535308678944
Validation Accuracy:  0.5378590078328982
Confusion Matrix: 
 [[213  51  35]
 [138 123  20]
 [ 59  51  76]]
Train 



Batch:  40 / 84
Batch Recognition loss:  0.8722290396690369
Batch:  80 / 84
Batch Recognition loss:  0.9121275544166565

Average_Loss:  0.8329844155481884
Average_Accuracy:  0.6952273581360391
Confusion Matrix: 
 [[446 252 108]
 [ 86 726 111]
 [ 78 176 678]]
Epoch:  3 

Validation 

Validation Loss:  1.0291012525558472
Validation Accuracy:  0.5143603133159269
Confusion Matrix: 
 [[210  66  23]
 [124 132  25]
 [ 57  77  52]]
Train 



Batch:  40 / 84
Batch Recognition loss:  0.795126736164093
Batch:  80 / 84
Batch Recognition loss:  0.9640493392944336

Average_Loss:  0.8147768427928289
Average_Accuracy:  0.7095077038707253
Confusion Matrix: 
 [[465 235 106]
 [ 86 753  84]
 [ 79 183 670]]
Epoch:  4 

Validation 

Validation Loss:  0.9975238665938377
Validation Accuracy:  0.49738903394255873
Confusion Matrix: 
 [[ 77 155  67]
 [ 40 207  34]
 [ 13  76  97]]
Train 



Batch:  40 / 84
Batch Recognition loss:  0.7508949041366577
Batch:  80 / 84
Batch Recognition loss:  0.8474494814872742

Average_Loss:  0.8087333731708073
Average_Accuracy:  0.7158962795941376
Confusion Matrix: 
 [[467 245  94]
 [ 94 741  88]
 [ 64 171 697]]
Epoch:  5 

Validation 

Validation Loss:  1.0026092330614726
Validation Accuracy:  0.4960835509138381
Confusion Matrix: 
 [[107 155  37]
 [ 53 205  23]
 [ 36  82  68]]
Train 



Batch:  40 / 84
Batch Recognition loss:  0.8556380867958069
Batch:  80 / 84
Batch Recognition loss:  0.805025041103363

Average_Loss:  0.8080718588261377
Average_Accuracy:  0.7211574596016536
Confusion Matrix: 
 [[485 229  92]
 [ 93 738  92]
 [ 72 164 696]]
Epoch:  6 

Validation 

Validation Loss:  0.999812347193559
Validation Accuracy:  0.5156657963446475
Confusion Matrix: 
 [[130 140  29]
 [ 69 185  27]
 [ 42  64  80]]
Train 



Batch:  40 / 84
Batch Recognition loss:  0.9034478068351746
Batch:  80 / 84
Batch Recognition loss:  0.8347861766815186

Average_Loss:  0.8130562631856828
Average_Accuracy:  0.7158962795941376
Confusion Matrix: 
 [[480 230  96]
 [ 83 745  95]
 [ 75 177 680]]
Epoch:  7 

Validation 

Validation Loss:  1.0147909397880237
Validation Accuracy:  0.5078328981723238
Confusion Matrix: 
 [[172 116  11]
 [ 89 177  15]
 [ 66  80  40]]
Train 



Batch:  40 / 84
Batch Recognition loss:  0.8203050494194031
Batch:  80 / 84
Batch Recognition loss:  0.7067427635192871

Average_Loss:  0.8000862981591906
Average_Accuracy:  0.7298008267568583
Confusion Matrix: 
 [[480 231  95]
 [ 82 762  79]
 [ 55 177 700]]
Epoch:  8 

Validation 

Validation Loss:  1.0235469862818718
Validation Accuracy:  0.5013054830287206
Confusion Matrix: 
 [[105  96  98]
 [ 50 158  73]
 [ 26  39 121]]
Train 



Batch:  40 / 84
Batch Recognition loss:  0.7950657606124878
Batch:  80 / 84
Batch Recognition loss:  0.6495224237442017

Average_Loss:  0.7910437122696922
Average_Accuracy:  0.7346862081924088
Confusion Matrix: 
 [[491 232  83]
 [ 82 762  79]
 [ 58 172 702]]
Epoch:  9 

Validation 

Validation Loss:  0.9831461956103643
Validation Accuracy:  0.5274151436031331
Confusion Matrix: 
 [[123 143  33]
 [ 44 202  35]
 [ 29  78  79]]
Train 



Batch:  40 / 84
Batch Recognition loss:  0.7595939040184021
Batch:  80 / 84
Batch Recognition loss:  0.804416298866272

Average_Loss:  0.7899383647101266
Average_Accuracy:  0.7350620067643743
Confusion Matrix: 
 [[492 220  94]
 [ 76 770  77]
 [ 70 168 694]]
Epoch:  10 

Validation 

Validation Loss:  1.0305903082092602
Validation Accuracy:  0.5182767624020888
Confusion Matrix: 
 [[150  66  83]
 [ 94 135  52]
 [ 46  28 112]]
Train 



Batch:  40 / 84
Batch Recognition loss:  0.7274855375289917
Batch:  80 / 84
Batch Recognition loss:  0.8101998567581177

Average_Loss:  0.7910726609684172
Average_Accuracy:  0.7376925967681323
Confusion Matrix: 
 [[465 224 117]
 [ 57 760 106]
 [ 48 146 738]]
Epoch:  11 

Validation 

Validation Loss:  1.018624576429526
Validation Accuracy:  0.4830287206266319
Confusion Matrix: 
 [[ 71 151  77]
 [ 40 203  38]
 [ 29  61  96]]
Train 



Batch:  40 / 84
Batch Recognition loss:  0.8147474527359009
Batch:  80 / 84
Batch Recognition loss:  0.7237690091133118

Average_Loss:  0.7860328249988102
Average_Accuracy:  0.7406989853438557
Confusion Matrix: 
 [[497 229  80]
 [ 69 771  83]
 [ 57 172 703]]
Epoch:  12 

Validation 

Validation Loss:  1.0274033099412918
Validation Accuracy:  0.47127937336814624
Confusion Matrix: 
 [[ 31 161 107]
 [ 17 203  61]
 [  8  51 127]]
Train 



Batch:  40 / 84
Batch Recognition loss:  0.7241376638412476
Batch:  80 / 84
Batch Recognition loss:  0.7057684659957886

Average_Loss:  0.7821141460112163
Average_Accuracy:  0.7403231867718902
Confusion Matrix: 
 [[467 257  82]
 [ 57 786  80]
 [ 50 165 717]]
Epoch:  13 

Validation 

Validation Loss:  1.0138817504048347
Validation Accuracy:  0.5221932114882507
Confusion Matrix: 
 [[151  96  52]
 [ 79 160  42]
 [ 49  48  89]]
Train 



Batch:  40 / 84
Batch Recognition loss:  0.8147661089897156
Batch:  80 / 84
Batch Recognition loss:  0.8200141191482544

Average_Loss:  0.7767146428426107
Average_Accuracy:  0.7531003382187148
Confusion Matrix: 
 [[503 209  94]
 [ 62 787  74]
 [ 58 160 714]]
Epoch:  14 

Validation 

Validation Loss:  1.0364924197395642
Validation Accuracy:  0.4869451697127937
Confusion Matrix: 
 [[ 89 105 105]
 [ 51 160  70]
 [ 30  32 124]]
Train 



Batch:  40 / 84
Batch Recognition loss:  0.7575408220291138
Batch:  80 / 84
Batch Recognition loss:  0.7523791193962097

Average_Loss:  0.7820002195380983
Average_Accuracy:  0.7485907553551296
Confusion Matrix: 
 [[494 218  94]
 [ 74 768  81]
 [ 48 154 730]]
Epoch:  15 

Validation 

Validation Loss:  0.991801547507445
Validation Accuracy:  0.5261096605744126
Confusion Matrix: 
 [[124 135  40]
 [ 56 196  29]
 [ 30  73  83]]
Train 



Batch:  40 / 84
Batch Recognition loss:  0.7283154129981995
Batch:  80 / 84
Batch Recognition loss:  0.7883751392364502

Average_Loss:  0.764387479140645
Average_Accuracy:  0.7636226982337467
Confusion Matrix: 
 [[514 212  80]
 [ 57 795  71]
 [ 56 153 723]]
Epoch:  16 

Validation 

Validation Loss:  1.0269569605588913
Validation Accuracy:  0.4830287206266319
Confusion Matrix: 
 [[ 70 124 105]
 [ 35 189  57]
 [ 16  59 111]]
Train 



Batch:  40 / 84
Batch Recognition loss:  0.7251418828964233
Batch:  80 / 84
Batch Recognition loss:  0.7546694278717041

Average_Loss:  0.765158399229958
Average_Accuracy:  0.7636226982337467
Confusion Matrix: 
 [[505 210  91]
 [ 52 796  75]
 [ 48 153 731]]
Epoch:  17 

Validation 

Validation Loss:  1.019638458887736
Validation Accuracy:  0.5013054830287206
Confusion Matrix: 
 [[105 118  76]
 [ 55 190  36]
 [ 26  71  89]]
Train 



Batch:  40 / 84
Batch Recognition loss:  0.6245071887969971
Batch:  80 / 84
Batch Recognition loss:  0.7602946758270264

Average_Loss:  0.7707491382246926
Average_Accuracy:  0.756858323938369
Confusion Matrix: 
 [[519 205  82]
 [ 69 791  63]
 [ 61 167 704]]
Epoch:  18 

Validation 

Validation Loss:  1.042935239772002
Validation Accuracy:  0.45039164490861616
Confusion Matrix: 
 [[ 36 177  86]
 [ 13 211  57]
 [  8  80  98]]
Train 



Batch:  40 / 84
Batch Recognition loss:  0.7452152371406555
Batch:  80 / 84
Batch Recognition loss:  0.766700267791748

Average_Loss:  0.7738057339475268
Average_Accuracy:  0.7609921082299888
Confusion Matrix: 
 [[506 221  79]
 [ 61 793  69]
 [ 52 154 726]]
Epoch:  19 

Validation 

Validation Loss:  1.0230142027139664
Validation Accuracy:  0.48172323759791125
Confusion Matrix: 
 [[106 142  51]
 [ 52 192  37]
 [ 27  88  71]]
Train 



Batch:  40 / 84
Batch Recognition loss:  0.7451520562171936
Batch:  80 / 84
Batch Recognition loss:  0.8473984003067017

Average_Loss:  0.7630582331191926
Average_Accuracy:  0.7715144682450207
Confusion Matrix: 
 [[531 179  96]
 [ 62 791  70]
 [ 52 149 731]]
Epoch:  20 

Validation 

Validation Loss:  1.0374426891406376
Validation Accuracy:  0.4856396866840731
Confusion Matrix: 
 [[110 108  81]
 [ 65 168  48]
 [ 23  69  94]]
Train 



Batch:  40 / 84
Batch Recognition loss:  0.749840259552002
Batch:  80 / 84
Batch Recognition loss:  0.7627444267272949

Average_Loss:  0.7489958767380033
Average_Accuracy:  0.7846674182638106
Confusion Matrix: 
 [[546 186  74]
 [ 59 793  71]
 [ 40 143 749]]
Epoch:  21 

Validation 

Validation Loss:  1.0372386972109477
Validation Accuracy:  0.47780678851174935
Confusion Matrix: 
 [[ 83 120  96]
 [ 53 165  63]
 [ 25  43 118]]
Train 



Batch:  40 / 84
Batch Recognition loss:  0.685946524143219
Batch:  80 / 84
Batch Recognition loss:  0.7981491088867188

Average_Loss:  0.7511271493775504
Average_Accuracy:  0.7794062382562946
Confusion Matrix: 
 [[531 202  73]
 [ 46 811  66]
 [ 44 156 732]]
Epoch:  22 

Validation 

Validation Loss:  1.0789220879475276
Validation Accuracy:  0.4464751958224543
Confusion Matrix: 
 [[ 66  95 138]
 [ 43 140  98]
 [ 16  34 136]]
Train 



Batch:  40 / 84
Batch Recognition loss:  0.7422934174537659
Batch:  80 / 84
Batch Recognition loss:  0.7371442914009094

Average_Loss:  0.7560815321547645
Average_Accuracy:  0.7763998496805712
Confusion Matrix: 
 [[534 185  87]
 [ 50 799  74]
 [ 49 150 733]]
Epoch:  23 

Validation 

Validation Loss:  1.045349749426047
Validation Accuracy:  0.489556135770235
Confusion Matrix: 
 [[129  96  74]
 [ 71 152  58]
 [ 44  48  94]]
Train 



Batch:  40 / 84
Batch Recognition loss:  0.7728130221366882
Batch:  80 / 84
Batch Recognition loss:  0.8281937837600708

Average_Loss:  0.7458418600616001
Average_Accuracy:  0.7857948139797069
Confusion Matrix: 
 [[537 194  75]
 [ 53 808  62]
 [ 43 143 746]]
Epoch:  24 

Validation 

Validation Loss:  1.1038818433880806
Validation Accuracy:  0.4308093994778068
Confusion Matrix: 
 [[ 55  74 170]
 [ 42 128 111]
 [ 16  23 147]]
Train 



Batch:  40 / 84
Batch Recognition loss:  0.6329864859580994
Batch:  80 / 84
Batch Recognition loss:  0.672889769077301

Average_Loss:  0.7526279524678275
Average_Accuracy:  0.7790304396843292
Confusion Matrix: 
 [[520 203  83]
 [ 53 802  68]
 [ 39 142 751]]
Epoch:  25 

Validation 

Validation Loss:  1.0874717310070992
Validation Accuracy:  0.4308093994778068
Confusion Matrix: 
 [[ 39 107 153]
 [ 25 156 100]
 [  9  42 135]]
Train 



Batch:  40 / 84
Batch Recognition loss:  0.7799332737922668
Batch:  80 / 84
Batch Recognition loss:  0.7473893165588379

Average_Loss:  0.7644882131190527
Average_Accuracy:  0.7602405110860578
Confusion Matrix: 
 [[485 230  91]
 [ 54 793  76]
 [ 40 147 745]]
Epoch:  26 

Validation 

Validation Loss:  1.0323115984598796
Validation Accuracy:  0.48172323759791125
Confusion Matrix: 
 [[ 73 112 114]
 [ 43 185  53]
 [ 19  56 111]]
Train 



Batch:  40 / 84
Batch Recognition loss:  0.7740389704704285
Batch:  80 / 84
Batch Recognition loss:  0.774495005607605

Average_Loss:  0.7422685970862707
Average_Accuracy:  0.7857948139797069
Confusion Matrix: 
 [[528 200  78]
 [ 54 807  62]
 [ 41 135 756]]
Epoch:  27 

Validation 

Validation Loss:  1.047812211016814
Validation Accuracy:  0.46475195822454307
Confusion Matrix: 
 [[ 70 115 114]
 [ 45 176  60]
 [ 18  58 110]]
Train 



Batch:  40 / 84
Batch Recognition loss:  0.8758595585823059
Batch:  80 / 84
Batch Recognition loss:  0.6925147175788879

Average_Loss:  0.7486860681147802
Average_Accuracy:  0.7782788425403984
Confusion Matrix: 
 [[523 200  83]
 [ 60 795  68]
 [ 50 129 753]]
Epoch:  28 

Validation 

Validation Loss:  1.0287718698382378
Validation Accuracy:  0.49738903394255873
Confusion Matrix: 
 [[103 116  80]
 [ 46 173  62]
 [ 25  56 105]]
Train 



Batch:  40 / 84
Batch Recognition loss:  0.9694812297821045
Batch:  80 / 84
Batch Recognition loss:  0.6510097980499268

Average_Loss:  0.750499115103767
Average_Accuracy:  0.7831642239759489
Confusion Matrix: 
 [[535 186  85]
 [ 59 790  74]
 [ 44 129 759]]
Epoch:  29 

Validation 

Validation Loss:  1.0674322570363681
Validation Accuracy:  0.45691906005221933
Confusion Matrix: 
 [[ 60  94 145]
 [ 27 156  98]
 [  6  46 134]]
Train 



Batch:  40 / 84
Batch Recognition loss:  0.7415968179702759
Batch:  80 / 84
Batch Recognition loss:  0.7081117033958435

Average_Loss:  0.737054467910812
Average_Accuracy:  0.7918075911311537
Confusion Matrix: 
 [[530 185  91]
 [ 50 810  63]
 [ 39 126 767]]
Epoch:  30 

Validation 

Validation Loss:  1.022267093261083
Validation Accuracy:  0.4908616187989556
Confusion Matrix: 
 [[105 134  60]
 [ 58 188  35]
 [ 35  68  83]]
Train 



Batch:  40 / 84
Batch Recognition loss:  0.686148464679718
Batch:  80 / 84
Batch Recognition loss:  0.9667323231697083

Average_Loss:  0.745450999765169
Average_Accuracy:  0.7857948139797069
Confusion Matrix: 
 [[525 198  83]
 [ 55 800  68]
 [ 31 135 766]]
Epoch:  31 

Validation 

Validation Loss:  1.0000218078494072
Validation Accuracy:  0.5248041775456919
Confusion Matrix: 
 [[117 119  63]
 [ 64 178  39]
 [ 21  58 107]]
Train 



Batch:  40 / 84
Batch Recognition loss:  0.6812223792076111
Batch:  80 / 84
Batch Recognition loss:  0.8035194277763367

Average_Loss:  0.7441324925138837
Average_Accuracy:  0.7891770011273957
Confusion Matrix: 
 [[546 182  78]
 [ 50 813  60]
 [ 50 141 741]]
Epoch:  32 

Validation 

Validation Loss:  1.0324652617176373
Validation Accuracy:  0.49869451697127937
Confusion Matrix: 
 [[126 111  62]
 [ 69 161  51]
 [ 35  56  95]]
Train 



Batch:  40 / 84
Batch Recognition loss:  0.6398575305938721
Batch:  80 / 84
Batch Recognition loss:  0.6555256843566895

Average_Loss:  0.7424753031560353
Average_Accuracy:  0.7884254039834648
Confusion Matrix: 
 [[541 188  77]
 [ 55 802  66]
 [ 43 134 755]]
Epoch:  33 

Validation 

Validation Loss:  1.0280574038624763
Validation Accuracy:  0.4699738903394256
Confusion Matrix: 
 [[ 71 153  75]
 [ 36 201  44]
 [ 22  76  88]]
Train 



Batch:  40 / 84
Batch Recognition loss:  0.7808225154876709
Batch:  80 / 84
Batch Recognition loss:  0.7695072293281555

Average_Loss:  0.7387812556255431
Average_Accuracy:  0.7899285982713266
Confusion Matrix: 
 [[548 182  76]
 [ 51 807  65]
 [ 40 145 747]]
Epoch:  34 

Validation 

Validation Loss:  1.036445530752341
Validation Accuracy:  0.4725848563968668
Confusion Matrix: 
 [[ 61 159  79]
 [ 36 204  41]
 [ 15  74  97]]
Train 



Batch:  40 / 84
Batch Recognition loss:  0.7314631342887878
Batch:  80 / 84
Batch Recognition loss:  0.6391487121582031

Average_Loss:  0.7461438604763576
Average_Accuracy:  0.7842916196918451
Confusion Matrix: 
 [[529 197  80]
 [ 50 809  64]
 [ 47 136 749]]
Epoch:  35 

Validation 

Validation Loss:  0.9977785870432854
Validation Accuracy:  0.5248041775456919
Confusion Matrix: 
 [[107 107  85]
 [ 58 180  43]
 [ 26  45 115]]
Train 



Batch:  40 / 84
Batch Recognition loss:  0.7201552391052246
Batch:  80 / 84
Batch Recognition loss:  0.8170602321624756

Average_Loss:  0.73641988776979
Average_Accuracy:  0.7970687711386697
Confusion Matrix: 
 [[557 184  65]
 [ 38 821  64]
 [ 47 142 743]]
Epoch:  36 

Validation 

Validation Loss:  1.0187197973330815
Validation Accuracy:  0.5195822454308094
Confusion Matrix: 
 [[111  92  96]
 [ 69 155  57]
 [ 34  20 132]]
Train 



Batch:  40 / 84
Batch Recognition loss:  0.6528623104095459
Batch:  80 / 84
Batch Recognition loss:  0.6970171928405762

Average_Loss:  0.7268188659633908
Average_Accuracy:  0.8068395340097707
Confusion Matrix: 
 [[571 166  69]
 [ 40 820  63]
 [ 39 137 756]]
Epoch:  37 

Validation 

Validation Loss:  1.0138715952634811
Validation Accuracy:  0.54177545691906
Confusion Matrix: 
 [[183  69  47]
 [104 141  36]
 [ 64  31  91]]
Train 



Batch:  40 / 84
Batch Recognition loss:  0.6443488001823425
Batch:  80 / 84
Batch Recognition loss:  0.7579065561294556

Average_Loss:  0.7271485548643839
Average_Accuracy:  0.8038331454340474
Confusion Matrix: 
 [[561 165  80]
 [ 37 818  68]
 [ 41 131 760]]
Epoch:  38 

Validation 

Validation Loss:  0.9910274669528008
Validation Accuracy:  0.5509138381201044
Confusion Matrix: 
 [[140  99  60]
 [ 73 169  39]
 [ 39  34 113]]
Train 



Batch:  40 / 84
Batch Recognition loss:  0.7895197868347168
Batch:  80 / 84
Batch Recognition loss:  0.7697907090187073

Average_Loss:  0.7334833790858587
Average_Accuracy:  0.7989477639984968
Confusion Matrix: 
 [[550 169  87]
 [ 53 808  62]
 [ 37 127 768]]
Epoch:  39 

Validation 

Validation Loss:  1.0508493433396022
Validation Accuracy:  0.46475195822454307
Confusion Matrix: 
 [[ 59 110 130]
 [ 40 167  74]
 [ 26  30 130]]
Train 



Batch:  40 / 84
Batch Recognition loss:  0.8266117572784424
Batch:  80 / 84
Batch Recognition loss:  0.7099444270133972

Average_Loss:  0.7321850352344059
Average_Accuracy:  0.7966929725667042
Confusion Matrix: 
 [[539 183  84]
 [ 43 826  54]
 [ 37 140 755]]
Epoch:  40 

Validation 

Validation Loss:  1.0321768249074619
Validation Accuracy:  0.4908616187989556
Confusion Matrix: 
 [[ 87  91 121]
 [ 53 154  74]
 [ 23  28 135]]
Train 



Batch:  40 / 84
Batch Recognition loss:  0.719455897808075
Batch:  80 / 84
Batch Recognition loss:  0.7145404815673828

Average_Loss:  0.7309763388974326
Average_Accuracy:  0.7974445697106352
Confusion Matrix: 
 [[556 177  73]
 [ 54 819  50]
 [ 44 141 747]]
Epoch:  41 

Validation 

Validation Loss:  1.0349264591932297
Validation Accuracy:  0.5065274151436031
Confusion Matrix: 
 [[154  79  66]
 [ 87 144  50]
 [ 41  55  90]]
Train 



Batch:  40 / 84
Batch Recognition loss:  0.8404581546783447
Batch:  80 / 84
Batch Recognition loss:  0.6602910757064819

Average_Loss:  0.7267599070356006
Average_Accuracy:  0.8079669297256671
Confusion Matrix: 
 [[562 173  71]
 [ 46 821  56]
 [ 48 117 767]]
Epoch:  42 

Validation 

Validation Loss:  1.0168808673818905
Validation Accuracy:  0.52088772845953
Confusion Matrix: 
 [[110  83 106]
 [ 46 157  78]
 [ 29  25 132]]
Train 



Batch:  40 / 84
Batch Recognition loss:  0.6270672082901001
Batch:  80 / 84
Batch Recognition loss:  0.7656920552253723

Average_Loss:  0.7330234327486583
Average_Accuracy:  0.798196166854566
Confusion Matrix: 
 [[538 196  72]
 [ 50 809  64]
 [ 40 115 777]]
Epoch:  43 

Validation 

Validation Loss:  1.0469973782698314
Validation Accuracy:  0.4804177545691906
Confusion Matrix: 
 [[119 101  79]
 [ 79 170  32]
 [ 52  55  79]]
Train 



Batch:  40 / 84
Batch Recognition loss:  0.705325722694397
Batch:  80 / 84
Batch Recognition loss:  0.7511523365974426

Average_Loss:  0.7326854311284565
Average_Accuracy:  0.7951897782788425
Confusion Matrix: 
 [[564 171  71]
 [ 46 827  50]
 [ 44 163 725]]
Epoch:  44 

Validation 

Validation Loss:  1.0323423519730568
Validation Accuracy:  0.4934725848563969
Confusion Matrix: 
 [[ 86 111 102]
 [ 47 178  56]
 [ 34  38 114]]
Train 



Batch:  40 / 84
Batch Recognition loss:  0.7823417782783508
Batch:  80 / 84
Batch Recognition loss:  0.788884162902832

Average_Loss:  0.7291285679453895
Average_Accuracy:  0.8045847425779782
Confusion Matrix: 
 [[558 181  67]
 [ 52 820  51]
 [ 40 129 763]]
Epoch:  45 

Validation 

Validation Loss:  1.0683585777878761
Validation Accuracy:  0.4830287206266319
Confusion Matrix: 
 [[193  80  26]
 [134 127  20]
 [ 96  40  50]]
Train 



Batch:  40 / 84
Batch Recognition loss:  0.6977657675743103
Batch:  80 / 84
Batch Recognition loss:  0.7042420506477356

Average_Loss:  0.7333018907478878
Average_Accuracy:  0.8019541525742202
Confusion Matrix: 
 [[577 159  70]
 [ 58 808  57]
 [ 57 126 749]]
Epoch:  46 

Validation 

Validation Loss:  1.0459173992276192
Validation Accuracy:  0.49477806788511747
Confusion Matrix: 
 [[144 100  55]
 [ 98 140  43]
 [ 50  41  95]]
Train 



Batch:  40 / 84
Batch Recognition loss:  0.6563746333122253
Batch:  80 / 84
Batch Recognition loss:  0.7597068548202515

Average_Loss:  0.7299504358144033
Average_Accuracy:  0.7996993611424277
Confusion Matrix: 
 [[561 175  70]
 [ 53 820  50]
 [ 34 151 747]]
Epoch:  47 

Validation 

Validation Loss:  1.026978721221288
Validation Accuracy:  0.5234986945169713
Confusion Matrix: 
 [[150  76  73]
 [ 88 143  50]
 [ 50  28 108]]
Train 



Batch:  40 / 84
Batch Recognition loss:  0.7041772603988647
Batch:  80 / 84
Batch Recognition loss:  0.7278287410736084

Average_Loss:  0.7508907743862697
Average_Accuracy:  0.7820368282600526
Confusion Matrix: 
 [[539 193  74]
 [ 70 798  55]
 [ 60 128 744]]
Epoch:  48 

Validation 

Validation Loss:  1.0514092420538266
Validation Accuracy:  0.46736292428198434
Confusion Matrix: 
 [[ 86 116  97]
 [ 43 161  77]
 [ 27  48 111]]
Train 



Batch:  40 / 84
Batch Recognition loss:  0.7148075103759766
Batch:  80 / 84
Batch Recognition loss:  0.7559669017791748

Average_Loss:  0.7314229025727227
Average_Accuracy:  0.7978203682826005
Confusion Matrix: 
 [[534 188  84]
 [ 44 818  61]
 [ 39 122 771]]
Epoch:  49 

Validation 

Validation Loss:  1.0628923624753952
Validation Accuracy:  0.45691906005221933
Confusion Matrix: 
 [[115 116  68]
 [ 78 165  38]
 [ 52  64  70]]
Train 



Batch:  40 / 84
Batch Recognition loss:  0.842606246471405
Batch:  80 / 84
Batch Recognition loss:  0.6719943284988403

Average_Loss:  0.732770534498351
Average_Accuracy:  0.7974445697106352
Confusion Matrix: 
 [[558 182  66]
 [ 52 821  50]
 [ 48 141 743]]
Epoch:  50 

Validation 

Validation Loss:  1.0283719102541606
Validation Accuracy:  0.47780678851174935
Confusion Matrix: 
 [[ 64 146  89]
 [ 29 197  55]
 [ 28  53 105]]
Train 



Batch:  40 / 84
Batch Recognition loss:  0.6450212597846985
Batch:  80 / 84
Batch Recognition loss:  0.7017750144004822

Average_Loss:  0.7332355883859453
Average_Accuracy:  0.8023299511461857
Confusion Matrix: 
 [[565 163  78]
 [ 54 812  57]
 [ 44 130 758]]
