In [ ]:
import torch
from torch import nn,optim

import resnet
import invres


class resampling(nn.Module):
    dim=64
    def __init__(self):
        super(resampling, self).__init__()
        
        self.encoder=resnet.resnet18(dim=dim)
        self.decoder=invres.invresnet18(dim=dim)
        self.sig=nn.Sigmoid()
    def forward(self,x)
        x=self.decoder(self.encoder(x))
        x=self.sig(x)
        return x




In [12]:
import torch

In [15]:
a=torch.rand((3,3))
b=torch.rand((3,3))

In [16]:
a

tensor([[0.7641, 0.7049, 0.8367],
        [0.4658, 0.4544, 0.4993],
        [0.2380, 0.9539, 0.4049]])

In [17]:
b

tensor([[0.2247, 0.4967, 0.3269],
        [0.8757, 0.9494, 0.1514],
        [0.8359, 0.3956, 0.7584]])

In [19]:
a*b

tensor([[0.1717, 0.3501, 0.2735],
        [0.4079, 0.4314, 0.0756],
        [0.1990, 0.3773, 0.3071]])

In [20]:
0.2247*0.7641

0.17169327